// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/bstream/v1/bstream.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockKind int32

const (
	BlockKind_UNKNOWN BlockKind = 0
	BlockKind_EOS     BlockKind = 1
	BlockKind_ETH     BlockKind = 2
)

var BlockKind_name = map[int32]string{
	0: "UNKNOWN",
	1: "EOS",
	2: "ETH",
}

var BlockKind_value = map[string]int32{
	"UNKNOWN": 0,
	"EOS":     1,
	"ETH":     2,
}

func (x BlockKind) String() string {
	return proto.EnumName(BlockKind_name, int32(x))
}

func (BlockKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{0}
}

// Whether we can assume the data will come ordered, unless there is a chain reorganization.
// mindreaders output ordered data, whereas relayers can output unordered data.
// The server can fail early if the assumption of the caller cannot be fulfilled.
type BlockRequest_Order int32

const (
	BlockRequest_UNSPECIFIED BlockRequest_Order = 0
	BlockRequest_ORDERED     BlockRequest_Order = 1
	BlockRequest_UNORDERED   BlockRequest_Order = 2
)

var BlockRequest_Order_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "ORDERED",
	2: "UNORDERED",
}

var BlockRequest_Order_value = map[string]int32{
	"UNSPECIFIED": 0,
	"ORDERED":     1,
	"UNORDERED":   2,
}

func (x BlockRequest_Order) String() string {
	return proto.EnumName(BlockRequest_Order_name, int32(x))
}

func (BlockRequest_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{0, 0}
}

type BlockRequest struct {
	// Number of blocks we want to get in burst upon connection, on a best effort basis.
	Burst int64 `protobuf:"varint,1,opt,name=burst,proto3" json:"burst,omitempty"`
	// Type of blocks we're after here, is it 'ethereum' data, 'eos', etc.. The server can fail early
	// if he doesn't match the data he serves (services mismatch, etc..)
	ContentType          string             `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Order                BlockRequest_Order `protobuf:"varint,3,opt,name=order,proto3,enum=dfuse.bstream.v1.BlockRequest_Order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{0}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetBurst() int64 {
	if m != nil {
		return m.Burst
	}
	return 0
}

func (m *BlockRequest) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *BlockRequest) GetOrder() BlockRequest_Order {
	if m != nil {
		return m.Order
	}
	return BlockRequest_UNSPECIFIED
}

type Block struct {
	Number               uint64               `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PreviousId           string               `protobuf:"bytes,3,opt,name=previous_id,json=previousId,proto3" json:"previous_id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LibNum               uint64               `protobuf:"varint,5,opt,name=lib_num,json=libNum,proto3" json:"lib_num,omitempty"`
	PayloadKind          BlockKind            `protobuf:"varint,6,opt,name=payload_kind,json=payloadKind,proto3,enum=dfuse.bstream.v1.BlockKind" json:"payload_kind,omitempty"`
	PayloadVersion       int32                `protobuf:"varint,7,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	PayloadBuffer        []byte               `protobuf:"bytes,8,opt,name=payload_buffer,json=payloadBuffer,proto3" json:"payload_buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Block) GetPreviousId() string {
	if m != nil {
		return m.PreviousId
	}
	return ""
}

func (m *Block) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Block) GetLibNum() uint64 {
	if m != nil {
		return m.LibNum
	}
	return 0
}

func (m *Block) GetPayloadKind() BlockKind {
	if m != nil {
		return m.PayloadKind
	}
	return BlockKind_UNKNOWN
}

func (m *Block) GetPayloadVersion() int32 {
	if m != nil {
		return m.PayloadVersion
	}
	return 0
}

func (m *Block) GetPayloadBuffer() []byte {
	if m != nil {
		return m.PayloadBuffer
	}
	return nil
}

func init() {
	proto.RegisterEnum("dfuse.bstream.v1.BlockKind", BlockKind_name, BlockKind_value)
	proto.RegisterEnum("dfuse.bstream.v1.BlockRequest_Order", BlockRequest_Order_name, BlockRequest_Order_value)
	proto.RegisterType((*BlockRequest)(nil), "dfuse.bstream.v1.BlockRequest")
	proto.RegisterType((*Block)(nil), "dfuse.bstream.v1.Block")
}

func init() { proto.RegisterFile("dfuse/bstream/v1/bstream.proto", fileDescriptor_9cfb17be2e7d1b7d) }

var fileDescriptor_9cfb17be2e7d1b7d = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x6f, 0xda, 0x3e,
	0x18, 0xc6, 0xeb, 0xd0, 0xc0, 0x9f, 0x37, 0x94, 0x46, 0xd6, 0x5f, 0x6b, 0xc4, 0xa4, 0x36, 0x43,
	0x9b, 0x16, 0xf5, 0x90, 0xb4, 0x6c, 0x87, 0x69, 0x87, 0x1d, 0x28, 0x4c, 0x43, 0x95, 0xc2, 0x64,
	0x60, 0x93, 0x76, 0x41, 0x09, 0x36, 0xcc, 0x2a, 0x89, 0xb3, 0xc4, 0x46, 0xe2, 0x73, 0xed, 0xb4,
	0x6f, 0x37, 0xe1, 0x24, 0x6c, 0xaa, 0xd4, 0xdd, 0xfc, 0xfc, 0xde, 0xf7, 0x89, 0x1f, 0x3d, 0x31,
	0x5c, 0xd2, 0xb5, 0x2a, 0x58, 0x10, 0x17, 0x32, 0x67, 0x51, 0x12, 0xec, 0x6e, 0xeb, 0xa3, 0x9f,
	0xe5, 0x42, 0x0a, 0x6c, 0xeb, 0xb9, 0x5f, 0xc3, 0xdd, 0x6d, 0xef, 0x6a, 0x23, 0xc4, 0x66, 0xcb,
	0x02, 0x3d, 0x8f, 0xd5, 0x3a, 0x90, 0x3c, 0x61, 0x85, 0x8c, 0x92, 0xac, 0xb4, 0xf4, 0x7f, 0x21,
	0xe8, 0x0c, 0xb7, 0x62, 0xf5, 0x40, 0xd8, 0x0f, 0xc5, 0x0a, 0x89, 0xff, 0x07, 0x33, 0x56, 0x79,
	0x21, 0x1d, 0xe4, 0x22, 0xaf, 0x41, 0x4a, 0x81, 0x5f, 0x40, 0x67, 0x25, 0x52, 0xc9, 0x52, 0xb9,
	0x94, 0xfb, 0x8c, 0x39, 0x86, 0x8b, 0xbc, 0x36, 0xb1, 0x2a, 0x36, 0xdf, 0x67, 0x0c, 0xbf, 0x07,
	0x53, 0xe4, 0x94, 0xe5, 0x4e, 0xc3, 0x45, 0x5e, 0x77, 0xf0, 0xd2, 0x7f, 0x1c, 0xc6, 0xff, 0xfb,
	0x1e, 0x7f, 0x7a, 0xd8, 0x25, 0xa5, 0xa5, 0xff, 0x16, 0x4c, 0xad, 0xf1, 0x39, 0x58, 0x8b, 0x70,
	0xf6, 0x79, 0x7c, 0x37, 0xf9, 0x38, 0x19, 0x8f, 0xec, 0x13, 0x6c, 0x41, 0x6b, 0x4a, 0x46, 0x63,
	0x32, 0x1e, 0xd9, 0x08, 0x9f, 0x41, 0x7b, 0x11, 0xd6, 0xd2, 0xe8, 0xff, 0x34, 0xc0, 0xd4, 0xdf,
	0xc4, 0xcf, 0xa0, 0x99, 0xaa, 0x24, 0x66, 0xb9, 0x4e, 0x7d, 0x4a, 0x2a, 0x85, 0xbb, 0x60, 0x70,
	0x5a, 0x85, 0x35, 0x38, 0xc5, 0x57, 0x60, 0x65, 0x39, 0xdb, 0x71, 0xa1, 0x8a, 0x25, 0xa7, 0x3a,
	0x69, 0x9b, 0x40, 0x8d, 0x26, 0x14, 0xbf, 0x83, 0xf6, 0xb1, 0x21, 0xe7, 0xd4, 0x45, 0x9e, 0x35,
	0xe8, 0xf9, 0x65, 0x87, 0x7e, 0xdd, 0xa1, 0x3f, 0xaf, 0x37, 0xc8, 0x9f, 0x65, 0x7c, 0x01, 0xad,
	0x2d, 0x8f, 0x97, 0xa9, 0x4a, 0x1c, 0xb3, 0xcc, 0xb0, 0xe5, 0x71, 0xa8, 0x12, 0xfc, 0x01, 0x3a,
	0x59, 0xb4, 0xdf, 0x8a, 0x88, 0x2e, 0x1f, 0x78, 0x4a, 0x9d, 0xa6, 0xae, 0xe7, 0xf9, 0x13, 0xf5,
	0xdc, 0xf3, 0x94, 0x12, 0xab, 0x32, 0x1c, 0x04, 0x7e, 0x0d, 0xe7, 0xb5, 0x7f, 0xc7, 0xf2, 0x82,
	0x8b, 0xd4, 0x69, 0xb9, 0xc8, 0x33, 0x49, 0xb7, 0xc2, 0x5f, 0x4a, 0x8a, 0x5f, 0x41, 0x4d, 0x96,
	0xb1, 0x5a, 0xaf, 0x59, 0xee, 0xfc, 0xe7, 0x22, 0xaf, 0x43, 0xce, 0x2a, 0x3a, 0xd4, 0xf0, 0xfa,
	0x1a, 0xda, 0xc7, 0x9b, 0x0e, 0xf5, 0x2e, 0xc2, 0xfb, 0x70, 0xfa, 0x35, 0xb4, 0x4f, 0x70, 0x0b,
	0x1a, 0xe3, 0xe9, 0xcc, 0x46, 0xfa, 0x30, 0xff, 0x64, 0x1b, 0x03, 0x02, 0x96, 0xde, 0x9d, 0xe9,
	0x90, 0xf8, 0x0e, 0x9a, 0x5a, 0x16, 0xf8, 0xf2, 0xdf, 0x7f, 0xb7, 0x77, 0xf1, 0xc4, 0xfc, 0x06,
	0x0d, 0x07, 0xdf, 0x6e, 0x36, 0x5c, 0x7e, 0x57, 0xb1, 0xbf, 0x12, 0x49, 0xc0, 0x44, 0xb1, 0x8a,
	0xd2, 0x88, 0x46, 0xc7, 0x57, 0x9d, 0xc5, 0xc1, 0xe3, 0x67, 0x1e, 0x37, 0x75, 0xf7, 0x6f, 0x7e,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xbe, 0xed, 0xcc, 0x01, 0x03, 0x00, 0x00,
}
