package main

var knownProtobufTypes = []string{
	// bstream
	"dfuse.bstream.v1.Block",

	// codecs/deos
	// Generated with:
	//     cat ../service-definitions/dfuse/codecs/deos/deos.proto | grep -E "^message" | sed 's/message /"dfuse.codecs.deos./' | sed 's/ {.*/",/' | sed -E 's|//.*||' | tr -d ' '
	"dfuse.codecs.deos.Block",
	"dfuse.codecs.deos.TransactionRefs",
	"dfuse.codecs.deos.ActivatedProtocolFeatures",
	"dfuse.codecs.deos.PendingProducerSchedule",
	"dfuse.codecs.deos.ProducerSchedule",
	"dfuse.codecs.deos.BlockRootMerkle",
	"dfuse.codecs.deos.ProducerToLastProduced",
	"dfuse.codecs.deos.ProducerToLastImpliedIRB",
	"dfuse.codecs.deos.TransactionReceipt",
	"dfuse.codecs.deos.PackedTransaction",
	"dfuse.codecs.deos.BlockHeader",
	"dfuse.codecs.deos.ProducerKey",
	"dfuse.codecs.deos.TransactionLifecycle",
	"dfuse.codecs.deos.SignedTransaction",
	"dfuse.codecs.deos.Transaction",
	"dfuse.codecs.deos.TransactionHeader",
	"dfuse.codecs.deos.TransactionTrace",
	"dfuse.codecs.deos.TransactionReceiptHeader",
	"dfuse.codecs.deos.Action",
	"dfuse.codecs.deos.ActionTrace",
	"dfuse.codecs.deos.ActionReceipt",
	"dfuse.codecs.deos.AuthSequence",
	"dfuse.codecs.deos.AccountRAMDelta",
	"dfuse.codecs.deos.Extension",
	"dfuse.codecs.deos.DTrxOp",
	"dfuse.codecs.deos.TrxOp",
	"dfuse.codecs.deos.DBOp",
	"dfuse.codecs.deos.RAMOp",
	"dfuse.codecs.deos.RAMCorrectionOp",
	"dfuse.codecs.deos.TableOp",
	"dfuse.codecs.deos.ExtDTrxOp",
	"dfuse.codecs.deos.FeatureOp",
	"dfuse.codecs.deos.CreationFlatNode",
	"dfuse.codecs.deos.PermOp",
	"dfuse.codecs.deos.PermissionObject",
	"dfuse.codecs.deos.Permission",
	"dfuse.codecs.deos.Authority",
	"dfuse.codecs.deos.KeyWeight",
	"dfuse.codecs.deos.PermissionLevel",
	"dfuse.codecs.deos.PermissionLevelWeight",
	"dfuse.codecs.deos.WaitWeight",
	"dfuse.codecs.deos.RlimitOp",
	"dfuse.codecs.deos.RlimitState",
	"dfuse.codecs.deos.RlimitConfig",
	"dfuse.codecs.deos.RlimitAccountLimits",
	"dfuse.codecs.deos.RlimitAccountUsage",
	"dfuse.codecs.deos.UsageAccumulator",
	"dfuse.codecs.deos.ElasticLimitParameters",
	"dfuse.codecs.deos.Ratio",
	"dfuse.codecs.deos.StackItemContext",
	"dfuse.codecs.deos.StackItem",
	"dfuse.codecs.deos.Exception",
	"dfuse.codecs.deos.Feature",
	"dfuse.codecs.deos.SubjectiveRestrictions",
	"dfuse.codecs.deos.Specification",

	// codecs/deos
	// Generated with:
	//     cat ../service-definitions/dfuse/codecs/deth/deth.proto | grep -E "^message" | sed 's/message /"dfuse.codecs.deth./' | sed 's/ {.*/",/' | sed -E 's|//.*||' | tr -d ' '
	"dfuse.codecs.deth.Block",
	"dfuse.codecs.deth.TransactionRefs",
	"dfuse.codecs.deth.UnclesHeaders",
	"dfuse.codecs.deth.BlockRef",
	"dfuse.codecs.deth.BlockHeader",
	"dfuse.codecs.deth.BigInt",
	"dfuse.codecs.deth.TransactionState",
	"dfuse.codecs.deth.Transaction",
	"dfuse.codecs.deth.TransactionTrace",
	"dfuse.codecs.deth.TransactionReceipt",
	"dfuse.codecs.deth.Log",
	"dfuse.codecs.deth.Call",
	"dfuse.codecs.deth.StorageChange",
	"dfuse.codecs.deth.BalanceChange",
	"dfuse.codecs.deth.NonceChange",
	"dfuse.codecs.deth.CodeChange",
	"dfuse.codecs.deth.GasChange",
	"dfuse.codecs.deth.GasEvent",
}
