// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/codecs/deos/deos.proto

package deos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockReversibility int32

const (
	BlockReversibility_BLOCKREVERSIBILITY_NONE         BlockReversibility = 0
	BlockReversibility_BLOCKREVERSIBILITY_REVERSIBLE   BlockReversibility = 1
	BlockReversibility_BLOCKREVERSIBILITY_IRREVERSIBLE BlockReversibility = 2
	BlockReversibility_BLOCKREVERSIBILITY_STALE        BlockReversibility = 3
	BlockReversibility_BLOCKREVERSIBILITY_MAYBESTALE   BlockReversibility = 4
)

var BlockReversibility_name = map[int32]string{
	0: "BLOCKREVERSIBILITY_NONE",
	1: "BLOCKREVERSIBILITY_REVERSIBLE",
	2: "BLOCKREVERSIBILITY_IRREVERSIBLE",
	3: "BLOCKREVERSIBILITY_STALE",
	4: "BLOCKREVERSIBILITY_MAYBESTALE",
}

var BlockReversibility_value = map[string]int32{
	"BLOCKREVERSIBILITY_NONE":         0,
	"BLOCKREVERSIBILITY_REVERSIBLE":   1,
	"BLOCKREVERSIBILITY_IRREVERSIBLE": 2,
	"BLOCKREVERSIBILITY_STALE":        3,
	"BLOCKREVERSIBILITY_MAYBESTALE":   4,
}

func (x BlockReversibility) String() string {
	return proto.EnumName(BlockReversibility_name, int32(x))
}

func (BlockReversibility) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{0}
}

type TransactionStatus int32

const (
	TransactionStatus_TRANSACTIONSTATUS_NONE     TransactionStatus = 0
	TransactionStatus_TRANSACTIONSTATUS_EXECUTED TransactionStatus = 1
	TransactionStatus_TRANSACTIONSTATUS_SOFTFAIL TransactionStatus = 2
	TransactionStatus_TRANSACTIONSTATUS_HARDFAIL TransactionStatus = 3
	TransactionStatus_TRANSACTIONSTATUS_DELAYED  TransactionStatus = 4
	TransactionStatus_TRANSACTIONSTATUS_EXPIRED  TransactionStatus = 5
	TransactionStatus_TRANSACTIONSTATUS_UNKNOWN  TransactionStatus = 6
	TransactionStatus_TRANSACTIONSTATUS_CANCELED TransactionStatus = 7
)

var TransactionStatus_name = map[int32]string{
	0: "TRANSACTIONSTATUS_NONE",
	1: "TRANSACTIONSTATUS_EXECUTED",
	2: "TRANSACTIONSTATUS_SOFTFAIL",
	3: "TRANSACTIONSTATUS_HARDFAIL",
	4: "TRANSACTIONSTATUS_DELAYED",
	5: "TRANSACTIONSTATUS_EXPIRED",
	6: "TRANSACTIONSTATUS_UNKNOWN",
	7: "TRANSACTIONSTATUS_CANCELED",
}

var TransactionStatus_value = map[string]int32{
	"TRANSACTIONSTATUS_NONE":     0,
	"TRANSACTIONSTATUS_EXECUTED": 1,
	"TRANSACTIONSTATUS_SOFTFAIL": 2,
	"TRANSACTIONSTATUS_HARDFAIL": 3,
	"TRANSACTIONSTATUS_DELAYED":  4,
	"TRANSACTIONSTATUS_EXPIRED":  5,
	"TRANSACTIONSTATUS_UNKNOWN":  6,
	"TRANSACTIONSTATUS_CANCELED": 7,
}

func (x TransactionStatus) String() string {
	return proto.EnumName(TransactionStatus_name, int32(x))
}

func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{1}
}

type BlockLifecycle struct {
	State                *BlockState  `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Block                *SignedBlock `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	DposLIBNum           uint32       `protobuf:"varint,3,opt,name=dposLIBNum,proto3" json:"dposLIBNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BlockLifecycle) Reset()         { *m = BlockLifecycle{} }
func (m *BlockLifecycle) String() string { return proto.CompactTextString(m) }
func (*BlockLifecycle) ProtoMessage()    {}
func (*BlockLifecycle) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{0}
}

func (m *BlockLifecycle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockLifecycle.Unmarshal(m, b)
}
func (m *BlockLifecycle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockLifecycle.Marshal(b, m, deterministic)
}
func (m *BlockLifecycle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockLifecycle.Merge(m, src)
}
func (m *BlockLifecycle) XXX_Size() int {
	return xxx_messageInfo_BlockLifecycle.Size(m)
}
func (m *BlockLifecycle) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockLifecycle.DiscardUnknown(m)
}

var xxx_messageInfo_BlockLifecycle proto.InternalMessageInfo

func (m *BlockLifecycle) GetState() *BlockState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *BlockLifecycle) GetBlock() *SignedBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockLifecycle) GetDposLIBNum() uint32 {
	if m != nil {
		return m.DposLIBNum
	}
	return 0
}

type SignedBlock struct {
	BlockHeader          *BlockHeader          `protobuf:"bytes,1,opt,name=blockHeader,proto3" json:"blockHeader,omitempty"`
	ProducerSignature    string                `protobuf:"bytes,2,opt,name=producerSignature,proto3" json:"producerSignature,omitempty"`
	Transactions         []*TransactionReceipt `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	BlockExtensions      []*Extension          `protobuf:"bytes,4,rep,name=blockExtensions,proto3" json:"blockExtensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SignedBlock) Reset()         { *m = SignedBlock{} }
func (m *SignedBlock) String() string { return proto.CompactTextString(m) }
func (*SignedBlock) ProtoMessage()    {}
func (*SignedBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{1}
}

func (m *SignedBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedBlock.Unmarshal(m, b)
}
func (m *SignedBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedBlock.Marshal(b, m, deterministic)
}
func (m *SignedBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedBlock.Merge(m, src)
}
func (m *SignedBlock) XXX_Size() int {
	return xxx_messageInfo_SignedBlock.Size(m)
}
func (m *SignedBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SignedBlock proto.InternalMessageInfo

func (m *SignedBlock) GetBlockHeader() *BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

func (m *SignedBlock) GetProducerSignature() string {
	if m != nil {
		return m.ProducerSignature
	}
	return ""
}

func (m *SignedBlock) GetTransactions() []*TransactionReceipt {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *SignedBlock) GetBlockExtensions() []*Extension {
	if m != nil {
		return m.BlockExtensions
	}
	return nil
}

type TransactionReceipt struct {
	Status               string             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CpuUsageMicroSeconds uint32             `protobuf:"varint,2,opt,name=cpuUsageMicroSeconds,proto3" json:"cpuUsageMicroSeconds,omitempty"`
	NetUsageWords        uint32             `protobuf:"varint,3,opt,name=netUsageWords,proto3" json:"netUsageWords,omitempty"`
	TransactionWithId    *TransactionWithID `protobuf:"bytes,4,opt,name=transactionWithId,proto3" json:"transactionWithId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TransactionReceipt) Reset()         { *m = TransactionReceipt{} }
func (m *TransactionReceipt) String() string { return proto.CompactTextString(m) }
func (*TransactionReceipt) ProtoMessage()    {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{2}
}

func (m *TransactionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReceipt.Unmarshal(m, b)
}
func (m *TransactionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReceipt.Marshal(b, m, deterministic)
}
func (m *TransactionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReceipt.Merge(m, src)
}
func (m *TransactionReceipt) XXX_Size() int {
	return xxx_messageInfo_TransactionReceipt.Size(m)
}
func (m *TransactionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReceipt proto.InternalMessageInfo

func (m *TransactionReceipt) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TransactionReceipt) GetCpuUsageMicroSeconds() uint32 {
	if m != nil {
		return m.CpuUsageMicroSeconds
	}
	return 0
}

func (m *TransactionReceipt) GetNetUsageWords() uint32 {
	if m != nil {
		return m.NetUsageWords
	}
	return 0
}

func (m *TransactionReceipt) GetTransactionWithId() *TransactionWithID {
	if m != nil {
		return m.TransactionWithId
	}
	return nil
}

type TransactionWithID struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PackedTransaction    *PackedTransaction `protobuf:"bytes,2,opt,name=packedTransaction,proto3" json:"packedTransaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TransactionWithID) Reset()         { *m = TransactionWithID{} }
func (m *TransactionWithID) String() string { return proto.CompactTextString(m) }
func (*TransactionWithID) ProtoMessage()    {}
func (*TransactionWithID) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{3}
}

func (m *TransactionWithID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionWithID.Unmarshal(m, b)
}
func (m *TransactionWithID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionWithID.Marshal(b, m, deterministic)
}
func (m *TransactionWithID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionWithID.Merge(m, src)
}
func (m *TransactionWithID) XXX_Size() int {
	return xxx_messageInfo_TransactionWithID.Size(m)
}
func (m *TransactionWithID) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionWithID.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionWithID proto.InternalMessageInfo

func (m *TransactionWithID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TransactionWithID) GetPackedTransaction() *PackedTransaction {
	if m != nil {
		return m.PackedTransaction
	}
	return nil
}

type PackedTransaction struct {
	Signatures            []string `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Compression           uint32   `protobuf:"varint,2,opt,name=compression,proto3" json:"compression,omitempty"`
	PackedContextFreeData []byte   `protobuf:"bytes,3,opt,name=packedContextFreeData,proto3" json:"packedContextFreeData,omitempty"`
	PackedTransaction     []byte   `protobuf:"bytes,4,opt,name=packedTransaction,proto3" json:"packedTransaction,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *PackedTransaction) Reset()         { *m = PackedTransaction{} }
func (m *PackedTransaction) String() string { return proto.CompactTextString(m) }
func (*PackedTransaction) ProtoMessage()    {}
func (*PackedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{4}
}

func (m *PackedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackedTransaction.Unmarshal(m, b)
}
func (m *PackedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackedTransaction.Marshal(b, m, deterministic)
}
func (m *PackedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackedTransaction.Merge(m, src)
}
func (m *PackedTransaction) XXX_Size() int {
	return xxx_messageInfo_PackedTransaction.Size(m)
}
func (m *PackedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_PackedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_PackedTransaction proto.InternalMessageInfo

func (m *PackedTransaction) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *PackedTransaction) GetCompression() uint32 {
	if m != nil {
		return m.Compression
	}
	return 0
}

func (m *PackedTransaction) GetPackedContextFreeData() []byte {
	if m != nil {
		return m.PackedContextFreeData
	}
	return nil
}

func (m *PackedTransaction) GetPackedTransaction() []byte {
	if m != nil {
		return m.PackedTransaction
	}
	return nil
}

type BlockHeader struct {
	Timestamp            *timestamp.Timestamp    `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Producer             string                  `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	Confirmed            uint32                  `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Previous             string                  `protobuf:"bytes,4,opt,name=previous,proto3" json:"previous,omitempty"`
	TransactionMRoot     string                  `protobuf:"bytes,5,opt,name=transactionMRoot,proto3" json:"transactionMRoot,omitempty"`
	ActionMRoot          string                  `protobuf:"bytes,6,opt,name=actionMRoot,proto3" json:"actionMRoot,omitempty"`
	ScheduleVersion      uint32                  `protobuf:"varint,7,opt,name=scheduleVersion,proto3" json:"scheduleVersion,omitempty"`
	NewProducers         *ProducerSchedule       `protobuf:"bytes,8,opt,name=newProducers,proto3" json:"newProducers,omitempty"`
	HeaderExtensions     []*BlockHeaderExtension `protobuf:"bytes,9,rep,name=headerExtensions,proto3" json:"headerExtensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{5}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BlockHeader) GetProducer() string {
	if m != nil {
		return m.Producer
	}
	return ""
}

func (m *BlockHeader) GetConfirmed() uint32 {
	if m != nil {
		return m.Confirmed
	}
	return 0
}

func (m *BlockHeader) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *BlockHeader) GetTransactionMRoot() string {
	if m != nil {
		return m.TransactionMRoot
	}
	return ""
}

func (m *BlockHeader) GetActionMRoot() string {
	if m != nil {
		return m.ActionMRoot
	}
	return ""
}

func (m *BlockHeader) GetScheduleVersion() uint32 {
	if m != nil {
		return m.ScheduleVersion
	}
	return 0
}

func (m *BlockHeader) GetNewProducers() *ProducerSchedule {
	if m != nil {
		return m.NewProducers
	}
	return nil
}

func (m *BlockHeader) GetHeaderExtensions() []*BlockHeaderExtension {
	if m != nil {
		return m.HeaderExtensions
	}
	return nil
}

type BlockHeaderExtension struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeaderExtension) Reset()         { *m = BlockHeaderExtension{} }
func (m *BlockHeaderExtension) String() string { return proto.CompactTextString(m) }
func (*BlockHeaderExtension) ProtoMessage()    {}
func (*BlockHeaderExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{6}
}

func (m *BlockHeaderExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaderExtension.Unmarshal(m, b)
}
func (m *BlockHeaderExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaderExtension.Marshal(b, m, deterministic)
}
func (m *BlockHeaderExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaderExtension.Merge(m, src)
}
func (m *BlockHeaderExtension) XXX_Size() int {
	return xxx_messageInfo_BlockHeaderExtension.Size(m)
}
func (m *BlockHeaderExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaderExtension.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaderExtension proto.InternalMessageInfo

func (m *BlockHeaderExtension) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *BlockHeaderExtension) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProducerSchedule struct {
	Version              uint32         `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Producers            []*ProducerKey `protobuf:"bytes,2,rep,name=producers,proto3" json:"producers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProducerSchedule) Reset()         { *m = ProducerSchedule{} }
func (m *ProducerSchedule) String() string { return proto.CompactTextString(m) }
func (*ProducerSchedule) ProtoMessage()    {}
func (*ProducerSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{7}
}

func (m *ProducerSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProducerSchedule.Unmarshal(m, b)
}
func (m *ProducerSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProducerSchedule.Marshal(b, m, deterministic)
}
func (m *ProducerSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProducerSchedule.Merge(m, src)
}
func (m *ProducerSchedule) XXX_Size() int {
	return xxx_messageInfo_ProducerSchedule.Size(m)
}
func (m *ProducerSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_ProducerSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_ProducerSchedule proto.InternalMessageInfo

func (m *ProducerSchedule) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ProducerSchedule) GetProducers() []*ProducerKey {
	if m != nil {
		return m.Producers
	}
	return nil
}

type ProducerKey struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	BlockSigningKey      string   `protobuf:"bytes,2,opt,name=blockSigningKey,proto3" json:"blockSigningKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProducerKey) Reset()         { *m = ProducerKey{} }
func (m *ProducerKey) String() string { return proto.CompactTextString(m) }
func (*ProducerKey) ProtoMessage()    {}
func (*ProducerKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{8}
}

func (m *ProducerKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProducerKey.Unmarshal(m, b)
}
func (m *ProducerKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProducerKey.Marshal(b, m, deterministic)
}
func (m *ProducerKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProducerKey.Merge(m, src)
}
func (m *ProducerKey) XXX_Size() int {
	return xxx_messageInfo_ProducerKey.Size(m)
}
func (m *ProducerKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ProducerKey.DiscardUnknown(m)
}

var xxx_messageInfo_ProducerKey proto.InternalMessageInfo

func (m *ProducerKey) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *ProducerKey) GetBlockSigningKey() string {
	if m != nil {
		return m.BlockSigningKey
	}
	return ""
}

type BlockState struct {
	Reversibility        BlockReversibility `protobuf:"varint,1,opt,name=reversibility,proto3,enum=dfuse.codecs.deos.BlockReversibility" json:"reversibility,omitempty"`
	Handoffs             uint32             `protobuf:"varint,2,opt,name=handoffs,proto3" json:"handoffs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BlockState) Reset()         { *m = BlockState{} }
func (m *BlockState) String() string { return proto.CompactTextString(m) }
func (*BlockState) ProtoMessage()    {}
func (*BlockState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{9}
}

func (m *BlockState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockState.Unmarshal(m, b)
}
func (m *BlockState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockState.Marshal(b, m, deterministic)
}
func (m *BlockState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockState.Merge(m, src)
}
func (m *BlockState) XXX_Size() int {
	return xxx_messageInfo_BlockState.Size(m)
}
func (m *BlockState) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockState.DiscardUnknown(m)
}

var xxx_messageInfo_BlockState proto.InternalMessageInfo

func (m *BlockState) GetReversibility() BlockReversibility {
	if m != nil {
		return m.Reversibility
	}
	return BlockReversibility_BLOCKREVERSIBILITY_NONE
}

func (m *BlockState) GetHandoffs() uint32 {
	if m != nil {
		return m.Handoffs
	}
	return 0
}

type TransactionLifecycle struct {
	Id                    string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionStatus     TransactionStatus   `protobuf:"varint,2,opt,name=transactionStatus,proto3,enum=dfuse.codecs.deos.TransactionStatus" json:"transactionStatus,omitempty"`
	SignedTransaction     *SignedTransaction  `protobuf:"bytes,10,opt,name=signedTransaction,proto3" json:"signedTransaction,omitempty"`
	ExecutionTrace        *TransactionTrace   `protobuf:"bytes,11,opt,name=executionTrace,proto3" json:"executionTrace,omitempty"`
	ExecutionBlockHeader  *BlockHeader        `protobuf:"bytes,12,opt,name=executionBlockHeader,proto3" json:"executionBlockHeader,omitempty"`
	DtrxOps               []*DTrxOp           `protobuf:"bytes,13,rep,name=dtrxOps,proto3" json:"dtrxOps,omitempty"`
	CreationTree          []*CreationFlatNode `protobuf:"bytes,14,rep,name=creationTree,proto3" json:"creationTree,omitempty"`
	DbOps                 []*DBOp             `protobuf:"bytes,15,rep,name=dbOps,proto3" json:"dbOps,omitempty"`
	RamOps                []*RAMOp            `protobuf:"bytes,16,rep,name=ramOps,proto3" json:"ramOps,omitempty"`
	TableOps              []*TableOp          `protobuf:"bytes,17,rep,name=tableOps,proto3" json:"tableOps,omitempty"`
	FeatureOps            []*FeatureOp        `protobuf:"bytes,18,rep,name=featureOps,proto3" json:"featureOps,omitempty"`
	PublicKeys            []string            `protobuf:"bytes,19,rep,name=publicKeys,proto3" json:"publicKeys,omitempty"`
	CreatedBy             *ExtDTrxOp          `protobuf:"bytes,20,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CanceledBy            *ExtDTrxOp          `protobuf:"bytes,21,opt,name=canceledBy,proto3" json:"canceledBy,omitempty"`
	CreationBlockState    *BlockState         `protobuf:"bytes,30,opt,name=creationBlockState,proto3" json:"creationBlockState,omitempty"`
	ExecutionBlockState   *BlockState         `protobuf:"bytes,31,opt,name=executionBlockState,proto3" json:"executionBlockState,omitempty"`
	CancelationBlockState *BlockState         `protobuf:"bytes,32,opt,name=cancelationBlockState,proto3" json:"cancelationBlockState,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}            `json:"-"`
	XXX_unrecognized      []byte              `json:"-"`
	XXX_sizecache         int32               `json:"-"`
}

func (m *TransactionLifecycle) Reset()         { *m = TransactionLifecycle{} }
func (m *TransactionLifecycle) String() string { return proto.CompactTextString(m) }
func (*TransactionLifecycle) ProtoMessage()    {}
func (*TransactionLifecycle) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{10}
}

func (m *TransactionLifecycle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionLifecycle.Unmarshal(m, b)
}
func (m *TransactionLifecycle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionLifecycle.Marshal(b, m, deterministic)
}
func (m *TransactionLifecycle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionLifecycle.Merge(m, src)
}
func (m *TransactionLifecycle) XXX_Size() int {
	return xxx_messageInfo_TransactionLifecycle.Size(m)
}
func (m *TransactionLifecycle) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionLifecycle.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionLifecycle proto.InternalMessageInfo

func (m *TransactionLifecycle) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TransactionLifecycle) GetTransactionStatus() TransactionStatus {
	if m != nil {
		return m.TransactionStatus
	}
	return TransactionStatus_TRANSACTIONSTATUS_NONE
}

func (m *TransactionLifecycle) GetSignedTransaction() *SignedTransaction {
	if m != nil {
		return m.SignedTransaction
	}
	return nil
}

func (m *TransactionLifecycle) GetExecutionTrace() *TransactionTrace {
	if m != nil {
		return m.ExecutionTrace
	}
	return nil
}

func (m *TransactionLifecycle) GetExecutionBlockHeader() *BlockHeader {
	if m != nil {
		return m.ExecutionBlockHeader
	}
	return nil
}

func (m *TransactionLifecycle) GetDtrxOps() []*DTrxOp {
	if m != nil {
		return m.DtrxOps
	}
	return nil
}

func (m *TransactionLifecycle) GetCreationTree() []*CreationFlatNode {
	if m != nil {
		return m.CreationTree
	}
	return nil
}

func (m *TransactionLifecycle) GetDbOps() []*DBOp {
	if m != nil {
		return m.DbOps
	}
	return nil
}

func (m *TransactionLifecycle) GetRamOps() []*RAMOp {
	if m != nil {
		return m.RamOps
	}
	return nil
}

func (m *TransactionLifecycle) GetTableOps() []*TableOp {
	if m != nil {
		return m.TableOps
	}
	return nil
}

func (m *TransactionLifecycle) GetFeatureOps() []*FeatureOp {
	if m != nil {
		return m.FeatureOps
	}
	return nil
}

func (m *TransactionLifecycle) GetPublicKeys() []string {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func (m *TransactionLifecycle) GetCreatedBy() *ExtDTrxOp {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *TransactionLifecycle) GetCanceledBy() *ExtDTrxOp {
	if m != nil {
		return m.CanceledBy
	}
	return nil
}

func (m *TransactionLifecycle) GetCreationBlockState() *BlockState {
	if m != nil {
		return m.CreationBlockState
	}
	return nil
}

func (m *TransactionLifecycle) GetExecutionBlockState() *BlockState {
	if m != nil {
		return m.ExecutionBlockState
	}
	return nil
}

func (m *TransactionLifecycle) GetCancelationBlockState() *BlockState {
	if m != nil {
		return m.CancelationBlockState
	}
	return nil
}

type SignedTransaction struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Signatures           []string     `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	ContextFreeData      [][]byte     `protobuf:"bytes,3,rep,name=contextFreeData,proto3" json:"contextFreeData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignedTransaction) Reset()         { *m = SignedTransaction{} }
func (m *SignedTransaction) String() string { return proto.CompactTextString(m) }
func (*SignedTransaction) ProtoMessage()    {}
func (*SignedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{11}
}

func (m *SignedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedTransaction.Unmarshal(m, b)
}
func (m *SignedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedTransaction.Marshal(b, m, deterministic)
}
func (m *SignedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedTransaction.Merge(m, src)
}
func (m *SignedTransaction) XXX_Size() int {
	return xxx_messageInfo_SignedTransaction.Size(m)
}
func (m *SignedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SignedTransaction proto.InternalMessageInfo

func (m *SignedTransaction) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *SignedTransaction) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *SignedTransaction) GetContextFreeData() [][]byte {
	if m != nil {
		return m.ContextFreeData
	}
	return nil
}

type Transaction struct {
	Header               *TransactionHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ContextFreeActions   []*Action          `protobuf:"bytes,2,rep,name=contextFreeActions,proto3" json:"contextFreeActions,omitempty"`
	Actions              []*Action          `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	Extensions           []*Extension       `protobuf:"bytes,4,rep,name=extensions,proto3" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{12}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetHeader() *TransactionHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Transaction) GetContextFreeActions() []*Action {
	if m != nil {
		return m.ContextFreeActions
	}
	return nil
}

func (m *Transaction) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Transaction) GetExtensions() []*Extension {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type TransactionHeader struct {
	Expiration           *timestamp.Timestamp `protobuf:"bytes,1,opt,name=expiration,proto3" json:"expiration,omitempty"`
	RefBlockNum          uint64               `protobuf:"varint,2,opt,name=refBlockNum,proto3" json:"refBlockNum,omitempty"`
	RefBlockPrefix       uint64               `protobuf:"varint,3,opt,name=refBlockPrefix,proto3" json:"refBlockPrefix,omitempty"`
	MaxNetUsageWords     uint32               `protobuf:"varint,4,opt,name=maxNetUsageWords,proto3" json:"maxNetUsageWords,omitempty"`
	MaxCPUUsageMS        uint32               `protobuf:"varint,5,opt,name=maxCPUUsageMS,proto3" json:"maxCPUUsageMS,omitempty"`
	DelaySec             uint32               `protobuf:"varint,6,opt,name=delaySec,proto3" json:"delaySec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransactionHeader) Reset()         { *m = TransactionHeader{} }
func (m *TransactionHeader) String() string { return proto.CompactTextString(m) }
func (*TransactionHeader) ProtoMessage()    {}
func (*TransactionHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{13}
}

func (m *TransactionHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionHeader.Unmarshal(m, b)
}
func (m *TransactionHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionHeader.Marshal(b, m, deterministic)
}
func (m *TransactionHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionHeader.Merge(m, src)
}
func (m *TransactionHeader) XXX_Size() int {
	return xxx_messageInfo_TransactionHeader.Size(m)
}
func (m *TransactionHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionHeader.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionHeader proto.InternalMessageInfo

func (m *TransactionHeader) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *TransactionHeader) GetRefBlockNum() uint64 {
	if m != nil {
		return m.RefBlockNum
	}
	return 0
}

func (m *TransactionHeader) GetRefBlockPrefix() uint64 {
	if m != nil {
		return m.RefBlockPrefix
	}
	return 0
}

func (m *TransactionHeader) GetMaxNetUsageWords() uint32 {
	if m != nil {
		return m.MaxNetUsageWords
	}
	return 0
}

func (m *TransactionHeader) GetMaxCPUUsageMS() uint32 {
	if m != nil {
		return m.MaxCPUUsageMS
	}
	return 0
}

func (m *TransactionHeader) GetDelaySec() uint32 {
	if m != nil {
		return m.DelaySec
	}
	return 0
}

type TransactionTrace struct {
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BlockNum             uint64                    `protobuf:"varint,2,opt,name=blockNum,proto3" json:"blockNum,omitempty"`
	BlockTime            *timestamp.Timestamp      `protobuf:"bytes,3,opt,name=blockTime,proto3" json:"blockTime,omitempty"`
	ProducerBlockId      string                    `protobuf:"bytes,4,opt,name=producerBlockId,proto3" json:"producerBlockId,omitempty"`
	Receipt              *TransactionReceiptHeader `protobuf:"bytes,5,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Elapsed              int64                     `protobuf:"varint,6,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	NetUsage             uint64                    `protobuf:"varint,7,opt,name=netUsage,proto3" json:"netUsage,omitempty"`
	Scheduled            bool                      `protobuf:"varint,8,opt,name=scheduled,proto3" json:"scheduled,omitempty"`
	ActionTraces         []*ActionTrace            `protobuf:"bytes,9,rep,name=actionTraces,proto3" json:"actionTraces,omitempty"`
	FailedDTrxTrace      *TransactionTrace         `protobuf:"bytes,10,opt,name=failedDTrxTrace,proto3" json:"failedDTrxTrace,omitempty"`
	Except               []byte                    `protobuf:"bytes,15,opt,name=except,proto3" json:"except,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TransactionTrace) Reset()         { *m = TransactionTrace{} }
func (m *TransactionTrace) String() string { return proto.CompactTextString(m) }
func (*TransactionTrace) ProtoMessage()    {}
func (*TransactionTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{14}
}

func (m *TransactionTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionTrace.Unmarshal(m, b)
}
func (m *TransactionTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionTrace.Marshal(b, m, deterministic)
}
func (m *TransactionTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionTrace.Merge(m, src)
}
func (m *TransactionTrace) XXX_Size() int {
	return xxx_messageInfo_TransactionTrace.Size(m)
}
func (m *TransactionTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionTrace.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionTrace proto.InternalMessageInfo

func (m *TransactionTrace) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TransactionTrace) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *TransactionTrace) GetBlockTime() *timestamp.Timestamp {
	if m != nil {
		return m.BlockTime
	}
	return nil
}

func (m *TransactionTrace) GetProducerBlockId() string {
	if m != nil {
		return m.ProducerBlockId
	}
	return ""
}

func (m *TransactionTrace) GetReceipt() *TransactionReceiptHeader {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *TransactionTrace) GetElapsed() int64 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

func (m *TransactionTrace) GetNetUsage() uint64 {
	if m != nil {
		return m.NetUsage
	}
	return 0
}

func (m *TransactionTrace) GetScheduled() bool {
	if m != nil {
		return m.Scheduled
	}
	return false
}

func (m *TransactionTrace) GetActionTraces() []*ActionTrace {
	if m != nil {
		return m.ActionTraces
	}
	return nil
}

func (m *TransactionTrace) GetFailedDTrxTrace() *TransactionTrace {
	if m != nil {
		return m.FailedDTrxTrace
	}
	return nil
}

func (m *TransactionTrace) GetExcept() []byte {
	if m != nil {
		return m.Except
	}
	return nil
}

type TransactionReceiptHeader struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CpuUsageMicroSeconds uint32   `protobuf:"varint,2,opt,name=cpuUsageMicroSeconds,proto3" json:"cpuUsageMicroSeconds,omitempty"`
	NetUsageWords        uint32   `protobuf:"varint,3,opt,name=netUsageWords,proto3" json:"netUsageWords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionReceiptHeader) Reset()         { *m = TransactionReceiptHeader{} }
func (m *TransactionReceiptHeader) String() string { return proto.CompactTextString(m) }
func (*TransactionReceiptHeader) ProtoMessage()    {}
func (*TransactionReceiptHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{15}
}

func (m *TransactionReceiptHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReceiptHeader.Unmarshal(m, b)
}
func (m *TransactionReceiptHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReceiptHeader.Marshal(b, m, deterministic)
}
func (m *TransactionReceiptHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReceiptHeader.Merge(m, src)
}
func (m *TransactionReceiptHeader) XXX_Size() int {
	return xxx_messageInfo_TransactionReceiptHeader.Size(m)
}
func (m *TransactionReceiptHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReceiptHeader.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReceiptHeader proto.InternalMessageInfo

func (m *TransactionReceiptHeader) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TransactionReceiptHeader) GetCpuUsageMicroSeconds() uint32 {
	if m != nil {
		return m.CpuUsageMicroSeconds
	}
	return 0
}

func (m *TransactionReceiptHeader) GetNetUsageWords() uint32 {
	if m != nil {
		return m.NetUsageWords
	}
	return 0
}

type Action struct {
	Account              string             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Authorization        []*PermissionLevel `protobuf:"bytes,3,rep,name=authorization,proto3" json:"authorization,omitempty"`
	Data                 string             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	HexData              string             `protobuf:"bytes,5,opt,name=hexData,proto3" json:"hexData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{16}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Action) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Action) GetAuthorization() []*PermissionLevel {
	if m != nil {
		return m.Authorization
	}
	return nil
}

func (m *Action) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Action) GetHexData() string {
	if m != nil {
		return m.HexData
	}
	return ""
}

type ActionTrace struct {
	Receipt                               *ActionReceipt     `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Action                                *Action            `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ContextFree                           bool               `protobuf:"varint,3,opt,name=contextFree,proto3" json:"contextFree,omitempty"`
	Elapsed                               uint64             `protobuf:"varint,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Console                               string             `protobuf:"bytes,5,opt,name=console,proto3" json:"console,omitempty"`
	TransactionID                         string             `protobuf:"bytes,6,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	BlockNum                              uint64             `protobuf:"varint,7,opt,name=blockNum,proto3" json:"blockNum,omitempty"`
	ProducerBlockID                       string             `protobuf:"bytes,8,opt,name=ProducerBlockID,proto3" json:"ProducerBlockID,omitempty"`
	AccountRAMDeltas                      []*AccountRAMDelta `protobuf:"bytes,9,rep,name=accountRAMDeltas,proto3" json:"accountRAMDeltas,omitempty"`
	Except                                []byte             `protobuf:"bytes,15,opt,name=except,proto3" json:"except,omitempty"`
	CreatorActionOrdinal                  int64              `protobuf:"varint,16,opt,name=creatorActionOrdinal,proto3" json:"creatorActionOrdinal,omitempty"`
	ClosestUnnotifiedAcestorActionOrdinal int64              `protobuf:"varint,17,opt,name=closestUnnotifiedAcestorActionOrdinal,proto3" json:"closestUnnotifiedAcestorActionOrdinal,omitempty"`
	InlineTraces                          []*ActionTrace     `protobuf:"bytes,20,rep,name=inlineTraces,proto3" json:"inlineTraces,omitempty"`
	XXX_NoUnkeyedLiteral                  struct{}           `json:"-"`
	XXX_unrecognized                      []byte             `json:"-"`
	XXX_sizecache                         int32              `json:"-"`
}

func (m *ActionTrace) Reset()         { *m = ActionTrace{} }
func (m *ActionTrace) String() string { return proto.CompactTextString(m) }
func (*ActionTrace) ProtoMessage()    {}
func (*ActionTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{17}
}

func (m *ActionTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionTrace.Unmarshal(m, b)
}
func (m *ActionTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionTrace.Marshal(b, m, deterministic)
}
func (m *ActionTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionTrace.Merge(m, src)
}
func (m *ActionTrace) XXX_Size() int {
	return xxx_messageInfo_ActionTrace.Size(m)
}
func (m *ActionTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionTrace.DiscardUnknown(m)
}

var xxx_messageInfo_ActionTrace proto.InternalMessageInfo

func (m *ActionTrace) GetReceipt() *ActionReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *ActionTrace) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ActionTrace) GetContextFree() bool {
	if m != nil {
		return m.ContextFree
	}
	return false
}

func (m *ActionTrace) GetElapsed() uint64 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

func (m *ActionTrace) GetConsole() string {
	if m != nil {
		return m.Console
	}
	return ""
}

func (m *ActionTrace) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *ActionTrace) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *ActionTrace) GetProducerBlockID() string {
	if m != nil {
		return m.ProducerBlockID
	}
	return ""
}

func (m *ActionTrace) GetAccountRAMDeltas() []*AccountRAMDelta {
	if m != nil {
		return m.AccountRAMDeltas
	}
	return nil
}

func (m *ActionTrace) GetExcept() []byte {
	if m != nil {
		return m.Except
	}
	return nil
}

func (m *ActionTrace) GetCreatorActionOrdinal() int64 {
	if m != nil {
		return m.CreatorActionOrdinal
	}
	return 0
}

func (m *ActionTrace) GetClosestUnnotifiedAcestorActionOrdinal() int64 {
	if m != nil {
		return m.ClosestUnnotifiedAcestorActionOrdinal
	}
	return 0
}

func (m *ActionTrace) GetInlineTraces() []*ActionTrace {
	if m != nil {
		return m.InlineTraces
	}
	return nil
}

type ActionReceipt struct {
	Receiver             string   `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Digest               string   `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	GlobalSequence       uint64   `protobuf:"varint,3,opt,name=globalSequence,proto3" json:"globalSequence,omitempty"`
	AuthSequence         [][]byte `protobuf:"bytes,4,rep,name=authSequence,proto3" json:"authSequence,omitempty"`
	RecvSequence         uint64   `protobuf:"varint,5,opt,name=recvSequence,proto3" json:"recvSequence,omitempty"`
	CodeSequence         uint64   `protobuf:"varint,6,opt,name=codeSequence,proto3" json:"codeSequence,omitempty"`
	AbiSequence          uint64   `protobuf:"varint,7,opt,name=abiSequence,proto3" json:"abiSequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionReceipt) Reset()         { *m = ActionReceipt{} }
func (m *ActionReceipt) String() string { return proto.CompactTextString(m) }
func (*ActionReceipt) ProtoMessage()    {}
func (*ActionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{18}
}

func (m *ActionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionReceipt.Unmarshal(m, b)
}
func (m *ActionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionReceipt.Marshal(b, m, deterministic)
}
func (m *ActionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionReceipt.Merge(m, src)
}
func (m *ActionReceipt) XXX_Size() int {
	return xxx_messageInfo_ActionReceipt.Size(m)
}
func (m *ActionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_ActionReceipt proto.InternalMessageInfo

func (m *ActionReceipt) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *ActionReceipt) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *ActionReceipt) GetGlobalSequence() uint64 {
	if m != nil {
		return m.GlobalSequence
	}
	return 0
}

func (m *ActionReceipt) GetAuthSequence() [][]byte {
	if m != nil {
		return m.AuthSequence
	}
	return nil
}

func (m *ActionReceipt) GetRecvSequence() uint64 {
	if m != nil {
		return m.RecvSequence
	}
	return 0
}

func (m *ActionReceipt) GetCodeSequence() uint64 {
	if m != nil {
		return m.CodeSequence
	}
	return 0
}

func (m *ActionReceipt) GetAbiSequence() uint64 {
	if m != nil {
		return m.AbiSequence
	}
	return 0
}

type AccountRAMDelta struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Delta                int64    `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRAMDelta) Reset()         { *m = AccountRAMDelta{} }
func (m *AccountRAMDelta) String() string { return proto.CompactTextString(m) }
func (*AccountRAMDelta) ProtoMessage()    {}
func (*AccountRAMDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{19}
}

func (m *AccountRAMDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRAMDelta.Unmarshal(m, b)
}
func (m *AccountRAMDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRAMDelta.Marshal(b, m, deterministic)
}
func (m *AccountRAMDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRAMDelta.Merge(m, src)
}
func (m *AccountRAMDelta) XXX_Size() int {
	return xxx_messageInfo_AccountRAMDelta.Size(m)
}
func (m *AccountRAMDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRAMDelta.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRAMDelta proto.InternalMessageInfo

func (m *AccountRAMDelta) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AccountRAMDelta) GetDelta() int64 {
	if m != nil {
		return m.Delta
	}
	return 0
}

type Extension struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Extension) Reset()         { *m = Extension{} }
func (m *Extension) String() string { return proto.CompactTextString(m) }
func (*Extension) ProtoMessage()    {}
func (*Extension) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{20}
}

func (m *Extension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extension.Unmarshal(m, b)
}
func (m *Extension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extension.Marshal(b, m, deterministic)
}
func (m *Extension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extension.Merge(m, src)
}
func (m *Extension) XXX_Size() int {
	return xxx_messageInfo_Extension.Size(m)
}
func (m *Extension) XXX_DiscardUnknown() {
	xxx_messageInfo_Extension.DiscardUnknown(m)
}

var xxx_messageInfo_Extension proto.InternalMessageInfo

func (m *Extension) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Extension) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PermissionLevel struct {
	Actor                string   `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Permission           string   `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionLevel) Reset()         { *m = PermissionLevel{} }
func (m *PermissionLevel) String() string { return proto.CompactTextString(m) }
func (*PermissionLevel) ProtoMessage()    {}
func (*PermissionLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{21}
}

func (m *PermissionLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionLevel.Unmarshal(m, b)
}
func (m *PermissionLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionLevel.Marshal(b, m, deterministic)
}
func (m *PermissionLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionLevel.Merge(m, src)
}
func (m *PermissionLevel) XXX_Size() int {
	return xxx_messageInfo_PermissionLevel.Size(m)
}
func (m *PermissionLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionLevel.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionLevel proto.InternalMessageInfo

func (m *PermissionLevel) GetActor() string {
	if m != nil {
		return m.Actor
	}
	return ""
}

func (m *PermissionLevel) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type DTrxOp struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	ActionIndex          uint32   `protobuf:"varint,2,opt,name=actionIndex,proto3" json:"actionIndex,omitempty"`
	Sender               string   `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderID             string   `protobuf:"bytes,4,opt,name=senderID,proto3" json:"senderID,omitempty"`
	Payer                string   `protobuf:"bytes,5,opt,name=payer,proto3" json:"payer,omitempty"`
	PublishedAt          string   `protobuf:"bytes,6,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	DelayUntil           string   `protobuf:"bytes,7,opt,name=delayUntil,proto3" json:"delayUntil,omitempty"`
	ExpirationAt         string   `protobuf:"bytes,8,opt,name=expirationAt,proto3" json:"expirationAt,omitempty"`
	TransactionID        string   `protobuf:"bytes,9,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Transaction          []byte   `protobuf:"bytes,10,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DTrxOp) Reset()         { *m = DTrxOp{} }
func (m *DTrxOp) String() string { return proto.CompactTextString(m) }
func (*DTrxOp) ProtoMessage()    {}
func (*DTrxOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{22}
}

func (m *DTrxOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DTrxOp.Unmarshal(m, b)
}
func (m *DTrxOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DTrxOp.Marshal(b, m, deterministic)
}
func (m *DTrxOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DTrxOp.Merge(m, src)
}
func (m *DTrxOp) XXX_Size() int {
	return xxx_messageInfo_DTrxOp.Size(m)
}
func (m *DTrxOp) XXX_DiscardUnknown() {
	xxx_messageInfo_DTrxOp.DiscardUnknown(m)
}

var xxx_messageInfo_DTrxOp proto.InternalMessageInfo

func (m *DTrxOp) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *DTrxOp) GetActionIndex() uint32 {
	if m != nil {
		return m.ActionIndex
	}
	return 0
}

func (m *DTrxOp) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *DTrxOp) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *DTrxOp) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *DTrxOp) GetPublishedAt() string {
	if m != nil {
		return m.PublishedAt
	}
	return ""
}

func (m *DTrxOp) GetDelayUntil() string {
	if m != nil {
		return m.DelayUntil
	}
	return ""
}

func (m *DTrxOp) GetExpirationAt() string {
	if m != nil {
		return m.ExpirationAt
	}
	return ""
}

func (m *DTrxOp) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *DTrxOp) GetTransaction() []byte {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type DBOp struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	ActionIndex          uint32   `protobuf:"varint,2,opt,name=actionIndex,proto3" json:"actionIndex,omitempty"`
	OldPayer             string   `protobuf:"bytes,3,opt,name=oldPayer,proto3" json:"oldPayer,omitempty"`
	NewPayer             string   `protobuf:"bytes,4,opt,name=newPayer,proto3" json:"newPayer,omitempty"`
	TablePath            string   `protobuf:"bytes,5,opt,name=tablePath,proto3" json:"tablePath,omitempty"`
	OldData              string   `protobuf:"bytes,6,opt,name=oldData,proto3" json:"oldData,omitempty"`
	NewData              string   `protobuf:"bytes,7,opt,name=newData,proto3" json:"newData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBOp) Reset()         { *m = DBOp{} }
func (m *DBOp) String() string { return proto.CompactTextString(m) }
func (*DBOp) ProtoMessage()    {}
func (*DBOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{23}
}

func (m *DBOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBOp.Unmarshal(m, b)
}
func (m *DBOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBOp.Marshal(b, m, deterministic)
}
func (m *DBOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBOp.Merge(m, src)
}
func (m *DBOp) XXX_Size() int {
	return xxx_messageInfo_DBOp.Size(m)
}
func (m *DBOp) XXX_DiscardUnknown() {
	xxx_messageInfo_DBOp.DiscardUnknown(m)
}

var xxx_messageInfo_DBOp proto.InternalMessageInfo

func (m *DBOp) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *DBOp) GetActionIndex() uint32 {
	if m != nil {
		return m.ActionIndex
	}
	return 0
}

func (m *DBOp) GetOldPayer() string {
	if m != nil {
		return m.OldPayer
	}
	return ""
}

func (m *DBOp) GetNewPayer() string {
	if m != nil {
		return m.NewPayer
	}
	return ""
}

func (m *DBOp) GetTablePath() string {
	if m != nil {
		return m.TablePath
	}
	return ""
}

func (m *DBOp) GetOldData() string {
	if m != nil {
		return m.OldData
	}
	return ""
}

func (m *DBOp) GetNewData() string {
	if m != nil {
		return m.NewData
	}
	return ""
}

type RAMOp struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	ActionIndex          uint32   `protobuf:"varint,2,opt,name=actionIndex,proto3" json:"actionIndex,omitempty"`
	Payer                string   `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	Delta                int64    `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"`
	Usage                uint64   `protobuf:"varint,5,opt,name=usage,proto3" json:"usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RAMOp) Reset()         { *m = RAMOp{} }
func (m *RAMOp) String() string { return proto.CompactTextString(m) }
func (*RAMOp) ProtoMessage()    {}
func (*RAMOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{24}
}

func (m *RAMOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RAMOp.Unmarshal(m, b)
}
func (m *RAMOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RAMOp.Marshal(b, m, deterministic)
}
func (m *RAMOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RAMOp.Merge(m, src)
}
func (m *RAMOp) XXX_Size() int {
	return xxx_messageInfo_RAMOp.Size(m)
}
func (m *RAMOp) XXX_DiscardUnknown() {
	xxx_messageInfo_RAMOp.DiscardUnknown(m)
}

var xxx_messageInfo_RAMOp proto.InternalMessageInfo

func (m *RAMOp) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *RAMOp) GetActionIndex() uint32 {
	if m != nil {
		return m.ActionIndex
	}
	return 0
}

func (m *RAMOp) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *RAMOp) GetDelta() int64 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func (m *RAMOp) GetUsage() uint64 {
	if m != nil {
		return m.Usage
	}
	return 0
}

type TableOp struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	ActionIndex          uint32   `protobuf:"varint,2,opt,name=actionIndex,proto3" json:"actionIndex,omitempty"`
	Payer                string   `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableOp) Reset()         { *m = TableOp{} }
func (m *TableOp) String() string { return proto.CompactTextString(m) }
func (*TableOp) ProtoMessage()    {}
func (*TableOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{25}
}

func (m *TableOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableOp.Unmarshal(m, b)
}
func (m *TableOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableOp.Marshal(b, m, deterministic)
}
func (m *TableOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableOp.Merge(m, src)
}
func (m *TableOp) XXX_Size() int {
	return xxx_messageInfo_TableOp.Size(m)
}
func (m *TableOp) XXX_DiscardUnknown() {
	xxx_messageInfo_TableOp.DiscardUnknown(m)
}

var xxx_messageInfo_TableOp proto.InternalMessageInfo

func (m *TableOp) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *TableOp) GetActionIndex() uint32 {
	if m != nil {
		return m.ActionIndex
	}
	return 0
}

func (m *TableOp) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *TableOp) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ExtDTrxOp struct {
	SourceTransactionID  string               `protobuf:"bytes,1,opt,name=sourceTransactionID,proto3" json:"sourceTransactionID,omitempty"`
	BlockNum             uint64               `protobuf:"varint,2,opt,name=blockNum,proto3" json:"blockNum,omitempty"`
	BlockId              string               `protobuf:"bytes,3,opt,name=blockId,proto3" json:"blockId,omitempty"`
	BlockTime            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=blockTime,proto3" json:"blockTime,omitempty"`
	Operation            string               `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	ActionIndex          uint32               `protobuf:"varint,6,opt,name=actionIndex,proto3" json:"actionIndex,omitempty"`
	Sender               string               `protobuf:"bytes,7,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderID             string               `protobuf:"bytes,8,opt,name=senderID,proto3" json:"senderID,omitempty"`
	Payer                string               `protobuf:"bytes,9,opt,name=payer,proto3" json:"payer,omitempty"`
	PublishedAt          string               `protobuf:"bytes,10,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	DelayUntil           string               `protobuf:"bytes,11,opt,name=delayUntil,proto3" json:"delayUntil,omitempty"`
	ExpirationAt         string               `protobuf:"bytes,12,opt,name=expirationAt,proto3" json:"expirationAt,omitempty"`
	TransactionID        string               `protobuf:"bytes,13,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExtDTrxOp) Reset()         { *m = ExtDTrxOp{} }
func (m *ExtDTrxOp) String() string { return proto.CompactTextString(m) }
func (*ExtDTrxOp) ProtoMessage()    {}
func (*ExtDTrxOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{26}
}

func (m *ExtDTrxOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtDTrxOp.Unmarshal(m, b)
}
func (m *ExtDTrxOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtDTrxOp.Marshal(b, m, deterministic)
}
func (m *ExtDTrxOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtDTrxOp.Merge(m, src)
}
func (m *ExtDTrxOp) XXX_Size() int {
	return xxx_messageInfo_ExtDTrxOp.Size(m)
}
func (m *ExtDTrxOp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtDTrxOp.DiscardUnknown(m)
}

var xxx_messageInfo_ExtDTrxOp proto.InternalMessageInfo

func (m *ExtDTrxOp) GetSourceTransactionID() string {
	if m != nil {
		return m.SourceTransactionID
	}
	return ""
}

func (m *ExtDTrxOp) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *ExtDTrxOp) GetBlockId() string {
	if m != nil {
		return m.BlockId
	}
	return ""
}

func (m *ExtDTrxOp) GetBlockTime() *timestamp.Timestamp {
	if m != nil {
		return m.BlockTime
	}
	return nil
}

func (m *ExtDTrxOp) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *ExtDTrxOp) GetActionIndex() uint32 {
	if m != nil {
		return m.ActionIndex
	}
	return 0
}

func (m *ExtDTrxOp) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ExtDTrxOp) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *ExtDTrxOp) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *ExtDTrxOp) GetPublishedAt() string {
	if m != nil {
		return m.PublishedAt
	}
	return ""
}

func (m *ExtDTrxOp) GetDelayUntil() string {
	if m != nil {
		return m.DelayUntil
	}
	return ""
}

func (m *ExtDTrxOp) GetExpirationAt() string {
	if m != nil {
		return m.ExpirationAt
	}
	return ""
}

func (m *ExtDTrxOp) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

type FeatureOp struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ActionIndex          int32    `protobuf:"varint,2,opt,name=actionIndex,proto3" json:"actionIndex,omitempty"`
	FeatureDigest        string   `protobuf:"bytes,3,opt,name=featureDigest,proto3" json:"featureDigest,omitempty"`
	Feature              []byte   `protobuf:"bytes,4,opt,name=Feature,proto3" json:"Feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureOp) Reset()         { *m = FeatureOp{} }
func (m *FeatureOp) String() string { return proto.CompactTextString(m) }
func (*FeatureOp) ProtoMessage()    {}
func (*FeatureOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{27}
}

func (m *FeatureOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureOp.Unmarshal(m, b)
}
func (m *FeatureOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureOp.Marshal(b, m, deterministic)
}
func (m *FeatureOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureOp.Merge(m, src)
}
func (m *FeatureOp) XXX_Size() int {
	return xxx_messageInfo_FeatureOp.Size(m)
}
func (m *FeatureOp) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureOp.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureOp proto.InternalMessageInfo

func (m *FeatureOp) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *FeatureOp) GetActionIndex() int32 {
	if m != nil {
		return m.ActionIndex
	}
	return 0
}

func (m *FeatureOp) GetFeatureDigest() string {
	if m != nil {
		return m.FeatureDigest
	}
	return ""
}

func (m *FeatureOp) GetFeature() []byte {
	if m != nil {
		return m.Feature
	}
	return nil
}

type CreationFlatNode struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentIndex          uint32   `protobuf:"varint,2,opt,name=parentIndex,proto3" json:"parentIndex,omitempty"`
	ExecutionActionIndex uint32   `protobuf:"varint,3,opt,name=executionActionIndex,proto3" json:"executionActionIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreationFlatNode) Reset()         { *m = CreationFlatNode{} }
func (m *CreationFlatNode) String() string { return proto.CompactTextString(m) }
func (*CreationFlatNode) ProtoMessage()    {}
func (*CreationFlatNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_b451c4b9b8745b11, []int{28}
}

func (m *CreationFlatNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreationFlatNode.Unmarshal(m, b)
}
func (m *CreationFlatNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreationFlatNode.Marshal(b, m, deterministic)
}
func (m *CreationFlatNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreationFlatNode.Merge(m, src)
}
func (m *CreationFlatNode) XXX_Size() int {
	return xxx_messageInfo_CreationFlatNode.Size(m)
}
func (m *CreationFlatNode) XXX_DiscardUnknown() {
	xxx_messageInfo_CreationFlatNode.DiscardUnknown(m)
}

var xxx_messageInfo_CreationFlatNode proto.InternalMessageInfo

func (m *CreationFlatNode) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreationFlatNode) GetParentIndex() uint32 {
	if m != nil {
		return m.ParentIndex
	}
	return 0
}

func (m *CreationFlatNode) GetExecutionActionIndex() uint32 {
	if m != nil {
		return m.ExecutionActionIndex
	}
	return 0
}

func init() {
	proto.RegisterEnum("dfuse.codecs.deos.BlockReversibility", BlockReversibility_name, BlockReversibility_value)
	proto.RegisterEnum("dfuse.codecs.deos.TransactionStatus", TransactionStatus_name, TransactionStatus_value)
	proto.RegisterType((*BlockLifecycle)(nil), "dfuse.codecs.deos.BlockLifecycle")
	proto.RegisterType((*SignedBlock)(nil), "dfuse.codecs.deos.SignedBlock")
	proto.RegisterType((*TransactionReceipt)(nil), "dfuse.codecs.deos.TransactionReceipt")
	proto.RegisterType((*TransactionWithID)(nil), "dfuse.codecs.deos.TransactionWithID")
	proto.RegisterType((*PackedTransaction)(nil), "dfuse.codecs.deos.PackedTransaction")
	proto.RegisterType((*BlockHeader)(nil), "dfuse.codecs.deos.BlockHeader")
	proto.RegisterType((*BlockHeaderExtension)(nil), "dfuse.codecs.deos.BlockHeaderExtension")
	proto.RegisterType((*ProducerSchedule)(nil), "dfuse.codecs.deos.ProducerSchedule")
	proto.RegisterType((*ProducerKey)(nil), "dfuse.codecs.deos.ProducerKey")
	proto.RegisterType((*BlockState)(nil), "dfuse.codecs.deos.BlockState")
	proto.RegisterType((*TransactionLifecycle)(nil), "dfuse.codecs.deos.TransactionLifecycle")
	proto.RegisterType((*SignedTransaction)(nil), "dfuse.codecs.deos.SignedTransaction")
	proto.RegisterType((*Transaction)(nil), "dfuse.codecs.deos.Transaction")
	proto.RegisterType((*TransactionHeader)(nil), "dfuse.codecs.deos.TransactionHeader")
	proto.RegisterType((*TransactionTrace)(nil), "dfuse.codecs.deos.TransactionTrace")
	proto.RegisterType((*TransactionReceiptHeader)(nil), "dfuse.codecs.deos.TransactionReceiptHeader")
	proto.RegisterType((*Action)(nil), "dfuse.codecs.deos.Action")
	proto.RegisterType((*ActionTrace)(nil), "dfuse.codecs.deos.ActionTrace")
	proto.RegisterType((*ActionReceipt)(nil), "dfuse.codecs.deos.ActionReceipt")
	proto.RegisterType((*AccountRAMDelta)(nil), "dfuse.codecs.deos.AccountRAMDelta")
	proto.RegisterType((*Extension)(nil), "dfuse.codecs.deos.Extension")
	proto.RegisterType((*PermissionLevel)(nil), "dfuse.codecs.deos.PermissionLevel")
	proto.RegisterType((*DTrxOp)(nil), "dfuse.codecs.deos.DTrxOp")
	proto.RegisterType((*DBOp)(nil), "dfuse.codecs.deos.DBOp")
	proto.RegisterType((*RAMOp)(nil), "dfuse.codecs.deos.RAMOp")
	proto.RegisterType((*TableOp)(nil), "dfuse.codecs.deos.TableOp")
	proto.RegisterType((*ExtDTrxOp)(nil), "dfuse.codecs.deos.ExtDTrxOp")
	proto.RegisterType((*FeatureOp)(nil), "dfuse.codecs.deos.FeatureOp")
	proto.RegisterType((*CreationFlatNode)(nil), "dfuse.codecs.deos.CreationFlatNode")
}

func init() { proto.RegisterFile("dfuse/codecs/deos/deos.proto", fileDescriptor_b451c4b9b8745b11) }

var fileDescriptor_b451c4b9b8745b11 = []byte{
	// 2356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xcf, 0x73, 0xe3, 0x48,
	0xf5, 0xff, 0xfa, 0x47, 0x9c, 0xf8, 0x39, 0x4e, 0x9c, 0x9e, 0xcc, 0xac, 0x36, 0xdf, 0x99, 0x4c,
	0xd0, 0xce, 0x42, 0x6a, 0x80, 0xcc, 0x32, 0xb3, 0x45, 0x51, 0x53, 0x53, 0x14, 0x4e, 0xec, 0xec,
	0x98, 0x24, 0x4e, 0xaa, 0xed, 0xec, 0xec, 0x70, 0xa1, 0x64, 0xa9, 0x9d, 0x88, 0x91, 0x25, 0x21,
	0xc9, 0x19, 0x87, 0x1b, 0x27, 0x6a, 0xab, 0xf6, 0xc0, 0x9d, 0x03, 0xff, 0x01, 0x17, 0x4e, 0x70,
	0xa2, 0x8a, 0x7f, 0x80, 0x2b, 0xfc, 0x05, 0xfc, 0x01, 0x5c, 0xb8, 0x51, 0xfd, 0xba, 0x25, 0xb7,
	0x2c, 0xd9, 0xf1, 0xd6, 0x16, 0x5c, 0x5c, 0x7e, 0xaf, 0x3f, 0xaf, 0x7f, 0xbc, 0x7e, 0x3f, 0x3e,
	0x2d, 0x78, 0x68, 0x0d, 0xc7, 0x21, 0x7b, 0x66, 0x7a, 0x16, 0x33, 0xc3, 0x67, 0x16, 0xf3, 0xc4,
	0xcf, 0x81, 0x1f, 0x78, 0x91, 0x47, 0xb6, 0x70, 0xf4, 0x40, 0x8c, 0x1e, 0xf0, 0x81, 0x9d, 0xc7,
	0x57, 0x9e, 0x77, 0xe5, 0xb0, 0x67, 0x08, 0x18, 0x8c, 0x87, 0xcf, 0x22, 0x7b, 0xc4, 0xc2, 0xc8,
	0x18, 0xf9, 0xc2, 0x46, 0xff, 0x5d, 0x01, 0x36, 0x0e, 0x1d, 0xcf, 0x7c, 0x77, 0x6a, 0x0f, 0x99,
	0x79, 0x6b, 0x3a, 0x8c, 0xbc, 0x80, 0x95, 0x30, 0x32, 0x22, 0xa6, 0x15, 0xf6, 0x0a, 0xfb, 0xb5,
	0xe7, 0x8f, 0x0e, 0x32, 0xd3, 0x1e, 0xa0, 0x45, 0x8f, 0x83, 0xa8, 0xc0, 0x92, 0x4f, 0x61, 0x65,
	0xc0, 0x95, 0x5a, 0x11, 0x8d, 0x76, 0x73, 0x8c, 0x7a, 0xf6, 0x95, 0xcb, 0x2c, 0x34, 0xa5, 0x02,
	0x4c, 0x76, 0x01, 0x2c, 0xdf, 0x0b, 0x4f, 0x3b, 0x87, 0xdd, 0xf1, 0x48, 0x2b, 0xed, 0x15, 0xf6,
	0xeb, 0x54, 0xd1, 0xe8, 0xbf, 0x2d, 0x42, 0x4d, 0x31, 0x23, 0x3f, 0x81, 0x1a, 0x1a, 0xbe, 0x66,
	0x86, 0xc5, 0x02, 0xb9, 0xc1, 0xdd, 0x79, 0x1b, 0x14, 0x28, 0xaa, 0x9a, 0x90, 0xef, 0xc1, 0x96,
	0x1f, 0x78, 0xd6, 0xd8, 0x64, 0x01, 0x9f, 0xd8, 0x88, 0xc6, 0x01, 0xc3, 0x3d, 0x57, 0x69, 0x76,
	0x80, 0x74, 0x60, 0x3d, 0x0a, 0x0c, 0x37, 0x34, 0xcc, 0xc8, 0xf6, 0xdc, 0x50, 0x2b, 0xed, 0x95,
	0xf6, 0x6b, 0xcf, 0x3f, 0xce, 0x59, 0xb0, 0x3f, 0x85, 0x51, 0x66, 0x32, 0xdb, 0x8f, 0x68, 0xca,
	0x94, 0x1c, 0xc3, 0x26, 0xee, 0xa3, 0x3d, 0x89, 0x98, 0x1b, 0xe2, 0x6c, 0x65, 0x9c, 0xed, 0x61,
	0xce, 0x6c, 0x09, 0x88, 0xce, 0x1a, 0xe9, 0xff, 0x28, 0x00, 0xc9, 0x2e, 0x46, 0x1e, 0x40, 0x85,
	0x5f, 0xc4, 0x38, 0x44, 0xa7, 0x54, 0xa9, 0x94, 0xc8, 0x73, 0xd8, 0x36, 0xfd, 0xf1, 0x65, 0x68,
	0x5c, 0xb1, 0x33, 0xdb, 0x0c, 0xbc, 0x1e, 0x33, 0x3d, 0xd7, 0x0a, 0xf1, 0xc8, 0x75, 0x9a, 0x3b,
	0x46, 0x9e, 0x40, 0xdd, 0x65, 0x11, 0xea, 0xdf, 0x78, 0x81, 0x15, 0xca, 0x8b, 0x49, 0x2b, 0x09,
	0x85, 0x2d, 0xe5, 0x80, 0x6f, 0xec, 0xe8, 0xba, 0x63, 0x69, 0x65, 0xbc, 0x91, 0x27, 0x8b, 0x1d,
	0x84, 0xd8, 0x16, 0xcd, 0x9a, 0xeb, 0xef, 0x61, 0x2b, 0x83, 0x23, 0x1b, 0x50, 0xb4, 0x2d, 0x79,
	0xac, 0xa2, 0x6d, 0xf1, 0x85, 0x7d, 0xc3, 0x7c, 0xc7, 0x2c, 0x05, 0x2a, 0xc3, 0x2e, 0x6f, 0xe1,
	0x8b, 0x59, 0x2c, 0xcd, 0x9a, 0xeb, 0x7f, 0x2a, 0xc0, 0x56, 0x06, 0xc8, 0xc3, 0x33, 0x8c, 0x63,
	0x81, 0x3b, 0xb6, 0xb4, 0x5f, 0xa5, 0x8a, 0x86, 0xec, 0x41, 0xcd, 0xf4, 0x46, 0x7e, 0xc0, 0xc2,
	0x30, 0xde, 0x43, 0x9d, 0xaa, 0x2a, 0xf2, 0x29, 0xdc, 0x17, 0x8b, 0x1d, 0x79, 0x6e, 0xc4, 0x26,
	0xd1, 0x71, 0xc0, 0x58, 0xcb, 0x88, 0x0c, 0x74, 0xe9, 0x3a, 0xcd, 0x1f, 0xc4, 0x20, 0xcd, 0x9c,
	0xb0, 0x8c, 0x16, 0x39, 0x7b, 0xff, 0x63, 0x09, 0x6a, 0x4a, 0xbc, 0x93, 0x1f, 0x41, 0x35, 0xc9,
	0x72, 0x99, 0x22, 0x3b, 0x07, 0xa2, 0x0e, 0x1c, 0xc4, 0x75, 0xe0, 0xa0, 0x1f, 0x23, 0xe8, 0x14,
	0x4c, 0x76, 0x60, 0x2d, 0xce, 0x01, 0x99, 0x13, 0x89, 0x4c, 0x1e, 0x42, 0xd5, 0xf4, 0xdc, 0xa1,
	0x1d, 0x8c, 0x98, 0x25, 0x03, 0x62, 0xaa, 0x10, 0x96, 0xec, 0xc6, 0xf6, 0xc6, 0x21, 0x6e, 0x14,
	0x2d, 0x85, 0x4c, 0x9e, 0x42, 0x43, 0xb9, 0xe9, 0x33, 0xea, 0x79, 0x91, 0xb6, 0x82, 0x98, 0x8c,
	0x9e, 0x7b, 0x54, 0x85, 0x55, 0x10, 0xa6, 0xaa, 0xc8, 0x3e, 0x6c, 0x86, 0xe6, 0x35, 0xb3, 0xc6,
	0x0e, 0xfb, 0x9c, 0x05, 0xe8, 0xf7, 0x55, 0xdc, 0xcd, 0xac, 0x9a, 0x7c, 0x06, 0xeb, 0x2e, 0x7b,
	0x7f, 0x21, 0x0f, 0x10, 0x6a, 0x6b, 0xe8, 0x8a, 0x8f, 0xf2, 0x42, 0x24, 0x4e, 0x7c, 0x39, 0x03,
	0x4d, 0x19, 0x92, 0x1e, 0x34, 0xae, 0xd1, 0xb5, 0x4a, 0xee, 0x56, 0x31, 0x77, 0xbf, 0xb3, 0xb8,
	0xf4, 0x4c, 0xd3, 0x38, 0x33, 0x81, 0xfe, 0x63, 0xd8, 0xce, 0x43, 0x12, 0x02, 0xe5, 0xe8, 0xd6,
	0x17, 0xc5, 0xb7, 0x4e, 0xf1, 0x3f, 0xd7, 0x59, 0x3c, 0x68, 0x8a, 0x18, 0x02, 0xf8, 0x5f, 0xff,
	0x05, 0x34, 0x66, 0xb7, 0x4d, 0x34, 0x58, 0xbd, 0x91, 0x3e, 0x11, 0xe6, 0xb1, 0x48, 0x5e, 0x41,
	0xd5, 0x4f, 0x1c, 0x51, 0xc4, 0xbd, 0xef, 0x2e, 0x70, 0xc4, 0x09, 0xbb, 0xa5, 0x53, 0x03, 0xfd,
	0x2d, 0xd4, 0x94, 0x11, 0x71, 0x49, 0xa6, 0x37, 0x76, 0xa3, 0xae, 0x31, 0x62, 0x32, 0x33, 0x55,
	0x15, 0xbf, 0x24, 0xac, 0x5b, 0xbc, 0x92, 0xda, 0xee, 0xd5, 0x09, 0xbb, 0x95, 0xf1, 0x34, 0xab,
	0xd6, 0xc7, 0x00, 0xd3, 0x66, 0x42, 0x4e, 0xa0, 0x1e, 0x30, 0xdc, 0xf3, 0xc0, 0x76, 0xec, 0xe8,
	0x16, 0xe7, 0xde, 0xc8, 0x2d, 0xb8, 0xa2, 0x8f, 0xa8, 0x60, 0x9a, 0xb6, 0xe5, 0x31, 0x79, 0x6d,
	0xb8, 0x96, 0x37, 0x1c, 0xc6, 0xe5, 0x2e, 0x91, 0xf5, 0xbf, 0xaf, 0xc1, 0xb6, 0x92, 0x43, 0xd3,
	0xe6, 0x97, 0x53, 0x6c, 0x94, 0x20, 0xed, 0x89, 0x12, 0x5b, 0xc4, 0x5d, 0xdd, 0x51, 0xe5, 0x04,
	0x96, 0x66, 0xcd, 0xf9, 0x9c, 0x21, 0x36, 0x35, 0x35, 0xbd, 0x61, 0x6e, 0x01, 0xeb, 0xcd, 0x62,
	0x69, 0xd6, 0x9c, 0x9c, 0xc0, 0x06, 0x9b, 0x30, 0x73, 0xcc, 0x85, 0x7e, 0x60, 0x98, 0x4c, 0xab,
	0xcd, 0x0d, 0x77, 0xc5, 0x0e, 0xa1, 0x74, 0xc6, 0x94, 0x50, 0xd8, 0x4e, 0x34, 0x4a, 0x90, 0x6a,
	0xeb, 0x4b, 0xf5, 0xdb, 0x5c, 0x5b, 0xf2, 0x02, 0x56, 0xad, 0x28, 0x98, 0x9c, 0xfb, 0xa1, 0x56,
	0xc7, 0xf8, 0xfb, 0x30, 0x67, 0x9a, 0x56, 0x9f, 0x23, 0x68, 0x8c, 0xe4, 0x29, 0x6c, 0x06, 0xcc,
	0x10, 0x3b, 0x63, 0x4c, 0xdb, 0x40, 0xcb, 0xbc, 0x33, 0x1d, 0x49, 0xd8, 0xb1, 0x63, 0x44, 0x5d,
	0xcf, 0x62, 0x34, 0x65, 0x48, 0xbe, 0x0f, 0x2b, 0xd6, 0x80, 0xaf, 0xbd, 0x89, 0x33, 0x7c, 0x90,
	0xb7, 0xf6, 0xe1, 0xb9, 0x4f, 0x05, 0x8a, 0x7c, 0x02, 0x95, 0xc0, 0x18, 0x71, 0x7c, 0x03, 0xf1,
	0x5a, 0x0e, 0x9e, 0x36, 0xcf, 0xce, 0x7d, 0x2a, 0x71, 0xe4, 0x87, 0xb0, 0x16, 0x19, 0x03, 0x87,
	0x71, 0x9b, 0x2d, 0xb4, 0xd9, 0xc9, 0xf3, 0xbc, 0x80, 0xd0, 0x04, 0x4b, 0x5e, 0x01, 0x0c, 0x19,
	0xb6, 0x13, 0x6e, 0x49, 0xe6, 0x32, 0x82, 0xe3, 0x18, 0x44, 0x15, 0x3c, 0x6f, 0x50, 0xfe, 0x78,
	0xe0, 0xd8, 0xe6, 0x09, 0xbb, 0x0d, 0xb5, 0x7b, 0xa2, 0x41, 0x4d, 0x35, 0xe4, 0x25, 0x54, 0xd1,
	0x0d, 0xcc, 0x3a, 0xbc, 0xd5, 0xb6, 0xf1, 0xf6, 0xe6, 0xd0, 0x0d, 0xe9, 0xf9, 0x29, 0x9c, 0xef,
	0xcc, 0x34, 0x5c, 0x93, 0x39, 0x68, 0x7c, 0x7f, 0x09, 0x63, 0x05, 0x4f, 0xce, 0x80, 0xc4, 0x17,
	0x30, 0xcd, 0x6f, 0x6d, 0x77, 0x19, 0x46, 0x99, 0x63, 0x48, 0xce, 0xe1, 0x5e, 0x3a, 0xaa, 0xc4,
	0x7c, 0x8f, 0x97, 0x99, 0x2f, 0xcf, 0x92, 0xf4, 0xe0, 0xbe, 0xd8, 0xed, 0xec, 0x16, 0xf7, 0x96,
	0x99, 0x32, 0xdf, 0xf6, 0xa7, 0xe5, 0xb5, 0x07, 0x8d, 0x5d, 0xfd, 0xf7, 0x05, 0xd8, 0xca, 0xe4,
	0x2c, 0xa7, 0xae, 0x4a, 0x25, 0x58, 0x40, 0x5d, 0xd5, 0x44, 0x57, 0x4d, 0x66, 0xd8, 0x48, 0x31,
	0xc3, 0x46, 0xf6, 0x61, 0xd3, 0xcc, 0xb0, 0x8c, 0xd2, 0xfe, 0x3a, 0x9d, 0x55, 0xeb, 0x5f, 0x16,
	0xa1, 0xa6, 0xee, 0xed, 0x15, 0x54, 0xae, 0x55, 0x46, 0x7d, 0x47, 0x65, 0x93, 0x79, 0x2e, 0x6d,
	0x48, 0x07, 0x88, 0xb2, 0x40, 0x53, 0x52, 0xe5, 0xe2, 0xdc, 0x24, 0x17, 0x08, 0x9a, 0x63, 0xc4,
	0x8b, 0x44, 0x9a, 0x6a, 0x2f, 0xb0, 0x8f, 0x91, 0x3c, 0x50, 0xd9, 0xd7, 0x23, 0xd5, 0x0a, 0x5e,
	0xff, 0x4d, 0x31, 0xc5, 0x39, 0x65, 0xb5, 0x7a, 0xc9, 0xe7, 0xf4, 0xed, 0xc0, 0x50, 0x2e, 0x6b,
	0x11, 0x89, 0x52, 0xd0, 0xbc, 0x3d, 0x06, 0x6c, 0x88, 0x61, 0xc1, 0x5f, 0x35, 0xbc, 0x59, 0x94,
	0xa9, 0xaa, 0x22, 0xdf, 0x86, 0x8d, 0x58, 0xbc, 0x08, 0xd8, 0xd0, 0x9e, 0x20, 0xa1, 0x2a, 0xd3,
	0x19, 0x2d, 0x67, 0x4e, 0x23, 0x63, 0xd2, 0x4d, 0x71, 0xf1, 0x32, 0x76, 0xb2, 0x8c, 0x9e, 0x93,
	0xf6, 0x91, 0x31, 0x39, 0xba, 0xb8, 0x14, 0x7c, 0xbe, 0x87, 0x14, 0xab, 0x4e, 0xd3, 0x4a, 0xde,
	0x13, 0x2d, 0xe6, 0x18, 0xb7, 0x3d, 0x66, 0x22, 0xb9, 0xaa, 0xd3, 0x44, 0xd6, 0xff, 0x59, 0x82,
	0xc6, 0x6c, 0x6b, 0xc8, 0xf4, 0xc3, 0x1d, 0x58, 0x1b, 0xa4, 0x4f, 0x96, 0xc8, 0x9c, 0x78, 0xe2,
	0x7f, 0xee, 0x16, 0x3c, 0xd1, 0x1d, 0xc4, 0x33, 0x01, 0xf3, 0xd0, 0x8d, 0xd9, 0x06, 0x9e, 0x5f,
	0xbe, 0x24, 0xaa, 0x74, 0x56, 0x4d, 0xda, 0xb0, 0x1a, 0x88, 0x27, 0x0f, 0x1e, 0xb0, 0xf6, 0xfc,
	0xbb, 0x4b, 0x3d, 0xc6, 0x64, 0xc8, 0xc6, 0xb6, 0x9c, 0x29, 0x31, 0xc7, 0xf0, 0x43, 0x66, 0xa1,
	0x1b, 0x4a, 0x34, 0x16, 0xf9, 0x01, 0xe3, 0x77, 0x0e, 0x12, 0xcb, 0x32, 0x4d, 0x64, 0xce, 0x81,
	0x63, 0x92, 0x69, 0x21, 0x9d, 0x5c, 0xa3, 0x53, 0x05, 0x39, 0x84, 0x75, 0xc5, 0x73, 0x31, 0x45,
	0xdc, 0x9d, 0x1b, 0xc1, 0xa2, 0xf7, 0xa6, 0x6c, 0xc8, 0x19, 0x6c, 0x0e, 0x0d, 0xdb, 0x61, 0x16,
	0x2f, 0xa9, 0xa2, 0x8f, 0xc3, 0xf2, 0x7d, 0x7c, 0xd6, 0x96, 0xbf, 0x0a, 0xd9, 0xc4, 0x64, 0x7e,
	0xa4, 0x6d, 0x22, 0x75, 0x94, 0x92, 0xfe, 0x55, 0x01, 0xb4, 0x79, 0x4e, 0xfa, 0xdf, 0x3f, 0x25,
	0xf5, 0x3f, 0x14, 0xa0, 0x22, 0x7c, 0xc2, 0x2f, 0x46, 0x12, 0x49, 0xb9, 0x7a, 0x2c, 0x72, 0x12,
	0xec, 0x72, 0xba, 0x29, 0x88, 0x24, 0xfe, 0x27, 0xaf, 0xa1, 0x6e, 0x8c, 0xa3, 0x6b, 0x2f, 0xb0,
	0x7f, 0x25, 0x32, 0x55, 0x54, 0x0d, 0x3d, 0x8f, 0xda, 0xb2, 0x60, 0x64, 0xe3, 0xa3, 0xec, 0x94,
	0xdd, 0x30, 0x87, 0xa6, 0x0d, 0x13, 0x8a, 0x2d, 0xc2, 0x0e, 0xff, 0xf3, 0xbd, 0x5c, 0xb3, 0x09,
	0x16, 0x52, 0xf1, 0x5e, 0x89, 0x45, 0xfd, 0x5f, 0x65, 0xa8, 0x29, 0x97, 0x48, 0x5e, 0x4e, 0xa3,
	0x52, 0xd4, 0x8a, 0xbd, 0xf9, 0x75, 0x4b, 0x7e, 0x1d, 0x48, 0x42, 0xf1, 0x07, 0x50, 0x49, 0xbd,
	0x61, 0x17, 0x94, 0x3c, 0x09, 0x14, 0xef, 0xce, 0xa4, 0x78, 0xa2, 0x4f, 0xd7, 0xa8, 0xaa, 0x52,
	0xe3, 0xbb, 0x8c, 0x41, 0x9c, 0xc4, 0xb7, 0x06, 0xab, 0xa6, 0xe7, 0x86, 0x9e, 0xc3, 0xe2, 0x43,
	0x49, 0x91, 0xdf, 0x95, 0xd2, 0x6e, 0x3a, 0x2d, 0xf9, 0xfa, 0x4a, 0x2b, 0x53, 0x05, 0x60, 0x75,
	0xa6, 0x00, 0xec, 0xc3, 0xe6, 0x45, 0x2a, 0x5f, 0x5b, 0x98, 0x25, 0x55, 0x3a, 0xab, 0x26, 0x5d,
	0x68, 0xc8, 0x7b, 0xa5, 0xcd, 0xb3, 0x16, 0x73, 0x22, 0x23, 0xce, 0x17, 0x3d, 0xf7, 0xf8, 0x29,
	0x28, 0xcd, 0xd8, 0xce, 0x0b, 0x74, 0x8c, 0x59, 0xce, 0x26, 0xbc, 0x40, 0xb8, 0xf0, 0x3c, 0xb0,
	0x6c, 0xd7, 0x70, 0xb4, 0x06, 0x26, 0x7d, 0xee, 0x18, 0xe9, 0xc3, 0xc7, 0xa6, 0xe3, 0x85, 0x2c,
	0x8c, 0x2e, 0x5d, 0xd7, 0x8b, 0xec, 0xa1, 0xcd, 0xac, 0xa6, 0xc9, 0xc2, 0xcc, 0x24, 0x5b, 0x38,
	0xc9, 0x72, 0x60, 0x5e, 0x1d, 0x6c, 0xd7, 0xb1, 0x5d, 0x26, 0xab, 0xc3, 0xf6, 0x72, 0xd5, 0x41,
	0xb5, 0xd1, 0xff, 0x5d, 0x80, 0x7a, 0x2a, 0x8a, 0xf8, 0x6d, 0x60, 0x1c, 0xdd, 0xc8, 0xde, 0x5d,
	0xa5, 0x89, 0xcc, 0x7d, 0x62, 0xd9, 0x57, 0x2c, 0x8c, 0x64, 0xca, 0x48, 0x89, 0x77, 0x9f, 0x2b,
	0xc7, 0x1b, 0x18, 0x4e, 0x8f, 0xfd, 0x72, 0xcc, 0x5c, 0x93, 0xc5, 0xdd, 0x27, 0xad, 0x25, 0x3a,
	0xac, 0xf3, 0x1c, 0x49, 0x50, 0x65, 0x24, 0x13, 0x29, 0x1d, 0xc7, 0x04, 0xcc, 0xbc, 0x49, 0x30,
	0x2b, 0x38, 0x53, 0x4a, 0xc7, 0x31, 0xfc, 0x78, 0x09, 0xa6, 0x22, 0x30, 0xaa, 0x0e, 0x9f, 0x94,
	0x03, 0x3b, 0x81, 0x88, 0xc0, 0x52, 0x55, 0x7a, 0x13, 0x36, 0x67, 0xc2, 0x60, 0x41, 0xad, 0xd8,
	0x86, 0x15, 0x8b, 0x43, 0xf0, 0xe4, 0x25, 0x2a, 0x04, 0xfd, 0x05, 0x54, 0x97, 0x7f, 0x67, 0xcb,
	0x22, 0xa0, 0x7f, 0x06, 0x9b, 0x33, 0xa5, 0x83, 0xcf, 0x6e, 0x98, 0x91, 0x17, 0x7b, 0x5c, 0x08,
	0xc8, 0xc5, 0x13, 0xa0, 0x9c, 0x42, 0xd1, 0xe8, 0x7f, 0x29, 0x42, 0x45, 0x10, 0x65, 0xde, 0x47,
	0x3c, 0x9f, 0x29, 0xe4, 0xa2, 0x4a, 0xa7, 0x8a, 0xe9, 0x37, 0x90, 0x8e, 0x6b, 0xb1, 0x49, 0xfc,
	0x55, 0x49, 0x51, 0x61, 0x85, 0x66, 0x2e, 0xe7, 0x6b, 0x25, 0x59, 0xa1, 0x51, 0xe2, 0xd1, 0x20,
	0xfe, 0x75, 0x5a, 0xf1, 0x57, 0x98, 0x58, 0xe6, 0x9b, 0xf6, 0x8d, 0x5b, 0x16, 0xc8, 0xac, 0x17,
	0x02, 0x5f, 0x0b, 0x9f, 0x0b, 0xe1, 0x35, 0xb3, 0x9a, 0xc9, 0xf7, 0x16, 0x45, 0x85, 0x9f, 0x68,
	0x39, 0x43, 0xb8, 0x74, 0x23, 0xdb, 0xc1, 0x8b, 0xa9, 0x52, 0x45, 0xc3, 0x6f, 0x77, 0xca, 0x7d,
	0x9a, 0x91, 0x4c, 0xf8, 0x94, 0x2e, 0x5b, 0x59, 0xaa, 0x79, 0x95, 0x65, 0x2f, 0xcd, 0x90, 0x01,
	0x13, 0x59, 0x55, 0xe9, 0x7f, 0x2b, 0x40, 0x99, 0x3f, 0xd3, 0xbe, 0xb1, 0x03, 0x77, 0x60, 0xcd,
	0x73, 0xac, 0x0b, 0xf4, 0x87, 0x70, 0x61, 0x22, 0x0b, 0x02, 0xf0, 0x5e, 0x8c, 0x49, 0x27, 0xc6,
	0x32, 0x5f, 0x17, 0x5f, 0x6e, 0x17, 0x46, 0x74, 0x2d, 0x1d, 0x39, 0x55, 0xf0, 0x78, 0xf4, 0x1c,
	0x0b, 0xfb, 0x85, 0x70, 0x64, 0x2c, 0xf2, 0x11, 0x97, 0xbd, 0xc7, 0x11, 0xe1, 0xc1, 0x58, 0xd4,
	0xbf, 0x2c, 0xc0, 0x0a, 0xbe, 0x24, 0xbf, 0xf1, 0x99, 0x92, 0x0b, 0x2e, 0xa9, 0x17, 0x9c, 0x64,
	0x42, 0x59, 0xc9, 0x04, 0xae, 0x1d, 0x23, 0xc3, 0x11, 0xf9, 0x2a, 0x04, 0x3d, 0x84, 0x55, 0xf9,
	0x40, 0xfd, 0x2f, 0x6d, 0x86, 0x40, 0xd9, 0xe7, 0x9e, 0x93, 0x4d, 0x96, 0xff, 0xd7, 0xff, 0x5a,
	0xc2, 0xac, 0x94, 0x99, 0xf1, 0x09, 0xdc, 0x0b, 0xbd, 0x71, 0x60, 0xb2, 0x7e, 0x2a, 0x5e, 0xc4,
	0x0e, 0xf2, 0x86, 0x16, 0x12, 0x52, 0x0d, 0x56, 0x07, 0x92, 0x4e, 0x8a, 0x7d, 0xc4, 0x62, 0x9a,
	0xaa, 0x96, 0xbf, 0x0e, 0x55, 0x4d, 0x79, 0x66, 0xe5, 0x0e, 0xcf, 0x54, 0x16, 0xe5, 0xee, 0xea,
	0xdc, 0xdc, 0x5d, 0x9b, 0x97, 0xbb, 0xd5, 0x05, 0xb9, 0x0b, 0x77, 0xe5, 0x6e, 0xed, 0xce, 0xdc,
	0x5d, 0x5f, 0x26, 0x77, 0xeb, 0x39, 0xb9, 0xab, 0xff, 0xba, 0x00, 0xd5, 0xe4, 0x13, 0x05, 0xbf,
	0xe7, 0x77, 0xb6, 0x1b, 0x3f, 0x1b, 0xf0, 0x7f, 0x5e, 0xcc, 0xac, 0xa4, 0x3d, 0xf3, 0x04, 0xea,
	0xf2, 0xd3, 0x46, 0x4b, 0xb4, 0x2d, 0x71, 0x67, 0x69, 0x25, 0xbf, 0x53, 0xb9, 0x90, 0xfc, 0x22,
	0x1e, 0x8b, 0xfa, 0x04, 0x1a, 0xb3, 0x5f, 0x81, 0x94, 0xe7, 0x4b, 0x1d, 0x9f, 0x2f, 0xdc, 0x67,
	0x46, 0xc0, 0xdc, 0x28, 0x15, 0xb9, 0x8a, 0x8a, 0x33, 0x86, 0xe4, 0x7b, 0x41, 0x53, 0xd9, 0xb0,
	0x20, 0xae, 0xb9, 0x63, 0x4f, 0xff, 0x5c, 0x00, 0x92, 0xfd, 0x1e, 0x49, 0xfe, 0x1f, 0x3e, 0x38,
	0x3c, 0x3d, 0x3f, 0x3a, 0xa1, 0xed, 0xcf, 0xdb, 0xb4, 0xd7, 0x39, 0xec, 0x9c, 0x76, 0xfa, 0x6f,
	0x7f, 0xde, 0x3d, 0xef, 0xb6, 0x1b, 0xff, 0x47, 0xbe, 0x05, 0x8f, 0x72, 0x06, 0x63, 0xe9, 0xb4,
	0xdd, 0x28, 0x90, 0x8f, 0xe0, 0x71, 0x0e, 0xa4, 0x43, 0x15, 0x50, 0x91, 0x3c, 0x04, 0x2d, 0x07,
	0xd4, 0xeb, 0x37, 0x4f, 0xdb, 0x8d, 0xd2, 0x9c, 0x55, 0xce, 0x9a, 0x6f, 0x0f, 0xdb, 0x02, 0x52,
	0x7e, 0xfa, 0x55, 0xfa, 0x01, 0x2c, 0xbf, 0x51, 0xee, 0xc0, 0x83, 0x3e, 0x6d, 0x76, 0x7b, 0xcd,
	0xa3, 0x7e, 0xe7, 0xbc, 0xdb, 0xeb, 0x37, 0xfb, 0x97, 0xbd, 0x78, 0xeb, 0xbb, 0xb0, 0x93, 0x1d,
	0x6b, 0x7f, 0xd1, 0x3e, 0xba, 0xec, 0xb7, 0x5b, 0x8d, 0x42, 0xfe, 0x78, 0xef, 0xfc, 0xb8, 0x7f,
	0xdc, 0xec, 0x9c, 0x36, 0x8a, 0xf9, 0xe3, 0xaf, 0x9b, 0xb4, 0x85, 0xe3, 0x25, 0xf2, 0x08, 0x3e,
	0xcc, 0x8e, 0xb7, 0xda, 0xa7, 0xcd, 0xb7, 0xed, 0x56, 0xa3, 0x9c, 0x3f, 0xdc, 0xfe, 0xe2, 0xa2,
	0x43, 0xdb, 0xad, 0xc6, 0x4a, 0xfe, 0xf0, 0x65, 0xf7, 0xa4, 0x7b, 0xfe, 0xa6, 0xdb, 0xa8, 0xe4,
	0x2f, 0x7e, 0xd4, 0xec, 0x1e, 0xb5, 0x4f, 0xdb, 0xad, 0xc6, 0xea, 0x61, 0xe5, 0x67, 0x65, 0xce,
	0xc2, 0x06, 0x15, 0x2c, 0x03, 0x2f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x94, 0xa0, 0x86,
	0x73, 0x1d, 0x00, 0x00,
}
