// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/codecs/deth/deth.proto

package deth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrxLifecycleTransitionType int32

const (
	TrxLifecycleTransitionType_POOLED    TrxLifecycleTransitionType = 0
	TrxLifecycleTransitionType_MINED     TrxLifecycleTransitionType = 1
	TrxLifecycleTransitionType_FORKED    TrxLifecycleTransitionType = 2
	TrxLifecycleTransitionType_CONFIRMED TrxLifecycleTransitionType = 3
	TrxLifecycleTransitionType_REPLACED  TrxLifecycleTransitionType = 4
)

var TrxLifecycleTransitionType_name = map[int32]string{
	0: "POOLED",
	1: "MINED",
	2: "FORKED",
	3: "CONFIRMED",
	4: "REPLACED",
}

var TrxLifecycleTransitionType_value = map[string]int32{
	"POOLED":    0,
	"MINED":     1,
	"FORKED":    2,
	"CONFIRMED": 3,
	"REPLACED":  4,
}

func (x TrxLifecycleTransitionType) String() string {
	return proto.EnumName(TrxLifecycleTransitionType_name, int32(x))
}

func (TrxLifecycleTransitionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{0}
}

type TrxLifecycleState int32

const (
	TrxLifecycleState_TRX_UNKNOWN    TrxLifecycleState = 0
	TrxLifecycleState_TRX_IN_MEMPOOL TrxLifecycleState = 1
	TrxLifecycleState_TRX_IN_BLOCK   TrxLifecycleState = 2
	TrxLifecycleState_TRX_SHADOWED   TrxLifecycleState = 3
)

var TrxLifecycleState_name = map[int32]string{
	0: "TRX_UNKNOWN",
	1: "TRX_IN_MEMPOOL",
	2: "TRX_IN_BLOCK",
	3: "TRX_SHADOWED",
}

var TrxLifecycleState_value = map[string]int32{
	"TRX_UNKNOWN":    0,
	"TRX_IN_MEMPOOL": 1,
	"TRX_IN_BLOCK":   2,
	"TRX_SHADOWED":   3,
}

func (x TrxLifecycleState) String() string {
	return proto.EnumName(TrxLifecycleState_name, int32(x))
}

func (TrxLifecycleState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{1}
}

type TransactionTraceStatus int32

const (
	TransactionTraceStatus_UNKNOWN   TransactionTraceStatus = 0
	TransactionTraceStatus_SUCCEEDED TransactionTraceStatus = 1
	TransactionTraceStatus_FAILED    TransactionTraceStatus = 2
	TransactionTraceStatus_REVERTED  TransactionTraceStatus = 3
)

var TransactionTraceStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCEEDED",
	2: "FAILED",
	3: "REVERTED",
}

var TransactionTraceStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"SUCCEEDED": 1,
	"FAILED":    2,
	"REVERTED":  3,
}

func (x TransactionTraceStatus) String() string {
	return proto.EnumName(TransactionTraceStatus_name, int32(x))
}

func (TransactionTraceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{2}
}

type CallType int32

const (
	CallType_UNSPECIFIED CallType = 0
	CallType_CALL        CallType = 1
	CallType_CALLCODE    CallType = 2
	CallType_DELEGATE    CallType = 3
	CallType_STATIC      CallType = 4
	CallType_CREATE      CallType = 5
)

var CallType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "CALL",
	2: "CALLCODE",
	3: "DELEGATE",
	4: "STATIC",
	5: "CREATE",
}

var CallType_value = map[string]int32{
	"UNSPECIFIED": 0,
	"CALL":        1,
	"CALLCODE":    2,
	"DELEGATE":    3,
	"STATIC":      4,
	"CREATE":      5,
}

func (x CallType) String() string {
	return proto.EnumName(CallType_name, int32(x))
}

func (CallType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{3}
}

type Block struct {
	Ver                  int32               `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Hash                 []byte              `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               uint64              `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Size                 uint64              `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Header               *BlockHeader        `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Uncles               []*BlockHeader      `protobuf:"bytes,6,rep,name=uncles,proto3" json:"uncles,omitempty"`
	TransactionTraces    []*TransactionTrace `protobuf:"bytes,10,rep,name=transaction_traces,json=transactionTraces,proto3" json:"transaction_traces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetUncles() []*BlockHeader {
	if m != nil {
		return m.Uncles
	}
	return nil
}

func (m *Block) GetTransactionTraces() []*TransactionTrace {
	if m != nil {
		return m.TransactionTraces
	}
	return nil
}

type TransactionRefs struct {
	Hashes               [][]byte `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRefs) Reset()         { *m = TransactionRefs{} }
func (m *TransactionRefs) String() string { return proto.CompactTextString(m) }
func (*TransactionRefs) ProtoMessage()    {}
func (*TransactionRefs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{1}
}

func (m *TransactionRefs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRefs.Unmarshal(m, b)
}
func (m *TransactionRefs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRefs.Marshal(b, m, deterministic)
}
func (m *TransactionRefs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRefs.Merge(m, src)
}
func (m *TransactionRefs) XXX_Size() int {
	return xxx_messageInfo_TransactionRefs.Size(m)
}
func (m *TransactionRefs) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRefs.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRefs proto.InternalMessageInfo

func (m *TransactionRefs) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type UnclesHeaders struct {
	Uncles               []*BlockHeader `protobuf:"bytes,1,rep,name=uncles,proto3" json:"uncles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UnclesHeaders) Reset()         { *m = UnclesHeaders{} }
func (m *UnclesHeaders) String() string { return proto.CompactTextString(m) }
func (*UnclesHeaders) ProtoMessage()    {}
func (*UnclesHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{2}
}

func (m *UnclesHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnclesHeaders.Unmarshal(m, b)
}
func (m *UnclesHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnclesHeaders.Marshal(b, m, deterministic)
}
func (m *UnclesHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnclesHeaders.Merge(m, src)
}
func (m *UnclesHeaders) XXX_Size() int {
	return xxx_messageInfo_UnclesHeaders.Size(m)
}
func (m *UnclesHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_UnclesHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_UnclesHeaders proto.InternalMessageInfo

func (m *UnclesHeaders) GetUncles() []*BlockHeader {
	if m != nil {
		return m.Uncles
	}
	return nil
}

type BlockRef struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               uint64   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRef) Reset()         { *m = BlockRef{} }
func (m *BlockRef) String() string { return proto.CompactTextString(m) }
func (*BlockRef) ProtoMessage()    {}
func (*BlockRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{3}
}

func (m *BlockRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRef.Unmarshal(m, b)
}
func (m *BlockRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRef.Marshal(b, m, deterministic)
}
func (m *BlockRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRef.Merge(m, src)
}
func (m *BlockRef) XXX_Size() int {
	return xxx_messageInfo_BlockRef.Size(m)
}
func (m *BlockRef) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRef.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRef proto.InternalMessageInfo

func (m *BlockRef) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockRef) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type BlockHeader struct {
	ParentHash           []byte               `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	UncleHash            []byte               `protobuf:"bytes,2,opt,name=uncle_hash,json=uncleHash,proto3" json:"uncle_hash,omitempty"`
	Coinbase             []byte               `protobuf:"bytes,3,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	StateRoot            []byte               `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	TransactionsRoot     []byte               `protobuf:"bytes,5,opt,name=transactions_root,json=transactionsRoot,proto3" json:"transactions_root,omitempty"`
	ReceiptRoot          []byte               `protobuf:"bytes,6,opt,name=receipt_root,json=receiptRoot,proto3" json:"receipt_root,omitempty"`
	LogsBloom            []byte               `protobuf:"bytes,7,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	Difficulty           *BigInt              `protobuf:"bytes,8,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Number               uint64               `protobuf:"varint,9,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit             uint64               `protobuf:"varint,10,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed              uint64               `protobuf:"varint,11,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData            []byte               `protobuf:"bytes,13,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	MixHash              []byte               `protobuf:"bytes,14,opt,name=mix_hash,json=mixHash,proto3" json:"mix_hash,omitempty"`
	Nonce                uint64               `protobuf:"varint,15,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Hash                 []byte               `protobuf:"bytes,16,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{4}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetUncleHash() []byte {
	if m != nil {
		return m.UncleHash
	}
	return nil
}

func (m *BlockHeader) GetCoinbase() []byte {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *BlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeader) GetTransactionsRoot() []byte {
	if m != nil {
		return m.TransactionsRoot
	}
	return nil
}

func (m *BlockHeader) GetReceiptRoot() []byte {
	if m != nil {
		return m.ReceiptRoot
	}
	return nil
}

func (m *BlockHeader) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *BlockHeader) GetDifficulty() *BigInt {
	if m != nil {
		return m.Difficulty
	}
	return nil
}

func (m *BlockHeader) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockHeader) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *BlockHeader) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BlockHeader) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *BlockHeader) GetMixHash() []byte {
	if m != nil {
		return m.MixHash
	}
	return nil
}

func (m *BlockHeader) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BigInt struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigInt) Reset()         { *m = BigInt{} }
func (m *BigInt) String() string { return proto.CompactTextString(m) }
func (*BigInt) ProtoMessage()    {}
func (*BigInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{5}
}

func (m *BigInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigInt.Unmarshal(m, b)
}
func (m *BigInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigInt.Marshal(b, m, deterministic)
}
func (m *BigInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigInt.Merge(m, src)
}
func (m *BigInt) XXX_Size() int {
	return xxx_messageInfo_BigInt.Size(m)
}
func (m *BigInt) XXX_DiscardUnknown() {
	xxx_messageInfo_BigInt.DiscardUnknown(m)
}

var xxx_messageInfo_BigInt proto.InternalMessageInfo

func (m *BigInt) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type TrxLifecycleTransitionPooled struct {
	NewState             TrxLifecycleState `protobuf:"varint,1,opt,name=new_state,json=newState,proto3,enum=dfuse.codecs.deth.TrxLifecycleState" json:"new_state,omitempty"`
	OldState             TrxLifecycleState `protobuf:"varint,2,opt,name=old_state,json=oldState,proto3,enum=dfuse.codecs.deth.TrxLifecycleState" json:"old_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TrxLifecycleTransitionPooled) Reset()         { *m = TrxLifecycleTransitionPooled{} }
func (m *TrxLifecycleTransitionPooled) String() string { return proto.CompactTextString(m) }
func (*TrxLifecycleTransitionPooled) ProtoMessage()    {}
func (*TrxLifecycleTransitionPooled) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{6}
}

func (m *TrxLifecycleTransitionPooled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxLifecycleTransitionPooled.Unmarshal(m, b)
}
func (m *TrxLifecycleTransitionPooled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxLifecycleTransitionPooled.Marshal(b, m, deterministic)
}
func (m *TrxLifecycleTransitionPooled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxLifecycleTransitionPooled.Merge(m, src)
}
func (m *TrxLifecycleTransitionPooled) XXX_Size() int {
	return xxx_messageInfo_TrxLifecycleTransitionPooled.Size(m)
}
func (m *TrxLifecycleTransitionPooled) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxLifecycleTransitionPooled.DiscardUnknown(m)
}

var xxx_messageInfo_TrxLifecycleTransitionPooled proto.InternalMessageInfo

func (m *TrxLifecycleTransitionPooled) GetNewState() TrxLifecycleState {
	if m != nil {
		return m.NewState
	}
	return TrxLifecycleState_TRX_UNKNOWN
}

func (m *TrxLifecycleTransitionPooled) GetOldState() TrxLifecycleState {
	if m != nil {
		return m.OldState
	}
	return TrxLifecycleState_TRX_UNKNOWN
}

type TrxLifecycleTransitionMined struct {
	NewState             TrxLifecycleState `protobuf:"varint,1,opt,name=new_state,json=newState,proto3,enum=dfuse.codecs.deth.TrxLifecycleState" json:"new_state,omitempty"`
	OldState             TrxLifecycleState `protobuf:"varint,2,opt,name=old_state,json=oldState,proto3,enum=dfuse.codecs.deth.TrxLifecycleState" json:"old_state,omitempty"`
	TransactionTraces    *TransactionTrace `protobuf:"bytes,3,opt,name=transaction_traces,json=transactionTraces,proto3" json:"transaction_traces,omitempty"`
	BlockHeader          *BlockHeader      `protobuf:"bytes,4,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TrxLifecycleTransitionMined) Reset()         { *m = TrxLifecycleTransitionMined{} }
func (m *TrxLifecycleTransitionMined) String() string { return proto.CompactTextString(m) }
func (*TrxLifecycleTransitionMined) ProtoMessage()    {}
func (*TrxLifecycleTransitionMined) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{7}
}

func (m *TrxLifecycleTransitionMined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxLifecycleTransitionMined.Unmarshal(m, b)
}
func (m *TrxLifecycleTransitionMined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxLifecycleTransitionMined.Marshal(b, m, deterministic)
}
func (m *TrxLifecycleTransitionMined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxLifecycleTransitionMined.Merge(m, src)
}
func (m *TrxLifecycleTransitionMined) XXX_Size() int {
	return xxx_messageInfo_TrxLifecycleTransitionMined.Size(m)
}
func (m *TrxLifecycleTransitionMined) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxLifecycleTransitionMined.DiscardUnknown(m)
}

var xxx_messageInfo_TrxLifecycleTransitionMined proto.InternalMessageInfo

func (m *TrxLifecycleTransitionMined) GetNewState() TrxLifecycleState {
	if m != nil {
		return m.NewState
	}
	return TrxLifecycleState_TRX_UNKNOWN
}

func (m *TrxLifecycleTransitionMined) GetOldState() TrxLifecycleState {
	if m != nil {
		return m.OldState
	}
	return TrxLifecycleState_TRX_UNKNOWN
}

func (m *TrxLifecycleTransitionMined) GetTransactionTraces() *TransactionTrace {
	if m != nil {
		return m.TransactionTraces
	}
	return nil
}

func (m *TrxLifecycleTransitionMined) GetBlockHeader() *BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

type TrxLifecycleTransitionForked struct {
	NewState TrxLifecycleState `protobuf:"varint,1,opt,name=new_state,json=newState,proto3,enum=dfuse.codecs.deth.TrxLifecycleState" json:"new_state,omitempty"`
	// (il faut d'abord passer par un UNDO donc MEMPOOL)
	OldState             TrxLifecycleState `protobuf:"varint,2,opt,name=old_state,json=oldState,proto3,enum=dfuse.codecs.deth.TrxLifecycleState" json:"old_state,omitempty"`
	TransactionTraces    *TransactionTrace `protobuf:"bytes,3,opt,name=transaction_traces,json=transactionTraces,proto3" json:"transaction_traces,omitempty"`
	BlockHeader          *BlockHeader      `protobuf:"bytes,4,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TrxLifecycleTransitionForked) Reset()         { *m = TrxLifecycleTransitionForked{} }
func (m *TrxLifecycleTransitionForked) String() string { return proto.CompactTextString(m) }
func (*TrxLifecycleTransitionForked) ProtoMessage()    {}
func (*TrxLifecycleTransitionForked) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{8}
}

func (m *TrxLifecycleTransitionForked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxLifecycleTransitionForked.Unmarshal(m, b)
}
func (m *TrxLifecycleTransitionForked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxLifecycleTransitionForked.Marshal(b, m, deterministic)
}
func (m *TrxLifecycleTransitionForked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxLifecycleTransitionForked.Merge(m, src)
}
func (m *TrxLifecycleTransitionForked) XXX_Size() int {
	return xxx_messageInfo_TrxLifecycleTransitionForked.Size(m)
}
func (m *TrxLifecycleTransitionForked) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxLifecycleTransitionForked.DiscardUnknown(m)
}

var xxx_messageInfo_TrxLifecycleTransitionForked proto.InternalMessageInfo

func (m *TrxLifecycleTransitionForked) GetNewState() TrxLifecycleState {
	if m != nil {
		return m.NewState
	}
	return TrxLifecycleState_TRX_UNKNOWN
}

func (m *TrxLifecycleTransitionForked) GetOldState() TrxLifecycleState {
	if m != nil {
		return m.OldState
	}
	return TrxLifecycleState_TRX_UNKNOWN
}

func (m *TrxLifecycleTransitionForked) GetTransactionTraces() *TransactionTrace {
	if m != nil {
		return m.TransactionTraces
	}
	return nil
}

func (m *TrxLifecycleTransitionForked) GetBlockHeader() *BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

type TrxLifecycleTransitionConfirmed struct {
	NewState             TrxLifecycleState `protobuf:"varint,1,opt,name=new_state,json=newState,proto3,enum=dfuse.codecs.deth.TrxLifecycleState" json:"new_state,omitempty"`
	OldState             TrxLifecycleState `protobuf:"varint,2,opt,name=old_state,json=oldState,proto3,enum=dfuse.codecs.deth.TrxLifecycleState" json:"old_state,omitempty"`
	BlockDepth           uint64            `protobuf:"varint,3,opt,name=block_depth,json=blockDepth,proto3" json:"block_depth,omitempty"`
	HeadBlockHeader      *BlockHeader      `protobuf:"bytes,4,opt,name=head_block_header,json=headBlockHeader,proto3" json:"head_block_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TrxLifecycleTransitionConfirmed) Reset()         { *m = TrxLifecycleTransitionConfirmed{} }
func (m *TrxLifecycleTransitionConfirmed) String() string { return proto.CompactTextString(m) }
func (*TrxLifecycleTransitionConfirmed) ProtoMessage()    {}
func (*TrxLifecycleTransitionConfirmed) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{9}
}

func (m *TrxLifecycleTransitionConfirmed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxLifecycleTransitionConfirmed.Unmarshal(m, b)
}
func (m *TrxLifecycleTransitionConfirmed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxLifecycleTransitionConfirmed.Marshal(b, m, deterministic)
}
func (m *TrxLifecycleTransitionConfirmed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxLifecycleTransitionConfirmed.Merge(m, src)
}
func (m *TrxLifecycleTransitionConfirmed) XXX_Size() int {
	return xxx_messageInfo_TrxLifecycleTransitionConfirmed.Size(m)
}
func (m *TrxLifecycleTransitionConfirmed) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxLifecycleTransitionConfirmed.DiscardUnknown(m)
}

var xxx_messageInfo_TrxLifecycleTransitionConfirmed proto.InternalMessageInfo

func (m *TrxLifecycleTransitionConfirmed) GetNewState() TrxLifecycleState {
	if m != nil {
		return m.NewState
	}
	return TrxLifecycleState_TRX_UNKNOWN
}

func (m *TrxLifecycleTransitionConfirmed) GetOldState() TrxLifecycleState {
	if m != nil {
		return m.OldState
	}
	return TrxLifecycleState_TRX_UNKNOWN
}

func (m *TrxLifecycleTransitionConfirmed) GetBlockDepth() uint64 {
	if m != nil {
		return m.BlockDepth
	}
	return 0
}

func (m *TrxLifecycleTransitionConfirmed) GetHeadBlockHeader() *BlockHeader {
	if m != nil {
		return m.HeadBlockHeader
	}
	return nil
}

type TrxLifecycleTransitionReplaced struct {
	NewState             TrxLifecycleState `protobuf:"varint,1,opt,name=new_state,json=newState,proto3,enum=dfuse.codecs.deth.TrxLifecycleState" json:"new_state,omitempty"`
	OldState             TrxLifecycleState `protobuf:"varint,2,opt,name=old_state,json=oldState,proto3,enum=dfuse.codecs.deth.TrxLifecycleState" json:"old_state,omitempty"`
	ShadowedBy           *TransactionTrace `protobuf:"bytes,3,opt,name=shadowed_by,json=shadowedBy,proto3" json:"shadowed_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TrxLifecycleTransitionReplaced) Reset()         { *m = TrxLifecycleTransitionReplaced{} }
func (m *TrxLifecycleTransitionReplaced) String() string { return proto.CompactTextString(m) }
func (*TrxLifecycleTransitionReplaced) ProtoMessage()    {}
func (*TrxLifecycleTransitionReplaced) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{10}
}

func (m *TrxLifecycleTransitionReplaced) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxLifecycleTransitionReplaced.Unmarshal(m, b)
}
func (m *TrxLifecycleTransitionReplaced) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxLifecycleTransitionReplaced.Marshal(b, m, deterministic)
}
func (m *TrxLifecycleTransitionReplaced) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxLifecycleTransitionReplaced.Merge(m, src)
}
func (m *TrxLifecycleTransitionReplaced) XXX_Size() int {
	return xxx_messageInfo_TrxLifecycleTransitionReplaced.Size(m)
}
func (m *TrxLifecycleTransitionReplaced) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxLifecycleTransitionReplaced.DiscardUnknown(m)
}

var xxx_messageInfo_TrxLifecycleTransitionReplaced proto.InternalMessageInfo

func (m *TrxLifecycleTransitionReplaced) GetNewState() TrxLifecycleState {
	if m != nil {
		return m.NewState
	}
	return TrxLifecycleState_TRX_UNKNOWN
}

func (m *TrxLifecycleTransitionReplaced) GetOldState() TrxLifecycleState {
	if m != nil {
		return m.OldState
	}
	return TrxLifecycleState_TRX_UNKNOWN
}

func (m *TrxLifecycleTransitionReplaced) GetShadowedBy() *TransactionTrace {
	if m != nil {
		return m.ShadowedBy
	}
	return nil
}

type TransactionLifecycleMessage struct {
	Trx *Transaction `protobuf:"bytes,1,opt,name=trx,proto3" json:"trx,omitempty"`
	// Types that are valid to be assigned to TrxLifecycleTransition:
	//	*TransactionLifecycleMessage_Pooled
	//	*TransactionLifecycleMessage_Mined
	//	*TransactionLifecycleMessage_Forked
	//	*TransactionLifecycleMessage_Confirmed
	//	*TransactionLifecycleMessage_Replaced
	TrxLifecycleTransition isTransactionLifecycleMessage_TrxLifecycleTransition `protobuf_oneof:"trx_lifecycle_transition"`
	XXX_NoUnkeyedLiteral   struct{}                                             `json:"-"`
	XXX_unrecognized       []byte                                               `json:"-"`
	XXX_sizecache          int32                                                `json:"-"`
}

func (m *TransactionLifecycleMessage) Reset()         { *m = TransactionLifecycleMessage{} }
func (m *TransactionLifecycleMessage) String() string { return proto.CompactTextString(m) }
func (*TransactionLifecycleMessage) ProtoMessage()    {}
func (*TransactionLifecycleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{11}
}

func (m *TransactionLifecycleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionLifecycleMessage.Unmarshal(m, b)
}
func (m *TransactionLifecycleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionLifecycleMessage.Marshal(b, m, deterministic)
}
func (m *TransactionLifecycleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionLifecycleMessage.Merge(m, src)
}
func (m *TransactionLifecycleMessage) XXX_Size() int {
	return xxx_messageInfo_TransactionLifecycleMessage.Size(m)
}
func (m *TransactionLifecycleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionLifecycleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionLifecycleMessage proto.InternalMessageInfo

func (m *TransactionLifecycleMessage) GetTrx() *Transaction {
	if m != nil {
		return m.Trx
	}
	return nil
}

type isTransactionLifecycleMessage_TrxLifecycleTransition interface {
	isTransactionLifecycleMessage_TrxLifecycleTransition()
}

type TransactionLifecycleMessage_Pooled struct {
	Pooled *TrxLifecycleTransitionPooled `protobuf:"bytes,3,opt,name=pooled,proto3,oneof"`
}

type TransactionLifecycleMessage_Mined struct {
	Mined *TrxLifecycleTransitionMined `protobuf:"bytes,4,opt,name=mined,proto3,oneof"`
}

type TransactionLifecycleMessage_Forked struct {
	Forked *TrxLifecycleTransitionForked `protobuf:"bytes,5,opt,name=forked,proto3,oneof"`
}

type TransactionLifecycleMessage_Confirmed struct {
	Confirmed *TrxLifecycleTransitionConfirmed `protobuf:"bytes,6,opt,name=confirmed,proto3,oneof"`
}

type TransactionLifecycleMessage_Replaced struct {
	Replaced *TrxLifecycleTransitionReplaced `protobuf:"bytes,7,opt,name=replaced,proto3,oneof"`
}

func (*TransactionLifecycleMessage_Pooled) isTransactionLifecycleMessage_TrxLifecycleTransition() {}

func (*TransactionLifecycleMessage_Mined) isTransactionLifecycleMessage_TrxLifecycleTransition() {}

func (*TransactionLifecycleMessage_Forked) isTransactionLifecycleMessage_TrxLifecycleTransition() {}

func (*TransactionLifecycleMessage_Confirmed) isTransactionLifecycleMessage_TrxLifecycleTransition() {}

func (*TransactionLifecycleMessage_Replaced) isTransactionLifecycleMessage_TrxLifecycleTransition() {}

func (m *TransactionLifecycleMessage) GetTrxLifecycleTransition() isTransactionLifecycleMessage_TrxLifecycleTransition {
	if m != nil {
		return m.TrxLifecycleTransition
	}
	return nil
}

func (m *TransactionLifecycleMessage) GetPooled() *TrxLifecycleTransitionPooled {
	if x, ok := m.GetTrxLifecycleTransition().(*TransactionLifecycleMessage_Pooled); ok {
		return x.Pooled
	}
	return nil
}

func (m *TransactionLifecycleMessage) GetMined() *TrxLifecycleTransitionMined {
	if x, ok := m.GetTrxLifecycleTransition().(*TransactionLifecycleMessage_Mined); ok {
		return x.Mined
	}
	return nil
}

func (m *TransactionLifecycleMessage) GetForked() *TrxLifecycleTransitionForked {
	if x, ok := m.GetTrxLifecycleTransition().(*TransactionLifecycleMessage_Forked); ok {
		return x.Forked
	}
	return nil
}

func (m *TransactionLifecycleMessage) GetConfirmed() *TrxLifecycleTransitionConfirmed {
	if x, ok := m.GetTrxLifecycleTransition().(*TransactionLifecycleMessage_Confirmed); ok {
		return x.Confirmed
	}
	return nil
}

func (m *TransactionLifecycleMessage) GetReplaced() *TrxLifecycleTransitionReplaced {
	if x, ok := m.GetTrxLifecycleTransition().(*TransactionLifecycleMessage_Replaced); ok {
		return x.Replaced
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TransactionLifecycleMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TransactionLifecycleMessage_Pooled)(nil),
		(*TransactionLifecycleMessage_Mined)(nil),
		(*TransactionLifecycleMessage_Forked)(nil),
		(*TransactionLifecycleMessage_Confirmed)(nil),
		(*TransactionLifecycleMessage_Replaced)(nil),
	}
}

// A Transaction not yet in block
type Transaction struct {
	// consensus
	To       []byte  `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Nonce    uint64  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasPrice *BigInt `protobuf:"bytes,3,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit uint64  `protobuf:"varint,4,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Value    *BigInt `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Input    []byte  `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	V        []byte  `protobuf:"bytes,7,opt,name=v,proto3" json:"v,omitempty"`
	R        []byte  `protobuf:"bytes,8,opt,name=r,proto3" json:"r,omitempty"`
	S        []byte  `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	// meta
	Hash                 []byte   `protobuf:"bytes,21,opt,name=hash,proto3" json:"hash,omitempty"`
	From                 []byte   `protobuf:"bytes,22,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{12}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetGasPrice() *BigInt {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *Transaction) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Transaction) GetValue() *BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Transaction) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *Transaction) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Transaction) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

type TransactionTrace struct {
	// consensus
	To       []byte  `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Nonce    uint64  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasPrice *BigInt `protobuf:"bytes,3,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit uint64  `protobuf:"varint,4,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Value    *BigInt `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Input    []byte  `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	V        []byte  `protobuf:"bytes,7,opt,name=v,proto3" json:"v,omitempty"`
	R        []byte  `protobuf:"bytes,8,opt,name=r,proto3" json:"r,omitempty"`
	S        []byte  `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	GasUsed  uint64  `protobuf:"varint,10,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// meta
	Index                uint32                 `protobuf:"varint,20,opt,name=index,proto3" json:"index,omitempty"`
	Hash                 []byte                 `protobuf:"bytes,21,opt,name=hash,proto3" json:"hash,omitempty"`
	From                 []byte                 `protobuf:"bytes,22,opt,name=from,proto3" json:"from,omitempty"`
	ReturnData           []byte                 `protobuf:"bytes,23,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	PublicKey            []byte                 `protobuf:"bytes,24,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status               TransactionTraceStatus `protobuf:"varint,30,opt,name=status,proto3,enum=dfuse.codecs.deth.TransactionTraceStatus" json:"status,omitempty"`
	Receipt              *TransactionReceipt    `protobuf:"bytes,31,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Calls                []*Call                `protobuf:"bytes,32,rep,name=calls,proto3" json:"calls,omitempty"`
	BalanceChanges       []*BalanceChange       `protobuf:"bytes,40,rep,name=balance_changes,json=balanceChanges,proto3" json:"balance_changes,omitempty"`
	NonceChanges         []*NonceChange         `protobuf:"bytes,41,rep,name=nonce_changes,json=nonceChanges,proto3" json:"nonce_changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TransactionTrace) Reset()         { *m = TransactionTrace{} }
func (m *TransactionTrace) String() string { return proto.CompactTextString(m) }
func (*TransactionTrace) ProtoMessage()    {}
func (*TransactionTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{13}
}

func (m *TransactionTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionTrace.Unmarshal(m, b)
}
func (m *TransactionTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionTrace.Marshal(b, m, deterministic)
}
func (m *TransactionTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionTrace.Merge(m, src)
}
func (m *TransactionTrace) XXX_Size() int {
	return xxx_messageInfo_TransactionTrace.Size(m)
}
func (m *TransactionTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionTrace.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionTrace proto.InternalMessageInfo

func (m *TransactionTrace) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransactionTrace) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionTrace) GetGasPrice() *BigInt {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *TransactionTrace) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *TransactionTrace) GetValue() *BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TransactionTrace) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *TransactionTrace) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *TransactionTrace) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *TransactionTrace) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *TransactionTrace) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *TransactionTrace) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TransactionTrace) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *TransactionTrace) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransactionTrace) GetReturnData() []byte {
	if m != nil {
		return m.ReturnData
	}
	return nil
}

func (m *TransactionTrace) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *TransactionTrace) GetStatus() TransactionTraceStatus {
	if m != nil {
		return m.Status
	}
	return TransactionTraceStatus_UNKNOWN
}

func (m *TransactionTrace) GetReceipt() *TransactionReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *TransactionTrace) GetCalls() []*Call {
	if m != nil {
		return m.Calls
	}
	return nil
}

func (m *TransactionTrace) GetBalanceChanges() []*BalanceChange {
	if m != nil {
		return m.BalanceChanges
	}
	return nil
}

func (m *TransactionTrace) GetNonceChanges() []*NonceChange {
	if m != nil {
		return m.NonceChanges
	}
	return nil
}

type TransactionReceipt struct {
	// consensus
	StateRoot            []byte   `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	CumulativeGasUsed    uint64   `protobuf:"varint,2,opt,name=cumulative_gas_used,json=cumulativeGasUsed,proto3" json:"cumulative_gas_used,omitempty"`
	LogsBloom            []byte   `protobuf:"bytes,3,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionReceipt) Reset()         { *m = TransactionReceipt{} }
func (m *TransactionReceipt) String() string { return proto.CompactTextString(m) }
func (*TransactionReceipt) ProtoMessage()    {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{14}
}

func (m *TransactionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReceipt.Unmarshal(m, b)
}
func (m *TransactionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReceipt.Marshal(b, m, deterministic)
}
func (m *TransactionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReceipt.Merge(m, src)
}
func (m *TransactionReceipt) XXX_Size() int {
	return xxx_messageInfo_TransactionReceipt.Size(m)
}
func (m *TransactionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReceipt proto.InternalMessageInfo

func (m *TransactionReceipt) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *TransactionReceipt) GetCumulativeGasUsed() uint64 {
	if m != nil {
		return m.CumulativeGasUsed
	}
	return 0
}

func (m *TransactionReceipt) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *TransactionReceipt) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Log struct {
	// consensus
	Address []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics  [][]byte `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data    []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// supplement
	Index                uint32   `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{15}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Log) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *Log) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Log) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Call struct {
	Index                uint32            `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ParentIndex          uint32            `protobuf:"varint,2,opt,name=parent_index,json=parentIndex,proto3" json:"parent_index,omitempty"`
	Depth                uint32            `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	CallType             CallType          `protobuf:"varint,4,opt,name=call_type,json=callType,proto3,enum=dfuse.codecs.deth.CallType" json:"call_type,omitempty"`
	Caller               []byte            `protobuf:"bytes,5,opt,name=caller,proto3" json:"caller,omitempty"`
	Address              []byte            `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Value                *BigInt           `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	GasLimit             uint64            `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasConsumed          uint64            `protobuf:"varint,9,opt,name=gas_consumed,json=gasConsumed,proto3" json:"gas_consumed,omitempty"`
	Failed               bool              `protobuf:"varint,10,opt,name=failed,proto3" json:"failed,omitempty"`
	FailureReason        string            `protobuf:"bytes,11,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	Reverted             bool              `protobuf:"varint,12,opt,name=reverted,proto3" json:"reverted,omitempty"`
	ReturnData           []byte            `protobuf:"bytes,13,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	Input                []byte            `protobuf:"bytes,14,opt,name=input,proto3" json:"input,omitempty"`
	ExecutedCode         bool              `protobuf:"varint,15,opt,name=executed_code,json=executedCode,proto3" json:"executed_code,omitempty"`
	KeccakPreimages      map[string]string `protobuf:"bytes,20,rep,name=keccak_preimages,json=keccakPreimages,proto3" json:"keccak_preimages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StorageChanges       []*StorageChange  `protobuf:"bytes,21,rep,name=storage_changes,json=storageChanges,proto3" json:"storage_changes,omitempty"`
	BalanceChanges       []*BalanceChange  `protobuf:"bytes,22,rep,name=balance_changes,json=balanceChanges,proto3" json:"balance_changes,omitempty"`
	NonceChanges         []*NonceChange    `protobuf:"bytes,24,rep,name=nonce_changes,json=nonceChanges,proto3" json:"nonce_changes,omitempty"`
	Logs                 []*Log            `protobuf:"bytes,25,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{16}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Call) GetParentIndex() uint32 {
	if m != nil {
		return m.ParentIndex
	}
	return 0
}

func (m *Call) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *Call) GetCallType() CallType {
	if m != nil {
		return m.CallType
	}
	return CallType_UNSPECIFIED
}

func (m *Call) GetCaller() []byte {
	if m != nil {
		return m.Caller
	}
	return nil
}

func (m *Call) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Call) GetValue() *BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Call) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Call) GetGasConsumed() uint64 {
	if m != nil {
		return m.GasConsumed
	}
	return 0
}

func (m *Call) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *Call) GetFailureReason() string {
	if m != nil {
		return m.FailureReason
	}
	return ""
}

func (m *Call) GetReverted() bool {
	if m != nil {
		return m.Reverted
	}
	return false
}

func (m *Call) GetReturnData() []byte {
	if m != nil {
		return m.ReturnData
	}
	return nil
}

func (m *Call) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Call) GetExecutedCode() bool {
	if m != nil {
		return m.ExecutedCode
	}
	return false
}

func (m *Call) GetKeccakPreimages() map[string]string {
	if m != nil {
		return m.KeccakPreimages
	}
	return nil
}

func (m *Call) GetStorageChanges() []*StorageChange {
	if m != nil {
		return m.StorageChanges
	}
	return nil
}

func (m *Call) GetBalanceChanges() []*BalanceChange {
	if m != nil {
		return m.BalanceChanges
	}
	return nil
}

func (m *Call) GetNonceChanges() []*NonceChange {
	if m != nil {
		return m.NonceChanges
	}
	return nil
}

func (m *Call) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type StorageChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	OldValue             []byte   `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             []byte   `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageChange) Reset()         { *m = StorageChange{} }
func (m *StorageChange) String() string { return proto.CompactTextString(m) }
func (*StorageChange) ProtoMessage()    {}
func (*StorageChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{17}
}

func (m *StorageChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageChange.Unmarshal(m, b)
}
func (m *StorageChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageChange.Marshal(b, m, deterministic)
}
func (m *StorageChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageChange.Merge(m, src)
}
func (m *StorageChange) XXX_Size() int {
	return xxx_messageInfo_StorageChange.Size(m)
}
func (m *StorageChange) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageChange.DiscardUnknown(m)
}

var xxx_messageInfo_StorageChange proto.InternalMessageInfo

func (m *StorageChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *StorageChange) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *StorageChange) GetOldValue() []byte {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *StorageChange) GetNewValue() []byte {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type BalanceChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldValue             *BigInt  `protobuf:"bytes,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             *BigInt  `protobuf:"bytes,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceChange) Reset()         { *m = BalanceChange{} }
func (m *BalanceChange) String() string { return proto.CompactTextString(m) }
func (*BalanceChange) ProtoMessage()    {}
func (*BalanceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{18}
}

func (m *BalanceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceChange.Unmarshal(m, b)
}
func (m *BalanceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceChange.Marshal(b, m, deterministic)
}
func (m *BalanceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceChange.Merge(m, src)
}
func (m *BalanceChange) XXX_Size() int {
	return xxx_messageInfo_BalanceChange.Size(m)
}
func (m *BalanceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceChange.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceChange proto.InternalMessageInfo

func (m *BalanceChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BalanceChange) GetOldValue() *BigInt {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *BalanceChange) GetNewValue() *BigInt {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type NonceChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldValue             uint64   `protobuf:"varint,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             uint64   `protobuf:"varint,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonceChange) Reset()         { *m = NonceChange{} }
func (m *NonceChange) String() string { return proto.CompactTextString(m) }
func (*NonceChange) ProtoMessage()    {}
func (*NonceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{19}
}

func (m *NonceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonceChange.Unmarshal(m, b)
}
func (m *NonceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonceChange.Marshal(b, m, deterministic)
}
func (m *NonceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceChange.Merge(m, src)
}
func (m *NonceChange) XXX_Size() int {
	return xxx_messageInfo_NonceChange.Size(m)
}
func (m *NonceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceChange.DiscardUnknown(m)
}

var xxx_messageInfo_NonceChange proto.InternalMessageInfo

func (m *NonceChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *NonceChange) GetOldValue() uint64 {
	if m != nil {
		return m.OldValue
	}
	return 0
}

func (m *NonceChange) GetNewValue() uint64 {
	if m != nil {
		return m.NewValue
	}
	return 0
}

func init() {
	proto.RegisterEnum("dfuse.codecs.deth.TrxLifecycleTransitionType", TrxLifecycleTransitionType_name, TrxLifecycleTransitionType_value)
	proto.RegisterEnum("dfuse.codecs.deth.TrxLifecycleState", TrxLifecycleState_name, TrxLifecycleState_value)
	proto.RegisterEnum("dfuse.codecs.deth.TransactionTraceStatus", TransactionTraceStatus_name, TransactionTraceStatus_value)
	proto.RegisterEnum("dfuse.codecs.deth.CallType", CallType_name, CallType_value)
	proto.RegisterType((*Block)(nil), "dfuse.codecs.deth.Block")
	proto.RegisterType((*TransactionRefs)(nil), "dfuse.codecs.deth.TransactionRefs")
	proto.RegisterType((*UnclesHeaders)(nil), "dfuse.codecs.deth.UnclesHeaders")
	proto.RegisterType((*BlockRef)(nil), "dfuse.codecs.deth.BlockRef")
	proto.RegisterType((*BlockHeader)(nil), "dfuse.codecs.deth.BlockHeader")
	proto.RegisterType((*BigInt)(nil), "dfuse.codecs.deth.BigInt")
	proto.RegisterType((*TrxLifecycleTransitionPooled)(nil), "dfuse.codecs.deth.TrxLifecycleTransitionPooled")
	proto.RegisterType((*TrxLifecycleTransitionMined)(nil), "dfuse.codecs.deth.TrxLifecycleTransitionMined")
	proto.RegisterType((*TrxLifecycleTransitionForked)(nil), "dfuse.codecs.deth.TrxLifecycleTransitionForked")
	proto.RegisterType((*TrxLifecycleTransitionConfirmed)(nil), "dfuse.codecs.deth.TrxLifecycleTransitionConfirmed")
	proto.RegisterType((*TrxLifecycleTransitionReplaced)(nil), "dfuse.codecs.deth.TrxLifecycleTransitionReplaced")
	proto.RegisterType((*TransactionLifecycleMessage)(nil), "dfuse.codecs.deth.TransactionLifecycleMessage")
	proto.RegisterType((*Transaction)(nil), "dfuse.codecs.deth.Transaction")
	proto.RegisterType((*TransactionTrace)(nil), "dfuse.codecs.deth.TransactionTrace")
	proto.RegisterType((*TransactionReceipt)(nil), "dfuse.codecs.deth.TransactionReceipt")
	proto.RegisterType((*Log)(nil), "dfuse.codecs.deth.Log")
	proto.RegisterType((*Call)(nil), "dfuse.codecs.deth.Call")
	proto.RegisterMapType((map[string]string)(nil), "dfuse.codecs.deth.Call.KeccakPreimagesEntry")
	proto.RegisterType((*StorageChange)(nil), "dfuse.codecs.deth.StorageChange")
	proto.RegisterType((*BalanceChange)(nil), "dfuse.codecs.deth.BalanceChange")
	proto.RegisterType((*NonceChange)(nil), "dfuse.codecs.deth.NonceChange")
}

func init() { proto.RegisterFile("dfuse/codecs/deth/deth.proto", fileDescriptor_3f10a8911eca0e2c) }

var fileDescriptor_3f10a8911eca0e2c = []byte{
	// 1914 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xdd, 0x6e, 0x23, 0x49,
	0x15, 0x4e, 0xfb, 0x2f, 0xf6, 0xb1, 0x9d, 0x38, 0x45, 0x36, 0xdb, 0x93, 0xec, 0x4c, 0x32, 0xde,
	0x5d, 0x94, 0x19, 0xc0, 0x81, 0x20, 0x45, 0x0b, 0x37, 0x28, 0xb1, 0x9d, 0x89, 0x89, 0xf3, 0xa3,
	0x8a, 0xb3, 0x03, 0x68, 0xa5, 0x56, 0xb9, 0xbb, 0xec, 0xb4, 0xd2, 0xee, 0xb6, 0xba, 0xca, 0x99,
	0x98, 0x77, 0xe0, 0x8e, 0x1b, 0x2e, 0x90, 0x40, 0xe2, 0x9a, 0x07, 0x80, 0x37, 0xe1, 0x19, 0x10,
	0xcf, 0x80, 0xea, 0x54, 0xbb, 0xdd, 0xf1, 0x38, 0x3f, 0x33, 0xe2, 0x62, 0x24, 0xf6, 0xc6, 0xaa,
	0x73, 0xea, 0xab, 0x53, 0xa7, 0xce, 0x5f, 0x9f, 0x63, 0xf8, 0xc2, 0xe9, 0x8d, 0x04, 0xdf, 0xb1,
	0x03, 0x87, 0xdb, 0x62, 0xc7, 0xe1, 0xf2, 0x0a, 0x7f, 0x6a, 0xc3, 0x30, 0x90, 0x01, 0x59, 0xc1,
	0xdd, 0x9a, 0xde, 0xad, 0xa9, 0x8d, 0xf5, 0xcd, 0x7e, 0x10, 0xf4, 0x3d, 0xbe, 0x83, 0x80, 0xee,
	0xa8, 0xb7, 0x23, 0xdd, 0x01, 0x17, 0x92, 0x0d, 0x86, 0xfa, 0x4c, 0xf5, 0xcf, 0x29, 0xc8, 0x1e,
	0x78, 0x81, 0x7d, 0x4d, 0x2a, 0x90, 0xbe, 0xe1, 0xa1, 0x69, 0x6c, 0x19, 0xdb, 0x59, 0xaa, 0x96,
	0x84, 0x40, 0xe6, 0x8a, 0x89, 0x2b, 0x33, 0xb5, 0x65, 0x6c, 0x97, 0x28, 0xae, 0xc9, 0x1a, 0xe4,
	0xfc, 0xd1, 0xa0, 0xcb, 0x43, 0x33, 0xbd, 0x65, 0x6c, 0x67, 0x68, 0x44, 0x29, 0xac, 0x70, 0x7f,
	0xcf, 0xcd, 0x0c, 0x72, 0x71, 0x4d, 0xf6, 0x20, 0x77, 0xc5, 0x99, 0xc3, 0x43, 0x33, 0xbb, 0x65,
	0x6c, 0x17, 0x77, 0x5f, 0xd4, 0xde, 0x53, 0xb0, 0x86, 0x77, 0x1f, 0x21, 0x8a, 0x46, 0x68, 0x75,
	0x6e, 0xe4, 0xdb, 0x1e, 0x17, 0x66, 0x6e, 0x2b, 0xfd, 0x94, 0x73, 0x1a, 0x4d, 0x28, 0x10, 0x19,
	0x32, 0x5f, 0x30, 0x5b, 0xba, 0x81, 0x6f, 0xc9, 0x90, 0xd9, 0x5c, 0x98, 0x80, 0x32, 0xbe, 0x9c,
	0x23, 0xa3, 0x33, 0x05, 0x77, 0x14, 0x96, 0xae, 0xc8, 0x19, 0x8e, 0xa8, 0xbe, 0x82, 0xe5, 0x04,
	0x8c, 0xf2, 0x9e, 0x50, 0x26, 0x50, 0xa6, 0xe0, 0xc2, 0x34, 0xb6, 0xd2, 0xdb, 0x25, 0x1a, 0x51,
	0xd5, 0x37, 0x50, 0xbe, 0x44, 0x45, 0xb4, 0x5a, 0x22, 0xf1, 0x0e, 0xe3, 0x43, 0xde, 0x51, 0xdd,
	0x83, 0x3c, 0xb2, 0x29, 0xef, 0xc5, 0x3e, 0x30, 0xe6, 0xfa, 0x20, 0x95, 0xf4, 0x41, 0xf5, 0x2f,
	0x19, 0x28, 0x26, 0xe4, 0x91, 0x4d, 0x28, 0x0e, 0x59, 0xc8, 0x7d, 0x69, 0x25, 0x44, 0x80, 0x66,
	0x1d, 0x29, 0x41, 0xcf, 0x01, 0xf0, 0x4a, 0x2b, 0xe1, 0xe6, 0x02, 0x72, 0x70, 0x7b, 0x1d, 0xf2,
	0x76, 0xe0, 0xfa, 0x5d, 0x26, 0x38, 0x7a, 0xbb, 0x44, 0x63, 0x5a, 0x1d, 0x15, 0x92, 0x49, 0x6e,
	0x85, 0x41, 0x20, 0xd1, 0xeb, 0x25, 0x5a, 0x40, 0x0e, 0x0d, 0x02, 0x49, 0x7e, 0x04, 0x49, 0x5b,
	0x0a, 0x8d, 0xca, 0x22, 0xaa, 0x92, 0xdc, 0x40, 0xf0, 0x4b, 0x28, 0x85, 0xdc, 0xe6, 0xee, 0x50,
	0x6a, 0x5c, 0x0e, 0x71, 0xc5, 0x88, 0x87, 0x90, 0xe7, 0x00, 0x5e, 0xd0, 0x17, 0x56, 0xd7, 0x0b,
	0x82, 0x81, 0xb9, 0xa8, 0xaf, 0x53, 0x9c, 0x03, 0xc5, 0x20, 0xbf, 0x00, 0x70, 0xdc, 0x5e, 0xcf,
	0xb5, 0x47, 0x9e, 0x1c, 0x9b, 0x79, 0x8c, 0xb6, 0x67, 0xf3, 0xac, 0xed, 0xf6, 0x5b, 0xbe, 0xa4,
	0x09, 0x70, 0xc2, 0x98, 0x85, 0x3b, 0x01, 0xbd, 0x01, 0x85, 0x3e, 0x13, 0x96, 0xe7, 0x0e, 0x5c,
	0x69, 0x02, 0x6e, 0xe5, 0xfb, 0x4c, 0xb4, 0x15, 0x4d, 0x9e, 0x81, 0x5a, 0x5b, 0x23, 0xc1, 0x1d,
	0xb3, 0x88, 0x7b, 0x8b, 0x7d, 0x26, 0x2e, 0x05, 0x77, 0xc8, 0x37, 0x50, 0x88, 0x73, 0xcc, 0x2c,
	0xa1, 0x26, 0xeb, 0x35, 0x9d, 0x85, 0xb5, 0x49, 0x16, 0xd6, 0x3a, 0x13, 0x04, 0x9d, 0x82, 0xd5,
	0x1b, 0xf9, 0xad, 0x0c, 0x99, 0xe5, 0x30, 0xc9, 0xcc, 0xb2, 0x7e, 0x23, 0x72, 0x1a, 0x4c, 0x32,
	0x75, 0xe7, 0xc0, 0xbd, 0xd5, 0xae, 0x5a, 0xc2, 0xcd, 0xc5, 0x81, 0x7b, 0x8b, 0x8e, 0x5a, 0x85,
	0xac, 0x1f, 0xf8, 0x36, 0x37, 0x97, 0x51, 0x17, 0x4d, 0xc4, 0xa1, 0x53, 0x99, 0x86, 0x4e, 0xf5,
	0x05, 0xe4, 0xb4, 0x0d, 0xd4, 0x99, 0xee, 0x58, 0x62, 0x6c, 0xaa, 0x6d, 0x4d, 0x54, 0xff, 0x66,
	0xc0, 0x17, 0x9d, 0xf0, 0xb6, 0xed, 0xf6, 0xb8, 0x3d, 0xb6, 0x3d, 0x8e, 0xb1, 0xef, 0x2a, 0x57,
	0x9d, 0x07, 0x81, 0xc7, 0x1d, 0xb2, 0x0f, 0x05, 0x9f, 0xbf, 0xb3, 0xd0, 0xd3, 0x78, 0x74, 0x69,
	0xf7, 0xab, 0xb9, 0xa9, 0x35, 0x95, 0x71, 0x81, 0x51, 0x91, 0xf7, 0xf9, 0x3b, 0x5c, 0x29, 0x11,
	0x81, 0xe7, 0x44, 0x22, 0x52, 0x1f, 0x22, 0x22, 0xf0, 0x1c, 0x5c, 0x55, 0xff, 0x91, 0x82, 0x8d,
	0xf9, 0x6a, 0x9e, 0xb8, 0xfe, 0xa7, 0xa2, 0xe5, 0x3d, 0xf5, 0x28, 0x8d, 0x31, 0xf1, 0x91, 0xf5,
	0x88, 0xec, 0x43, 0xa9, 0xab, 0x52, 0xdc, 0x8a, 0x2a, 0x6b, 0xe6, 0x49, 0x95, 0xb5, 0xd8, 0x9d,
	0x12, 0xd5, 0x7f, 0xa6, 0xee, 0xf3, 0xf1, 0x61, 0x10, 0x5e, 0x7f, 0x6f, 0xbd, 0x87, 0xad, 0xf7,
	0xc7, 0x14, 0x6c, 0xce, 0xb7, 0x5e, 0x3d, 0xf0, 0x7b, 0x6e, 0x38, 0xf8, 0x64, 0x0c, 0xb8, 0x09,
	0x5a, 0x71, 0xcb, 0xe1, 0x43, 0x79, 0x15, 0x7d, 0xaf, 0x01, 0x59, 0x0d, 0xc5, 0x21, 0xbf, 0x86,
	0x15, 0x65, 0x07, 0xeb, 0x23, 0x4c, 0xb2, 0xac, 0xd0, 0x09, 0x46, 0xf5, 0xdf, 0x06, 0xbc, 0x98,
	0x6f, 0x16, 0xca, 0x87, 0x1e, 0xb3, 0x3f, 0x19, 0xab, 0x34, 0xa0, 0x28, 0xae, 0x98, 0x13, 0xbc,
	0xe3, 0x8e, 0xd5, 0x1d, 0x7f, 0x48, 0x3c, 0xc1, 0xe4, 0xdc, 0xc1, 0xb8, 0xfa, 0x9f, 0xb4, 0x2a,
	0x40, 0x31, 0x20, 0xbe, 0xed, 0x84, 0x0b, 0xc1, 0xfa, 0x9c, 0xfc, 0x14, 0xd2, 0x32, 0xbc, 0xc5,
	0x57, 0xce, 0x37, 0x66, 0xb2, 0xa9, 0x50, 0x50, 0xd2, 0x82, 0xdc, 0x10, 0x4b, 0x6c, 0xa4, 0xd2,
	0xce, 0x23, 0xef, 0x9a, 0xad, 0xcc, 0x47, 0x0b, 0x34, 0x12, 0x40, 0x0e, 0x21, 0x3b, 0x50, 0x65,
	0x30, 0xf2, 0x65, 0xed, 0xc9, 0x92, 0xb0, 0x78, 0x1e, 0x2d, 0x50, 0x7d, 0x5c, 0xa9, 0xd4, 0xc3,
	0x8a, 0x10, 0xf5, 0x6f, 0x4f, 0x57, 0x49, 0x17, 0x12, 0xa5, 0x92, 0x16, 0x40, 0x28, 0x14, 0xec,
	0x49, 0x7a, 0xe0, 0xf7, 0xbd, 0xb8, 0xbb, 0xfb, 0x64, 0x69, 0x71, 0x62, 0x1d, 0x2d, 0xd0, 0xa9,
	0x18, 0x72, 0x06, 0xf9, 0x30, 0x8a, 0x2d, 0xec, 0x08, 0x8a, 0xbb, 0x3f, 0x7b, 0xb2, 0xc8, 0x49,
	0x50, 0x1e, 0x2d, 0xd0, 0x58, 0xc8, 0xc1, 0x3a, 0x98, 0x32, 0xbc, 0xb5, 0xbc, 0x09, 0xdc, 0x92,
	0x31, 0xbe, 0xfa, 0xd7, 0x14, 0x14, 0x13, 0x3e, 0x23, 0x4b, 0x90, 0x92, 0x41, 0xf4, 0xed, 0x4c,
	0xc9, 0x60, 0xfa, 0x09, 0x4e, 0x25, 0x3f, 0xc1, 0x7b, 0xba, 0x89, 0x18, 0x86, 0xae, 0xcd, 0x23,
	0xbf, 0x3e, 0xd0, 0x96, 0xa8, 0x9e, 0xe2, 0x5c, 0x41, 0xef, 0x36, 0x1f, 0x99, 0x99, 0xe6, 0x63,
	0x07, 0xb2, 0x37, 0xcc, 0x1b, 0xf1, 0xc8, 0x2b, 0x0f, 0x08, 0xd4, 0x38, 0xa5, 0x9b, 0xeb, 0x0f,
	0x47, 0x93, 0xc6, 0x4a, 0x13, 0xa4, 0x04, 0xc6, 0x4d, 0xd4, 0x49, 0x19, 0x37, 0x8a, 0x0a, 0xb1,
	0x71, 0x2a, 0x51, 0x23, 0x54, 0x94, 0xc0, 0x7e, 0xa8, 0x44, 0x0d, 0x11, 0x37, 0x12, 0x9f, 0x25,
	0x7a, 0x50, 0x02, 0x99, 0x5e, 0x18, 0x0c, 0xcc, 0x35, 0xcd, 0x53, 0xeb, 0xea, 0xbf, 0xb2, 0x50,
	0x99, 0xcd, 0x9a, 0xff, 0x2b, 0x43, 0x25, 0xdb, 0x42, 0xb8, 0xdb, 0x16, 0xa2, 0x68, 0x87, 0xdf,
	0x9a, 0xab, 0x5b, 0xc6, 0x76, 0x99, 0x6a, 0xe2, 0xa9, 0x96, 0x55, 0xa5, 0x3c, 0xe4, 0x72, 0x14,
	0xfa, 0xba, 0x37, 0xfc, 0x5c, 0x77, 0xf2, 0x9a, 0x85, 0xcd, 0xe1, 0x73, 0x80, 0xe1, 0xa8, 0xeb,
	0xb9, 0xb6, 0x75, 0xcd, 0xc7, 0xa6, 0xa9, 0x7b, 0x47, 0xcd, 0x39, 0xe6, 0x63, 0xb2, 0x0f, 0x39,
	0x55, 0x33, 0x47, 0xc2, 0x7c, 0x81, 0x45, 0xf3, 0xd5, 0x13, 0xea, 0xdd, 0x05, 0x1e, 0xa0, 0xd1,
	0x41, 0xf2, 0x2b, 0x58, 0x8c, 0x1a, 0x72, 0x73, 0x13, 0xcd, 0xf9, 0xf5, 0x23, 0x55, 0x2d, 0xea,
	0xde, 0x27, 0xa7, 0xc8, 0x4f, 0x20, 0x6b, 0x33, 0xcf, 0x13, 0xe6, 0x16, 0x0e, 0x43, 0x9f, 0xcf,
	0x39, 0x5e, 0x67, 0x9e, 0x47, 0x35, 0x8a, 0xb4, 0x60, 0xb9, 0xcb, 0x3c, 0xe6, 0xdb, 0xdc, 0xb2,
	0xaf, 0x98, 0xdf, 0xe7, 0xc2, 0xdc, 0xc6, 0x83, 0x5b, 0xf3, 0xdc, 0xa8, 0x91, 0x75, 0x04, 0xd2,
	0xa5, 0x6e, 0x92, 0x14, 0xa4, 0x0e, 0x65, 0x8c, 0xb2, 0x58, 0xd0, 0xab, 0x7b, 0xc7, 0xb1, 0xd3,
	0x60, 0x2a, 0xa6, 0xe4, 0x4f, 0x09, 0x51, 0xfd, 0xbb, 0x01, 0xe4, 0xfd, 0xe7, 0xcd, 0xcc, 0x41,
	0xc6, 0xec, 0x1c, 0x54, 0x83, 0x1f, 0xd8, 0xa3, 0xc1, 0xc8, 0x63, 0xd2, 0xbd, 0xe1, 0x56, 0x1c,
	0x1c, 0x3a, 0xf6, 0x57, 0xa6, 0x5b, 0x6f, 0xa2, 0x30, 0xb9, 0x3b, 0xe7, 0xa4, 0x67, 0xe7, 0x9c,
	0xd7, 0x90, 0x51, 0x84, 0x99, 0xc1, 0x07, 0xac, 0xcd, 0x79, 0x40, 0x3b, 0xe8, 0x53, 0xc4, 0x54,
	0x19, 0xa4, 0xdb, 0x41, 0x9f, 0x98, 0xb0, 0xc8, 0x1c, 0x27, 0xe4, 0x62, 0xd2, 0xe9, 0x4f, 0x48,
	0x35, 0xf9, 0xc8, 0x60, 0xe8, 0xda, 0xc2, 0x4c, 0xe9, 0x39, 0x56, 0x53, 0x2a, 0x00, 0x31, 0xca,
	0xf4, 0xed, 0xb8, 0x9e, 0x86, 0x6f, 0x26, 0x11, 0xbe, 0xd5, 0x3f, 0x2c, 0x42, 0x46, 0xf9, 0x6c,
	0xba, 0x6d, 0x24, 0xa3, 0xfb, 0x25, 0x94, 0xa2, 0xf9, 0x53, 0x6f, 0xa6, 0x70, 0x33, 0x9a, 0x49,
	0x5b, 0x08, 0x59, 0x85, 0xec, 0xb4, 0x3b, 0x29, 0x53, 0x4d, 0xa8, 0x19, 0x4a, 0x05, 0x81, 0x25,
	0xc7, 0x43, 0xfd, 0x8f, 0xc2, 0xd2, 0xee, 0xc6, 0x3d, 0xe1, 0xd2, 0x19, 0x0f, 0x39, 0xcd, 0xdb,
	0xd1, 0x4a, 0xbd, 0x49, 0xad, 0xa3, 0xbf, 0x1c, 0x4a, 0x34, 0xa2, 0x92, 0x56, 0xc8, 0xdd, 0xb5,
	0x42, 0x5c, 0x24, 0x16, 0x9f, 0x58, 0x24, 0xee, 0x94, 0x9c, 0xfc, 0x4c, 0xc9, 0x79, 0x09, 0x25,
	0xb5, 0x69, 0x07, 0xbe, 0x18, 0xa9, 0x4f, 0x9d, 0x9e, 0x29, 0x8b, 0x7d, 0x26, 0xea, 0x11, 0x4b,
	0xa9, 0xd8, 0x63, 0xae, 0x17, 0x95, 0x88, 0x3c, 0x8d, 0x28, 0xf2, 0x35, 0x2c, 0xa9, 0xd5, 0x28,
	0xe4, 0x56, 0xc8, 0x99, 0x08, 0x7c, 0x9c, 0x2c, 0x0b, 0xb4, 0x1c, 0x71, 0x29, 0x32, 0xd5, 0x50,
	0x1e, 0xf2, 0x1b, 0x1e, 0x4a, 0xee, 0xe0, 0x78, 0x99, 0xa7, 0x31, 0x3d, 0x5b, 0x26, 0xca, 0xef,
	0x95, 0x89, 0xb8, 0xc0, 0x2d, 0x25, 0x0b, 0xdc, 0x97, 0x50, 0xe6, 0xb7, 0xdc, 0x1e, 0x49, 0xee,
	0x58, 0xea, 0xdd, 0x38, 0x46, 0xe6, 0x69, 0x69, 0xc2, 0xac, 0x07, 0x0e, 0x27, 0x6f, 0xa1, 0x72,
	0xcd, 0x6d, 0x9b, 0x5d, 0x5b, 0xc3, 0x90, 0xbb, 0x03, 0xa6, 0xf2, 0x68, 0x15, 0xc3, 0xf0, 0xc7,
	0xf7, 0xb8, 0xa6, 0x76, 0x8c, 0xf8, 0xf3, 0x09, 0xbc, 0xe9, 0xcb, 0x70, 0x4c, 0x97, 0xaf, 0xef,
	0x72, 0x55, 0xa2, 0x0b, 0x19, 0x84, 0xac, 0x3f, 0xcd, 0xcf, 0xcf, 0xee, 0x4d, 0xf4, 0x0b, 0x8d,
	0x9c, 0x24, 0xba, 0x48, 0x92, 0x73, 0x6b, 0xc6, 0xda, 0xff, 0xaa, 0x66, 0x98, 0x1f, 0x5e, 0x33,
	0xe2, 0x74, 0x7d, 0xf6, 0x78, 0xba, 0xae, 0x1f, 0xc0, 0xea, 0x3c, 0x7b, 0x91, 0x0a, 0xa4, 0x55,
	0x49, 0x37, 0x30, 0x16, 0xd4, 0x52, 0x39, 0x51, 0x47, 0x6c, 0x0a, 0x79, 0x9a, 0xf8, 0x65, 0xea,
	0x1b, 0xa3, 0x3a, 0x82, 0xf2, 0x1d, 0x03, 0x3d, 0x90, 0xfc, 0x91, 0x58, 0xfd, 0x9f, 0x0f, 0x8a,
	0xdd, 0xd0, 0xbd, 0xb5, 0x16, 0x1d, 0xfd, 0xdd, 0x13, 0x78, 0xce, 0xb7, 0x93, 0xa0, 0x57, 0xbd,
	0xbb, 0xde, 0xd4, 0xff, 0xf6, 0xa8, 0xae, 0x1c, 0x37, 0xab, 0x7f, 0x32, 0xa0, 0x7c, 0xc7, 0x9a,
	0x0f, 0xdc, 0xbb, 0x97, 0xbc, 0x25, 0xf5, 0xe8, 0x87, 0x3e, 0x56, 0x60, 0x2f, 0xa9, 0xc0, 0xe3,
	0x0d, 0x42, 0xac, 0x1b, 0x83, 0x62, 0xc2, 0x3f, 0x0f, 0x28, 0xb6, 0x31, 0xab, 0x58, 0xe6, 0xbe,
	0xe7, 0xeb, 0x41, 0x2a, 0xbe, 0xe2, 0xf5, 0x77, 0xb0, 0x3e, 0xbf, 0xc9, 0xc4, 0x8a, 0x04, 0x90,
	0x3b, 0x3f, 0x3b, 0x6b, 0x37, 0x1b, 0x95, 0x05, 0x52, 0x80, 0xec, 0x49, 0xeb, 0xb4, 0xd9, 0xa8,
	0x18, 0x8a, 0x7d, 0x78, 0x46, 0x8f, 0x9b, 0x8d, 0x4a, 0x8a, 0x94, 0xa1, 0x50, 0x3f, 0x3b, 0x3d,
	0x6c, 0xd1, 0x93, 0x66, 0xa3, 0x92, 0x26, 0x25, 0xc8, 0xd3, 0xe6, 0x79, 0x7b, 0xbf, 0xde, 0x6c,
	0x54, 0x32, 0xaf, 0xbf, 0x83, 0x95, 0xf7, 0xc6, 0x19, 0xb2, 0x0c, 0xc5, 0x0e, 0xfd, 0x8d, 0x75,
	0x79, 0x7a, 0x7c, 0x7a, 0xf6, 0xf6, 0xb4, 0xb2, 0x40, 0x08, 0x2c, 0x29, 0x46, 0xeb, 0xd4, 0x3a,
	0x69, 0x9e, 0xa8, 0xfb, 0x2a, 0x06, 0xa9, 0x40, 0x29, 0xe2, 0x1d, 0xb4, 0xcf, 0xea, 0xc7, 0x95,
	0xd4, 0x84, 0x73, 0x71, 0xb4, 0xdf, 0x38, 0x7b, 0xab, 0xee, 0x7a, 0x7d, 0x0a, 0x6b, 0xf3, 0xbf,
	0xfb, 0xa4, 0x08, 0x8b, 0x53, 0xf1, 0x65, 0x28, 0x5c, 0x5c, 0xd6, 0xeb, 0xcd, 0x66, 0x23, 0x56,
	0x7e, 0xbf, 0xd5, 0x46, 0xe5, 0x51, 0xdb, 0x6f, 0x9b, 0xb4, 0x83, 0xf2, 0x7e, 0x0b, 0xf9, 0x49,
	0x55, 0x56, 0x4a, 0x5e, 0x9e, 0x5e, 0x9c, 0x37, 0xeb, 0xad, 0xc3, 0x16, 0x3e, 0x3f, 0x0f, 0x99,
	0xfa, 0x7e, 0x5b, 0xa9, 0x56, 0x82, 0xbc, 0x5a, 0xd5, 0xcf, 0x1a, 0x4d, 0x2d, 0xa2, 0xd1, 0x6c,
	0x37, 0xdf, 0xec, 0x77, 0x9a, 0x95, 0xb4, 0x12, 0x7e, 0xd1, 0xd9, 0xef, 0xb4, 0xea, 0x95, 0x8c,
	0x5a, 0xd7, 0x69, 0x53, 0xf1, 0xb3, 0x07, 0x3f, 0xfc, 0xdd, 0x57, 0x7d, 0x57, 0x5e, 0x8d, 0xba,
	0x35, 0x3b, 0x18, 0xec, 0xf0, 0x40, 0xd8, 0xcc, 0x67, 0x0e, 0xdb, 0xe9, 0x0a, 0x19, 0x72, 0x36,
	0xd8, 0x19, 0x76, 0xf1, 0xbf, 0xf0, 0x6e, 0x0e, 0xff, 0x65, 0xfb, 0xf9, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xe3, 0x2f, 0xef, 0x74, 0x2c, 0x17, 0x00, 0x00,
}
