// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/codecs/deth/deth.proto

package deth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionTraceStatus int32

const (
	TransactionTraceStatus_UNKNOWN   TransactionTraceStatus = 0
	TransactionTraceStatus_SUCCEEDED TransactionTraceStatus = 1
	TransactionTraceStatus_FAILED    TransactionTraceStatus = 2
	TransactionTraceStatus_REVERTED  TransactionTraceStatus = 3
)

var TransactionTraceStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCEEDED",
	2: "FAILED",
	3: "REVERTED",
}

var TransactionTraceStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"SUCCEEDED": 1,
	"FAILED":    2,
	"REVERTED":  3,
}

func (x TransactionTraceStatus) String() string {
	return proto.EnumName(TransactionTraceStatus_name, int32(x))
}

func (TransactionTraceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{0}
}

type CallType int32

const (
	CallType_UNSPECIFIED CallType = 0
	CallType_CALL        CallType = 1
	CallType_CALLCODE    CallType = 2
	CallType_DELEGATE    CallType = 3
	CallType_STATIC      CallType = 4
	CallType_CREATE      CallType = 5
)

var CallType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "CALL",
	2: "CALLCODE",
	3: "DELEGATE",
	4: "STATIC",
	5: "CREATE",
}

var CallType_value = map[string]int32{
	"UNSPECIFIED": 0,
	"CALL":        1,
	"CALLCODE":    2,
	"DELEGATE":    3,
	"STATIC":      4,
	"CREATE":      5,
}

func (x CallType) String() string {
	return proto.EnumName(CallType_name, int32(x))
}

func (CallType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{1}
}

type Block struct {
	Ver                  int32               `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Hash                 []byte              `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               uint64              `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Size                 uint64              `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Header               *BlockHeader        `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Uncles               []*BlockHeader      `protobuf:"bytes,6,rep,name=uncles,proto3" json:"uncles,omitempty"`
	TransactionTraces    []*TransactionTrace `protobuf:"bytes,10,rep,name=transaction_traces,json=transactionTraces,proto3" json:"transaction_traces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetUncles() []*BlockHeader {
	if m != nil {
		return m.Uncles
	}
	return nil
}

func (m *Block) GetTransactionTraces() []*TransactionTrace {
	if m != nil {
		return m.TransactionTraces
	}
	return nil
}

type TransactionRefs struct {
	Hashes               [][]byte `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRefs) Reset()         { *m = TransactionRefs{} }
func (m *TransactionRefs) String() string { return proto.CompactTextString(m) }
func (*TransactionRefs) ProtoMessage()    {}
func (*TransactionRefs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{1}
}

func (m *TransactionRefs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRefs.Unmarshal(m, b)
}
func (m *TransactionRefs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRefs.Marshal(b, m, deterministic)
}
func (m *TransactionRefs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRefs.Merge(m, src)
}
func (m *TransactionRefs) XXX_Size() int {
	return xxx_messageInfo_TransactionRefs.Size(m)
}
func (m *TransactionRefs) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRefs.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRefs proto.InternalMessageInfo

func (m *TransactionRefs) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type UnclesHeaders struct {
	Uncles               []*BlockHeader `protobuf:"bytes,1,rep,name=uncles,proto3" json:"uncles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UnclesHeaders) Reset()         { *m = UnclesHeaders{} }
func (m *UnclesHeaders) String() string { return proto.CompactTextString(m) }
func (*UnclesHeaders) ProtoMessage()    {}
func (*UnclesHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{2}
}

func (m *UnclesHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnclesHeaders.Unmarshal(m, b)
}
func (m *UnclesHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnclesHeaders.Marshal(b, m, deterministic)
}
func (m *UnclesHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnclesHeaders.Merge(m, src)
}
func (m *UnclesHeaders) XXX_Size() int {
	return xxx_messageInfo_UnclesHeaders.Size(m)
}
func (m *UnclesHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_UnclesHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_UnclesHeaders proto.InternalMessageInfo

func (m *UnclesHeaders) GetUncles() []*BlockHeader {
	if m != nil {
		return m.Uncles
	}
	return nil
}

type BlockRef struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               uint64   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRef) Reset()         { *m = BlockRef{} }
func (m *BlockRef) String() string { return proto.CompactTextString(m) }
func (*BlockRef) ProtoMessage()    {}
func (*BlockRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{3}
}

func (m *BlockRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRef.Unmarshal(m, b)
}
func (m *BlockRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRef.Marshal(b, m, deterministic)
}
func (m *BlockRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRef.Merge(m, src)
}
func (m *BlockRef) XXX_Size() int {
	return xxx_messageInfo_BlockRef.Size(m)
}
func (m *BlockRef) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRef.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRef proto.InternalMessageInfo

func (m *BlockRef) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockRef) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type BlockHeader struct {
	ParentHash           []byte               `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	UncleHash            []byte               `protobuf:"bytes,2,opt,name=uncle_hash,json=uncleHash,proto3" json:"uncle_hash,omitempty"`
	Coinbase             []byte               `protobuf:"bytes,3,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	StateRoot            []byte               `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	TransactionsRoot     []byte               `protobuf:"bytes,5,opt,name=transactions_root,json=transactionsRoot,proto3" json:"transactions_root,omitempty"`
	ReceiptRoot          []byte               `protobuf:"bytes,6,opt,name=receipt_root,json=receiptRoot,proto3" json:"receipt_root,omitempty"`
	LogsBloom            []byte               `protobuf:"bytes,7,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	Difficulty           *BigInt              `protobuf:"bytes,8,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Number               uint64               `protobuf:"varint,9,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit             uint64               `protobuf:"varint,10,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed              uint64               `protobuf:"varint,11,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData            []byte               `protobuf:"bytes,13,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	MixHash              []byte               `protobuf:"bytes,14,opt,name=mix_hash,json=mixHash,proto3" json:"mix_hash,omitempty"`
	Nonce                uint64               `protobuf:"varint,15,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Hash                 []byte               `protobuf:"bytes,16,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{4}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetUncleHash() []byte {
	if m != nil {
		return m.UncleHash
	}
	return nil
}

func (m *BlockHeader) GetCoinbase() []byte {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *BlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeader) GetTransactionsRoot() []byte {
	if m != nil {
		return m.TransactionsRoot
	}
	return nil
}

func (m *BlockHeader) GetReceiptRoot() []byte {
	if m != nil {
		return m.ReceiptRoot
	}
	return nil
}

func (m *BlockHeader) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *BlockHeader) GetDifficulty() *BigInt {
	if m != nil {
		return m.Difficulty
	}
	return nil
}

func (m *BlockHeader) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockHeader) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *BlockHeader) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BlockHeader) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *BlockHeader) GetMixHash() []byte {
	if m != nil {
		return m.MixHash
	}
	return nil
}

func (m *BlockHeader) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BigInt struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigInt) Reset()         { *m = BigInt{} }
func (m *BigInt) String() string { return proto.CompactTextString(m) }
func (*BigInt) ProtoMessage()    {}
func (*BigInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{5}
}

func (m *BigInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigInt.Unmarshal(m, b)
}
func (m *BigInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigInt.Marshal(b, m, deterministic)
}
func (m *BigInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigInt.Merge(m, src)
}
func (m *BigInt) XXX_Size() int {
	return xxx_messageInfo_BigInt.Size(m)
}
func (m *BigInt) XXX_DiscardUnknown() {
	xxx_messageInfo_BigInt.DiscardUnknown(m)
}

var xxx_messageInfo_BigInt proto.InternalMessageInfo

func (m *BigInt) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type TransactionTrace struct {
	// consensus
	To       []byte  `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Nonce    uint64  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasPrice *BigInt `protobuf:"bytes,3,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit uint64  `protobuf:"varint,4,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Value    *BigInt `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Input    []byte  `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	V        []byte  `protobuf:"bytes,7,opt,name=v,proto3" json:"v,omitempty"`
	R        []byte  `protobuf:"bytes,8,opt,name=r,proto3" json:"r,omitempty"`
	S        []byte  `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	GasUsed  uint64  `protobuf:"varint,10,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// meta
	Index                uint32                 `protobuf:"varint,20,opt,name=index,proto3" json:"index,omitempty"`
	Hash                 []byte                 `protobuf:"bytes,21,opt,name=hash,proto3" json:"hash,omitempty"`
	From                 []byte                 `protobuf:"bytes,22,opt,name=from,proto3" json:"from,omitempty"`
	ReturnData           []byte                 `protobuf:"bytes,23,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	PublicKey            []byte                 `protobuf:"bytes,24,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status               TransactionTraceStatus `protobuf:"varint,30,opt,name=status,proto3,enum=dfuse.codecs.deth.TransactionTraceStatus" json:"status,omitempty"`
	Receipt              *TransactionReceipt    `protobuf:"bytes,31,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Calls                []*Call                `protobuf:"bytes,32,rep,name=calls,proto3" json:"calls,omitempty"`
	BalanceChanges       []*BalanceChange       `protobuf:"bytes,40,rep,name=balance_changes,json=balanceChanges,proto3" json:"balance_changes,omitempty"`
	NonceChanges         []*NonceChange         `protobuf:"bytes,41,rep,name=nonce_changes,json=nonceChanges,proto3" json:"nonce_changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TransactionTrace) Reset()         { *m = TransactionTrace{} }
func (m *TransactionTrace) String() string { return proto.CompactTextString(m) }
func (*TransactionTrace) ProtoMessage()    {}
func (*TransactionTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{6}
}

func (m *TransactionTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionTrace.Unmarshal(m, b)
}
func (m *TransactionTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionTrace.Marshal(b, m, deterministic)
}
func (m *TransactionTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionTrace.Merge(m, src)
}
func (m *TransactionTrace) XXX_Size() int {
	return xxx_messageInfo_TransactionTrace.Size(m)
}
func (m *TransactionTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionTrace.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionTrace proto.InternalMessageInfo

func (m *TransactionTrace) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransactionTrace) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionTrace) GetGasPrice() *BigInt {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *TransactionTrace) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *TransactionTrace) GetValue() *BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TransactionTrace) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *TransactionTrace) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *TransactionTrace) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *TransactionTrace) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *TransactionTrace) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *TransactionTrace) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TransactionTrace) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *TransactionTrace) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransactionTrace) GetReturnData() []byte {
	if m != nil {
		return m.ReturnData
	}
	return nil
}

func (m *TransactionTrace) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *TransactionTrace) GetStatus() TransactionTraceStatus {
	if m != nil {
		return m.Status
	}
	return TransactionTraceStatus_UNKNOWN
}

func (m *TransactionTrace) GetReceipt() *TransactionReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *TransactionTrace) GetCalls() []*Call {
	if m != nil {
		return m.Calls
	}
	return nil
}

func (m *TransactionTrace) GetBalanceChanges() []*BalanceChange {
	if m != nil {
		return m.BalanceChanges
	}
	return nil
}

func (m *TransactionTrace) GetNonceChanges() []*NonceChange {
	if m != nil {
		return m.NonceChanges
	}
	return nil
}

type TransactionReceipt struct {
	// consensus
	StateRoot            []byte   `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	CumulativeGasUsed    uint64   `protobuf:"varint,2,opt,name=cumulative_gas_used,json=cumulativeGasUsed,proto3" json:"cumulative_gas_used,omitempty"`
	LogsBloom            []byte   `protobuf:"bytes,3,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionReceipt) Reset()         { *m = TransactionReceipt{} }
func (m *TransactionReceipt) String() string { return proto.CompactTextString(m) }
func (*TransactionReceipt) ProtoMessage()    {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{7}
}

func (m *TransactionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReceipt.Unmarshal(m, b)
}
func (m *TransactionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReceipt.Marshal(b, m, deterministic)
}
func (m *TransactionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReceipt.Merge(m, src)
}
func (m *TransactionReceipt) XXX_Size() int {
	return xxx_messageInfo_TransactionReceipt.Size(m)
}
func (m *TransactionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReceipt proto.InternalMessageInfo

func (m *TransactionReceipt) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *TransactionReceipt) GetCumulativeGasUsed() uint64 {
	if m != nil {
		return m.CumulativeGasUsed
	}
	return 0
}

func (m *TransactionReceipt) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *TransactionReceipt) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Log struct {
	// consensus
	Address []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics  [][]byte `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data    []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// supplement
	Index                uint32   `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{8}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Log) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *Log) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Log) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Call struct {
	Index                uint32            `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ParentIndex          uint32            `protobuf:"varint,2,opt,name=parent_index,json=parentIndex,proto3" json:"parent_index,omitempty"`
	Depth                uint32            `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	CallType             CallType          `protobuf:"varint,4,opt,name=call_type,json=callType,proto3,enum=dfuse.codecs.deth.CallType" json:"call_type,omitempty"`
	Caller               []byte            `protobuf:"bytes,5,opt,name=caller,proto3" json:"caller,omitempty"`
	Address              []byte            `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Value                *BigInt           `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	GasLimit             uint64            `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasConsumed          uint64            `protobuf:"varint,9,opt,name=gas_consumed,json=gasConsumed,proto3" json:"gas_consumed,omitempty"`
	Failed               bool              `protobuf:"varint,10,opt,name=failed,proto3" json:"failed,omitempty"`
	FailureReason        string            `protobuf:"bytes,11,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	Reverted             bool              `protobuf:"varint,12,opt,name=reverted,proto3" json:"reverted,omitempty"`
	ReturnData           []byte            `protobuf:"bytes,13,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	Input                []byte            `protobuf:"bytes,14,opt,name=input,proto3" json:"input,omitempty"`
	ExecutedCode         bool              `protobuf:"varint,15,opt,name=executed_code,json=executedCode,proto3" json:"executed_code,omitempty"`
	KeccakPreimages      map[string]string `protobuf:"bytes,20,rep,name=keccak_preimages,json=keccakPreimages,proto3" json:"keccak_preimages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StorageChanges       []*StorageChange  `protobuf:"bytes,21,rep,name=storage_changes,json=storageChanges,proto3" json:"storage_changes,omitempty"`
	BalanceChanges       []*BalanceChange  `protobuf:"bytes,22,rep,name=balance_changes,json=balanceChanges,proto3" json:"balance_changes,omitempty"`
	NonceChanges         []*NonceChange    `protobuf:"bytes,24,rep,name=nonce_changes,json=nonceChanges,proto3" json:"nonce_changes,omitempty"`
	Logs                 []*Log            `protobuf:"bytes,25,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{9}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Call) GetParentIndex() uint32 {
	if m != nil {
		return m.ParentIndex
	}
	return 0
}

func (m *Call) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *Call) GetCallType() CallType {
	if m != nil {
		return m.CallType
	}
	return CallType_UNSPECIFIED
}

func (m *Call) GetCaller() []byte {
	if m != nil {
		return m.Caller
	}
	return nil
}

func (m *Call) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Call) GetValue() *BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Call) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Call) GetGasConsumed() uint64 {
	if m != nil {
		return m.GasConsumed
	}
	return 0
}

func (m *Call) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *Call) GetFailureReason() string {
	if m != nil {
		return m.FailureReason
	}
	return ""
}

func (m *Call) GetReverted() bool {
	if m != nil {
		return m.Reverted
	}
	return false
}

func (m *Call) GetReturnData() []byte {
	if m != nil {
		return m.ReturnData
	}
	return nil
}

func (m *Call) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Call) GetExecutedCode() bool {
	if m != nil {
		return m.ExecutedCode
	}
	return false
}

func (m *Call) GetKeccakPreimages() map[string]string {
	if m != nil {
		return m.KeccakPreimages
	}
	return nil
}

func (m *Call) GetStorageChanges() []*StorageChange {
	if m != nil {
		return m.StorageChanges
	}
	return nil
}

func (m *Call) GetBalanceChanges() []*BalanceChange {
	if m != nil {
		return m.BalanceChanges
	}
	return nil
}

func (m *Call) GetNonceChanges() []*NonceChange {
	if m != nil {
		return m.NonceChanges
	}
	return nil
}

func (m *Call) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type StorageChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	OldValue             []byte   `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             []byte   `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageChange) Reset()         { *m = StorageChange{} }
func (m *StorageChange) String() string { return proto.CompactTextString(m) }
func (*StorageChange) ProtoMessage()    {}
func (*StorageChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{10}
}

func (m *StorageChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageChange.Unmarshal(m, b)
}
func (m *StorageChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageChange.Marshal(b, m, deterministic)
}
func (m *StorageChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageChange.Merge(m, src)
}
func (m *StorageChange) XXX_Size() int {
	return xxx_messageInfo_StorageChange.Size(m)
}
func (m *StorageChange) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageChange.DiscardUnknown(m)
}

var xxx_messageInfo_StorageChange proto.InternalMessageInfo

func (m *StorageChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *StorageChange) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *StorageChange) GetOldValue() []byte {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *StorageChange) GetNewValue() []byte {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type BalanceChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldValue             *BigInt  `protobuf:"bytes,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             *BigInt  `protobuf:"bytes,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceChange) Reset()         { *m = BalanceChange{} }
func (m *BalanceChange) String() string { return proto.CompactTextString(m) }
func (*BalanceChange) ProtoMessage()    {}
func (*BalanceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{11}
}

func (m *BalanceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceChange.Unmarshal(m, b)
}
func (m *BalanceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceChange.Marshal(b, m, deterministic)
}
func (m *BalanceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceChange.Merge(m, src)
}
func (m *BalanceChange) XXX_Size() int {
	return xxx_messageInfo_BalanceChange.Size(m)
}
func (m *BalanceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceChange.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceChange proto.InternalMessageInfo

func (m *BalanceChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BalanceChange) GetOldValue() *BigInt {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *BalanceChange) GetNewValue() *BigInt {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type NonceChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldValue             uint64   `protobuf:"varint,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             uint64   `protobuf:"varint,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonceChange) Reset()         { *m = NonceChange{} }
func (m *NonceChange) String() string { return proto.CompactTextString(m) }
func (*NonceChange) ProtoMessage()    {}
func (*NonceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{12}
}

func (m *NonceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonceChange.Unmarshal(m, b)
}
func (m *NonceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonceChange.Marshal(b, m, deterministic)
}
func (m *NonceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceChange.Merge(m, src)
}
func (m *NonceChange) XXX_Size() int {
	return xxx_messageInfo_NonceChange.Size(m)
}
func (m *NonceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceChange.DiscardUnknown(m)
}

var xxx_messageInfo_NonceChange proto.InternalMessageInfo

func (m *NonceChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *NonceChange) GetOldValue() uint64 {
	if m != nil {
		return m.OldValue
	}
	return 0
}

func (m *NonceChange) GetNewValue() uint64 {
	if m != nil {
		return m.NewValue
	}
	return 0
}

func init() {
	proto.RegisterEnum("dfuse.codecs.deth.TransactionTraceStatus", TransactionTraceStatus_name, TransactionTraceStatus_value)
	proto.RegisterEnum("dfuse.codecs.deth.CallType", CallType_name, CallType_value)
	proto.RegisterType((*Block)(nil), "dfuse.codecs.deth.Block")
	proto.RegisterType((*TransactionRefs)(nil), "dfuse.codecs.deth.TransactionRefs")
	proto.RegisterType((*UnclesHeaders)(nil), "dfuse.codecs.deth.UnclesHeaders")
	proto.RegisterType((*BlockRef)(nil), "dfuse.codecs.deth.BlockRef")
	proto.RegisterType((*BlockHeader)(nil), "dfuse.codecs.deth.BlockHeader")
	proto.RegisterType((*BigInt)(nil), "dfuse.codecs.deth.BigInt")
	proto.RegisterType((*TransactionTrace)(nil), "dfuse.codecs.deth.TransactionTrace")
	proto.RegisterType((*TransactionReceipt)(nil), "dfuse.codecs.deth.TransactionReceipt")
	proto.RegisterType((*Log)(nil), "dfuse.codecs.deth.Log")
	proto.RegisterType((*Call)(nil), "dfuse.codecs.deth.Call")
	proto.RegisterMapType((map[string]string)(nil), "dfuse.codecs.deth.Call.KeccakPreimagesEntry")
	proto.RegisterType((*StorageChange)(nil), "dfuse.codecs.deth.StorageChange")
	proto.RegisterType((*BalanceChange)(nil), "dfuse.codecs.deth.BalanceChange")
	proto.RegisterType((*NonceChange)(nil), "dfuse.codecs.deth.NonceChange")
}

func init() { proto.RegisterFile("dfuse/codecs/deth/deth.proto", fileDescriptor_3f10a8911eca0e2c) }

var fileDescriptor_3f10a8911eca0e2c = []byte{
	// 1457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0x1b, 0xb7,
	0x12, 0xce, 0xea, 0x5f, 0x23, 0xc9, 0x56, 0x78, 0x1c, 0x67, 0x63, 0x9f, 0x24, 0x8a, 0x72, 0x72,
	0xa0, 0xa4, 0xad, 0x04, 0xa4, 0x80, 0x91, 0xf6, 0xa6, 0xb0, 0x25, 0x25, 0x31, 0x62, 0x38, 0x01,
	0x2d, 0x27, 0x68, 0x6f, 0x16, 0xd4, 0x2e, 0x25, 0x2f, 0xbc, 0x5a, 0x0a, 0x4b, 0xae, 0x63, 0xf7,
	0x1d, 0xfa, 0x00, 0xbd, 0x28, 0xd0, 0x27, 0xe8, 0x03, 0xf5, 0x69, 0x0a, 0x0e, 0x57, 0xd2, 0x4a,
	0x91, 0x9d, 0x04, 0xe8, 0x8d, 0xc0, 0x99, 0xf9, 0x38, 0x1c, 0xce, 0xcf, 0xc7, 0x15, 0xfc, 0xd7,
	0x1b, 0xc5, 0x92, 0x77, 0x5c, 0xe1, 0x71, 0x57, 0x76, 0x3c, 0xae, 0xce, 0xf0, 0xa7, 0x3d, 0x8d,
	0x84, 0x12, 0xe4, 0x36, 0x5a, 0xdb, 0xc6, 0xda, 0xd6, 0x86, 0x9d, 0x87, 0x63, 0x21, 0xc6, 0x01,
	0xef, 0x20, 0x60, 0x18, 0x8f, 0x3a, 0xca, 0x9f, 0x70, 0xa9, 0xd8, 0x64, 0x6a, 0xf6, 0x34, 0xff,
	0xc8, 0x40, 0xfe, 0x20, 0x10, 0xee, 0x39, 0xa9, 0x43, 0xf6, 0x82, 0x47, 0xb6, 0xd5, 0xb0, 0x5a,
	0x79, 0xaa, 0x97, 0x84, 0x40, 0xee, 0x8c, 0xc9, 0x33, 0x3b, 0xd3, 0xb0, 0x5a, 0x55, 0x8a, 0x6b,
	0xb2, 0x0d, 0x85, 0x30, 0x9e, 0x0c, 0x79, 0x64, 0x67, 0x1b, 0x56, 0x2b, 0x47, 0x13, 0x49, 0x63,
	0xa5, 0xff, 0x2b, 0xb7, 0x73, 0xa8, 0xc5, 0x35, 0xd9, 0x83, 0xc2, 0x19, 0x67, 0x1e, 0x8f, 0xec,
	0x7c, 0xc3, 0x6a, 0x55, 0x9e, 0x3f, 0x68, 0x7f, 0x12, 0x60, 0x1b, 0xcf, 0x7e, 0x8d, 0x28, 0x9a,
	0xa0, 0xf5, 0xbe, 0x38, 0x74, 0x03, 0x2e, 0xed, 0x42, 0x23, 0xfb, 0x25, 0xfb, 0x0c, 0x9a, 0x50,
	0x20, 0x2a, 0x62, 0xa1, 0x64, 0xae, 0xf2, 0x45, 0xe8, 0xa8, 0x88, 0xb9, 0x5c, 0xda, 0x80, 0x3e,
	0x1e, 0xaf, 0xf1, 0x31, 0x58, 0x80, 0x07, 0x1a, 0x4b, 0x6f, 0xab, 0x15, 0x8d, 0x6c, 0x3e, 0x85,
	0xcd, 0x14, 0x8c, 0xf2, 0x91, 0xd4, 0x29, 0xd0, 0xa9, 0xe0, 0xd2, 0xb6, 0x1a, 0xd9, 0x56, 0x95,
	0x26, 0x52, 0xf3, 0x15, 0xd4, 0x4e, 0x31, 0x10, 0x13, 0x96, 0x4c, 0xdd, 0xc3, 0xfa, 0x9a, 0x7b,
	0x34, 0xf7, 0xa0, 0x84, 0x6a, 0xca, 0x47, 0xf3, 0x1a, 0x58, 0x6b, 0x6b, 0x90, 0x49, 0xd7, 0xa0,
	0xf9, 0x67, 0x0e, 0x2a, 0x29, 0x7f, 0xe4, 0x21, 0x54, 0xa6, 0x2c, 0xe2, 0xa1, 0x72, 0x52, 0x2e,
	0xc0, 0xa8, 0x5e, 0x6b, 0x47, 0xf7, 0x01, 0xf0, 0x48, 0x27, 0x55, 0xe6, 0x32, 0x6a, 0xd0, 0xbc,
	0x03, 0x25, 0x57, 0xf8, 0xe1, 0x90, 0x49, 0x8e, 0xd5, 0xae, 0xd2, 0xb9, 0xac, 0xb7, 0x4a, 0xc5,
	0x14, 0x77, 0x22, 0x21, 0x14, 0x56, 0xbd, 0x4a, 0xcb, 0xa8, 0xa1, 0x42, 0x28, 0xf2, 0x0d, 0xa4,
	0x73, 0x29, 0x0d, 0x2a, 0x8f, 0xa8, 0x7a, 0xda, 0x80, 0xe0, 0x47, 0x50, 0x8d, 0xb8, 0xcb, 0xfd,
	0xa9, 0x32, 0xb8, 0x02, 0xe2, 0x2a, 0x89, 0x0e, 0x21, 0xf7, 0x01, 0x02, 0x31, 0x96, 0xce, 0x30,
	0x10, 0x62, 0x62, 0x17, 0xcd, 0x71, 0x5a, 0x73, 0xa0, 0x15, 0xe4, 0x07, 0x00, 0xcf, 0x1f, 0x8d,
	0x7c, 0x37, 0x0e, 0xd4, 0x95, 0x5d, 0xc2, 0x6e, 0xbb, 0xb7, 0x2e, 0xdb, 0xfe, 0xf8, 0x30, 0x54,
	0x34, 0x05, 0x4e, 0x25, 0xb3, 0xbc, 0xd4, 0xd0, 0xbb, 0x50, 0x1e, 0x33, 0xe9, 0x04, 0xfe, 0xc4,
	0x57, 0x36, 0xa0, 0xa9, 0x34, 0x66, 0xf2, 0x48, 0xcb, 0xe4, 0x1e, 0xe8, 0xb5, 0x13, 0x4b, 0xee,
	0xd9, 0x15, 0xb4, 0x15, 0xc7, 0x4c, 0x9e, 0x4a, 0xee, 0x91, 0x17, 0x50, 0x9e, 0xcf, 0x98, 0x5d,
	0xc5, 0x48, 0x76, 0xda, 0x66, 0x0a, 0xdb, 0xb3, 0x29, 0x6c, 0x0f, 0x66, 0x08, 0xba, 0x00, 0xeb,
	0x3b, 0xf2, 0x4b, 0x15, 0x31, 0xc7, 0x63, 0x8a, 0xd9, 0x35, 0x73, 0x47, 0xd4, 0xf4, 0x98, 0x62,
	0xfa, 0xcc, 0x89, 0x7f, 0x69, 0x4a, 0xb5, 0x81, 0xc6, 0xe2, 0xc4, 0xbf, 0xc4, 0x42, 0x6d, 0x41,
	0x3e, 0x14, 0xa1, 0xcb, 0xed, 0x4d, 0x8c, 0xc5, 0x08, 0xf3, 0xd6, 0xa9, 0x2f, 0x5a, 0xa7, 0xf9,
	0x00, 0x0a, 0x26, 0x07, 0x7a, 0xcf, 0xf0, 0x4a, 0x61, 0x6f, 0x6a, 0xb3, 0x11, 0x9a, 0x7f, 0xe7,
	0xa1, 0xbe, 0x3a, 0x16, 0x64, 0x03, 0x32, 0x4a, 0x24, 0xb8, 0x8c, 0x12, 0x8b, 0xe3, 0x32, 0xe9,
	0xe3, 0xf6, 0x4c, 0xc2, 0xa6, 0x91, 0xef, 0x9a, 0x76, 0xb9, 0xb1, 0x04, 0x3a, 0x7f, 0xef, 0x34,
	0x74, 0x39, 0xd1, 0xb9, 0x95, 0x44, 0x77, 0x20, 0x7f, 0xc1, 0x82, 0x98, 0x27, 0x0c, 0x72, 0x83,
	0x43, 0x83, 0xd3, 0xb1, 0xf9, 0xe1, 0x34, 0x9e, 0x35, 0x91, 0x11, 0x48, 0x15, 0xac, 0x8b, 0xa4,
	0x6b, 0xac, 0x0b, 0x2d, 0x45, 0xd8, 0x24, 0x55, 0x6a, 0x45, 0x5a, 0x92, 0x58, 0xfb, 0x2a, 0xb5,
	0xe4, 0x52, 0x65, 0x61, 0xb9, 0xb2, 0xe8, 0xda, 0xe3, 0x97, 0xf6, 0x56, 0xc3, 0x6a, 0xd5, 0xa8,
	0x11, 0xe6, 0x59, 0xbe, 0x93, 0x1a, 0x50, 0x02, 0xb9, 0x51, 0x24, 0x26, 0xf6, 0xb6, 0xd1, 0xe9,
	0xb5, 0x1e, 0xc6, 0x88, 0xab, 0x38, 0x0a, 0x4d, 0x79, 0xef, 0x9a, 0x61, 0x34, 0x2a, 0xac, 0xef,
	0x7d, 0x80, 0x69, 0x3c, 0x0c, 0x7c, 0xd7, 0x39, 0xe7, 0x57, 0xb6, 0x6d, 0xca, 0x6f, 0x34, 0x6f,
	0xf8, 0x15, 0xd9, 0x87, 0x82, 0x1e, 0xaf, 0x58, 0xda, 0x0f, 0x1a, 0x56, 0x6b, 0xe3, 0xf9, 0xd3,
	0x2f, 0x20, 0xb4, 0x13, 0xdc, 0x40, 0x93, 0x8d, 0xe4, 0x27, 0x28, 0x26, 0x33, 0x65, 0x3f, 0xc4,
	0x74, 0x3e, 0xb9, 0xd9, 0x07, 0x4d, 0x06, 0x70, 0xb6, 0x8b, 0x7c, 0x07, 0x79, 0x97, 0x05, 0x81,
	0xb4, 0x1b, 0xc8, 0x67, 0x77, 0xd7, 0x6c, 0xef, 0xb2, 0x20, 0xa0, 0x06, 0x45, 0x0e, 0x61, 0x73,
	0xc8, 0x02, 0x16, 0xba, 0xdc, 0x71, 0xcf, 0x58, 0x38, 0xe6, 0xd2, 0x6e, 0xe1, 0xc6, 0xc6, 0xba,
	0x32, 0x1a, 0x64, 0x17, 0x81, 0x74, 0x63, 0x98, 0x16, 0x25, 0xe9, 0x42, 0x0d, 0xbb, 0x6c, 0xee,
	0xe8, 0xe9, 0xb5, 0x8c, 0x7a, 0x2c, 0x16, 0x6e, 0xaa, 0xe1, 0x42, 0x90, 0xcd, 0xbf, 0x2c, 0x20,
	0x9f, 0x5e, 0x6f, 0x85, 0xca, 0xac, 0x55, 0x2a, 0x6b, 0xc3, 0x7f, 0xdc, 0x78, 0x12, 0x07, 0x4c,
	0xf9, 0x17, 0xdc, 0x99, 0x37, 0x87, 0xe9, 0xfd, 0xdb, 0x0b, 0xd3, 0xab, 0xa4, 0x4d, 0x96, 0xa9,
	0x2a, 0xbb, 0x4a, 0x55, 0xcf, 0x20, 0xa7, 0x05, 0x3b, 0x87, 0x17, 0xd8, 0x5e, 0x73, 0x81, 0x23,
	0x31, 0xa6, 0x88, 0x69, 0x32, 0xc8, 0x1e, 0x89, 0x31, 0xb1, 0xa1, 0xc8, 0x3c, 0x2f, 0xe2, 0x72,
	0x36, 0xac, 0x33, 0x51, 0x93, 0x97, 0x12, 0x53, 0xdf, 0x95, 0x76, 0xc6, 0x3c, 0x45, 0x46, 0xd2,
	0x0d, 0x88, 0x5d, 0x66, 0x4e, 0xc7, 0xf5, 0xa2, 0x7d, 0x73, 0xa9, 0xf6, 0x6d, 0xfe, 0x56, 0x84,
	0x9c, 0xae, 0xd9, 0xc2, 0x6c, 0xa5, 0xbb, 0xfb, 0x11, 0x54, 0x93, 0x27, 0xc4, 0x18, 0x33, 0x68,
	0x4c, 0x9e, 0x95, 0x43, 0x84, 0x6c, 0x41, 0xde, 0xe3, 0x53, 0x75, 0x86, 0x87, 0xd5, 0xa8, 0x11,
	0x34, 0x0d, 0xea, 0x26, 0x70, 0xd4, 0xd5, 0xd4, 0x7c, 0x14, 0x6c, 0x3c, 0xdf, 0xbd, 0xa6, 0x5d,
	0x06, 0x57, 0x53, 0x4e, 0x4b, 0x6e, 0xb2, 0xd2, 0x77, 0xd2, 0xeb, 0xe4, 0xab, 0xa1, 0x4a, 0x13,
	0x29, 0x9d, 0x85, 0xc2, 0x72, 0x16, 0xe6, 0x24, 0x51, 0xfc, 0x42, 0x92, 0x58, 0xa2, 0x9c, 0xd2,
	0x0a, 0xe5, 0x3c, 0x82, 0xaa, 0x36, 0xba, 0x22, 0x94, 0xf1, 0x84, 0x7b, 0xc9, 0xb3, 0x50, 0x19,
	0x33, 0xd9, 0x4d, 0x54, 0x3a, 0xc4, 0x11, 0xf3, 0x83, 0x84, 0x22, 0x4a, 0x34, 0x91, 0xc8, 0x13,
	0xd8, 0xd0, 0xab, 0x38, 0xe2, 0x4e, 0xc4, 0x99, 0x14, 0x21, 0x3e, 0x0e, 0x65, 0x5a, 0x4b, 0xb4,
	0x14, 0x95, 0xfa, 0x5d, 0x8d, 0xf8, 0x05, 0x8f, 0x14, 0xf7, 0xf0, 0x85, 0x28, 0xd1, 0xb9, 0xbc,
	0x4a, 0x13, 0xb5, 0x4f, 0x68, 0x62, 0x4e, 0x70, 0x1b, 0x69, 0x82, 0x7b, 0x0c, 0x35, 0x7e, 0xc9,
	0xdd, 0x58, 0x71, 0xcf, 0xd1, 0xf7, 0xc6, 0x97, 0xa0, 0x44, 0xab, 0x33, 0x65, 0x57, 0x78, 0x9c,
	0x7c, 0x80, 0xfa, 0x39, 0x77, 0x5d, 0x76, 0xee, 0x4c, 0x23, 0xee, 0x4f, 0x98, 0x9e, 0xa3, 0x2d,
	0x6c, 0xc3, 0x6f, 0xaf, 0x29, 0x4d, 0xfb, 0x0d, 0xe2, 0xdf, 0xcd, 0xe0, 0xfd, 0x50, 0x45, 0x57,
	0x74, 0xf3, 0x7c, 0x59, 0xab, 0x07, 0x5d, 0x2a, 0x11, 0xb1, 0xf1, 0x62, 0x3e, 0xef, 0x5c, 0x3b,
	0xe8, 0x27, 0x06, 0x39, 0x1b, 0x74, 0x99, 0x16, 0xd7, 0x72, 0xc6, 0xf6, 0xbf, 0xc5, 0x19, 0xf6,
	0xd7, 0x73, 0xc6, 0x7c, 0x5c, 0xef, 0x7d, 0x7e, 0x5c, 0x77, 0x0e, 0x60, 0x6b, 0x5d, 0xbe, 0xf4,
	0x97, 0xb5, 0xa6, 0x74, 0x0b, 0x7b, 0x41, 0x2f, 0x75, 0x11, 0x4d, 0xc7, 0x66, 0x50, 0x67, 0x84,
	0x1f, 0x33, 0x2f, 0xac, 0x66, 0x0c, 0xb5, 0xa5, 0x04, 0xdd, 0x30, 0xfc, 0x89, 0x5b, 0xf3, 0xd9,
	0x86, 0x6e, 0x77, 0xa1, 0x2c, 0x02, 0xcf, 0x31, 0xae, 0x93, 0x2f, 0x36, 0x11, 0x78, 0xef, 0x67,
	0x4d, 0x1f, 0xf2, 0x8f, 0x89, 0xd1, 0x7c, 0xb0, 0x95, 0x42, 0xfe, 0x11, 0x8d, 0xcd, 0xdf, 0x2d,
	0xa8, 0x2d, 0x65, 0xf3, 0x86, 0x73, 0xf7, 0xd2, 0xa7, 0x64, 0x3e, 0xfb, 0xd0, 0xcf, 0x03, 0xd8,
	0x4b, 0x07, 0xf0, 0xf9, 0x0f, 0x84, 0x79, 0x6c, 0x0c, 0x2a, 0xa9, 0xfa, 0xdc, 0x10, 0xd8, 0xee,
	0x6a, 0x60, 0xb9, 0xeb, 0xae, 0x6f, 0xfe, 0xbb, 0xcc, 0x8f, 0x78, 0x76, 0x0c, 0xdb, 0xeb, 0xdf,
	0x4e, 0x52, 0x81, 0xe2, 0xe9, 0xf1, 0x9b, 0xe3, 0xb7, 0x1f, 0x8e, 0xeb, 0xb7, 0x48, 0x0d, 0xca,
	0x27, 0xa7, 0xdd, 0x6e, 0xbf, 0xdf, 0xeb, 0xf7, 0xea, 0x16, 0x01, 0x28, 0xbc, 0xdc, 0x3f, 0x3c,
	0xea, 0xf7, 0xea, 0x19, 0x52, 0x85, 0x12, 0xed, 0xbf, 0xef, 0xd3, 0x41, 0xbf, 0x57, 0xcf, 0x3e,
	0xfb, 0x19, 0x4a, 0x33, 0x66, 0x23, 0x9b, 0x50, 0x39, 0x3d, 0x3e, 0x79, 0xd7, 0xef, 0x1e, 0xbe,
	0x3c, 0xec, 0xf7, 0xea, 0xb7, 0x48, 0x09, 0x72, 0xdd, 0xfd, 0xa3, 0xa3, 0xba, 0xa5, 0x37, 0xe9,
	0x55, 0xf7, 0x6d, 0xaf, 0x6f, 0x5c, 0xf4, 0xfa, 0x47, 0xfd, 0x57, 0xfb, 0x83, 0x7e, 0x3d, 0xab,
	0x9d, 0x9f, 0x0c, 0xf6, 0x07, 0x87, 0xdd, 0x7a, 0x4e, 0xaf, 0xbb, 0xb4, 0xaf, 0xf5, 0xf9, 0x83,
	0xff, 0xff, 0xf2, 0xbf, 0xb1, 0xaf, 0xce, 0xe2, 0x61, 0xdb, 0x15, 0x93, 0x0e, 0x17, 0xd2, 0x65,
	0x21, 0xf3, 0x58, 0x67, 0x28, 0x55, 0xc4, 0xd9, 0xa4, 0x33, 0x1d, 0xe2, 0x5f, 0xc2, 0x61, 0x01,
	0x3f, 0x36, 0xbf, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x37, 0x08, 0xea, 0x33, 0x0e, 0x00,
	0x00,
}
