// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/codecs/deth/deth.proto

package deth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionTraceStatus int32

const (
	TransactionTraceStatus_UNKNOWN  TransactionTraceStatus = 0
	TransactionTraceStatus_SUCCEED  TransactionTraceStatus = 1
	TransactionTraceStatus_FAILED   TransactionTraceStatus = 2
	TransactionTraceStatus_REVERTED TransactionTraceStatus = 3
)

var TransactionTraceStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCEED",
	2: "FAILED",
	3: "REVERTED",
}

var TransactionTraceStatus_value = map[string]int32{
	"UNKNOWN":  0,
	"SUCCEED":  1,
	"FAILED":   2,
	"REVERTED": 3,
}

func (x TransactionTraceStatus) String() string {
	return proto.EnumName(TransactionTraceStatus_name, int32(x))
}

func (TransactionTraceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{0}
}

type EVMCallType int32

const (
	EVMCallType_UNSPECIFIED EVMCallType = 0
	EVMCallType_CALL        EVMCallType = 1
	EVMCallType_CALLCODE    EVMCallType = 2
	EVMCallType_DELEGATE    EVMCallType = 3
	EVMCallType_STATIC      EVMCallType = 4
	EVMCallType_CREATE      EVMCallType = 5
)

var EVMCallType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "CALL",
	2: "CALLCODE",
	3: "DELEGATE",
	4: "STATIC",
	5: "CREATE",
}

var EVMCallType_value = map[string]int32{
	"UNSPECIFIED": 0,
	"CALL":        1,
	"CALLCODE":    2,
	"DELEGATE":    3,
	"STATIC":      4,
	"CREATE":      5,
}

func (x EVMCallType) String() string {
	return proto.EnumName(EVMCallType_name, int32(x))
}

func (EVMCallType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{1}
}

type Block struct {
	Ver                  int32               `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Hash                 []byte              `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               uint64              `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Size                 uint64              `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Header               *BlockHeader        `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Uncles               []*BlockHeader      `protobuf:"bytes,6,rep,name=uncles,proto3" json:"uncles,omitempty"`
	TransactionTraces    []*TransactionTrace `protobuf:"bytes,10,rep,name=transactionTraces,proto3" json:"transactionTraces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetUncles() []*BlockHeader {
	if m != nil {
		return m.Uncles
	}
	return nil
}

func (m *Block) GetTransactionTraces() []*TransactionTrace {
	if m != nil {
		return m.TransactionTraces
	}
	return nil
}

type TransactionRefs struct {
	Hashes               [][]byte `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRefs) Reset()         { *m = TransactionRefs{} }
func (m *TransactionRefs) String() string { return proto.CompactTextString(m) }
func (*TransactionRefs) ProtoMessage()    {}
func (*TransactionRefs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{1}
}

func (m *TransactionRefs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRefs.Unmarshal(m, b)
}
func (m *TransactionRefs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRefs.Marshal(b, m, deterministic)
}
func (m *TransactionRefs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRefs.Merge(m, src)
}
func (m *TransactionRefs) XXX_Size() int {
	return xxx_messageInfo_TransactionRefs.Size(m)
}
func (m *TransactionRefs) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRefs.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRefs proto.InternalMessageInfo

func (m *TransactionRefs) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type BlockRef struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               uint64   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRef) Reset()         { *m = BlockRef{} }
func (m *BlockRef) String() string { return proto.CompactTextString(m) }
func (*BlockRef) ProtoMessage()    {}
func (*BlockRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{2}
}

func (m *BlockRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRef.Unmarshal(m, b)
}
func (m *BlockRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRef.Marshal(b, m, deterministic)
}
func (m *BlockRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRef.Merge(m, src)
}
func (m *BlockRef) XXX_Size() int {
	return xxx_messageInfo_BlockRef.Size(m)
}
func (m *BlockRef) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRef.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRef proto.InternalMessageInfo

func (m *BlockRef) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockRef) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type BlockHeader struct {
	ParentHash           []byte               `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	UncleHash            []byte               `protobuf:"bytes,2,opt,name=uncle_hash,json=uncleHash,proto3" json:"uncle_hash,omitempty"`
	Coinbase             []byte               `protobuf:"bytes,3,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	StateRoot            []byte               `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	TransactionsRoot     []byte               `protobuf:"bytes,5,opt,name=transactions_root,json=transactionsRoot,proto3" json:"transactions_root,omitempty"`
	ReceiptRoot          []byte               `protobuf:"bytes,6,opt,name=receipt_root,json=receiptRoot,proto3" json:"receipt_root,omitempty"`
	LogsBloom            []byte               `protobuf:"bytes,7,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	Difficulty           *BigInt              `protobuf:"bytes,8,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Number               uint64               `protobuf:"varint,9,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit             uint64               `protobuf:"varint,10,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed              uint64               `protobuf:"varint,11,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData            []byte               `protobuf:"bytes,13,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	MixHash              []byte               `protobuf:"bytes,14,opt,name=mix_hash,json=mixHash,proto3" json:"mix_hash,omitempty"`
	Nonce                uint64               `protobuf:"varint,15,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Hash                 []byte               `protobuf:"bytes,16,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{3}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetUncleHash() []byte {
	if m != nil {
		return m.UncleHash
	}
	return nil
}

func (m *BlockHeader) GetCoinbase() []byte {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *BlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeader) GetTransactionsRoot() []byte {
	if m != nil {
		return m.TransactionsRoot
	}
	return nil
}

func (m *BlockHeader) GetReceiptRoot() []byte {
	if m != nil {
		return m.ReceiptRoot
	}
	return nil
}

func (m *BlockHeader) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *BlockHeader) GetDifficulty() *BigInt {
	if m != nil {
		return m.Difficulty
	}
	return nil
}

func (m *BlockHeader) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockHeader) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *BlockHeader) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BlockHeader) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *BlockHeader) GetMixHash() []byte {
	if m != nil {
		return m.MixHash
	}
	return nil
}

func (m *BlockHeader) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BigInt struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigInt) Reset()         { *m = BigInt{} }
func (m *BigInt) String() string { return proto.CompactTextString(m) }
func (*BigInt) ProtoMessage()    {}
func (*BigInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{4}
}

func (m *BigInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigInt.Unmarshal(m, b)
}
func (m *BigInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigInt.Marshal(b, m, deterministic)
}
func (m *BigInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigInt.Merge(m, src)
}
func (m *BigInt) XXX_Size() int {
	return xxx_messageInfo_BigInt.Size(m)
}
func (m *BigInt) XXX_DiscardUnknown() {
	xxx_messageInfo_BigInt.DiscardUnknown(m)
}

var xxx_messageInfo_BigInt proto.InternalMessageInfo

func (m *BigInt) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type TransactionTrace struct {
	// consensus
	To       []byte  `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Nonce    uint64  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasPrice *BigInt `protobuf:"bytes,3,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit uint64  `protobuf:"varint,4,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Value    *BigInt `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Input    []byte  `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	V        *BigInt `protobuf:"bytes,7,opt,name=v,proto3" json:"v,omitempty"`
	R        *BigInt `protobuf:"bytes,8,opt,name=r,proto3" json:"r,omitempty"`
	S        *BigInt `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	// meta
	Index                uint32                 `protobuf:"varint,20,opt,name=index,proto3" json:"index,omitempty"`
	Hash                 []byte                 `protobuf:"bytes,21,opt,name=hash,proto3" json:"hash,omitempty"`
	From                 []byte                 `protobuf:"bytes,22,opt,name=from,proto3" json:"from,omitempty"`
	ReturnData           []byte                 `protobuf:"bytes,23,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	PublicKey            []byte                 `protobuf:"bytes,24,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status               TransactionTraceStatus `protobuf:"varint,30,opt,name=status,proto3,enum=dfuse.codecs.deth.TransactionTraceStatus" json:"status,omitempty"`
	Receipt              *TransactionReceipt    `protobuf:"bytes,31,opt,name=receipt,proto3" json:"receipt,omitempty"`
	EvmCalls             []*EVMCall             `protobuf:"bytes,32,rep,name=evm_calls,json=evmCalls,proto3" json:"evm_calls,omitempty"`
	BalanceChanges       []*BalanceChange       `protobuf:"bytes,40,rep,name=balance_changes,json=balanceChanges,proto3" json:"balance_changes,omitempty"`
	NonceChanges         []*NonceChange         `protobuf:"bytes,41,rep,name=nonce_changes,json=nonceChanges,proto3" json:"nonce_changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TransactionTrace) Reset()         { *m = TransactionTrace{} }
func (m *TransactionTrace) String() string { return proto.CompactTextString(m) }
func (*TransactionTrace) ProtoMessage()    {}
func (*TransactionTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{5}
}

func (m *TransactionTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionTrace.Unmarshal(m, b)
}
func (m *TransactionTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionTrace.Marshal(b, m, deterministic)
}
func (m *TransactionTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionTrace.Merge(m, src)
}
func (m *TransactionTrace) XXX_Size() int {
	return xxx_messageInfo_TransactionTrace.Size(m)
}
func (m *TransactionTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionTrace.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionTrace proto.InternalMessageInfo

func (m *TransactionTrace) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransactionTrace) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionTrace) GetGasPrice() *BigInt {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *TransactionTrace) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *TransactionTrace) GetValue() *BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TransactionTrace) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *TransactionTrace) GetV() *BigInt {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *TransactionTrace) GetR() *BigInt {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *TransactionTrace) GetS() *BigInt {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *TransactionTrace) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TransactionTrace) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *TransactionTrace) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransactionTrace) GetReturnData() []byte {
	if m != nil {
		return m.ReturnData
	}
	return nil
}

func (m *TransactionTrace) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *TransactionTrace) GetStatus() TransactionTraceStatus {
	if m != nil {
		return m.Status
	}
	return TransactionTraceStatus_UNKNOWN
}

func (m *TransactionTrace) GetReceipt() *TransactionReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *TransactionTrace) GetEvmCalls() []*EVMCall {
	if m != nil {
		return m.EvmCalls
	}
	return nil
}

func (m *TransactionTrace) GetBalanceChanges() []*BalanceChange {
	if m != nil {
		return m.BalanceChanges
	}
	return nil
}

func (m *TransactionTrace) GetNonceChanges() []*NonceChange {
	if m != nil {
		return m.NonceChanges
	}
	return nil
}

type TransactionReceipt struct {
	// consensus
	StateRoot            []byte      `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	CumulativeGasUsed    uint64      `protobuf:"varint,2,opt,name=cumulative_gas_used,json=cumulativeGasUsed,proto3" json:"cumulative_gas_used,omitempty"`
	LogsBloom            []byte      `protobuf:"bytes,3,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	Logs                 []*EventLog `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TransactionReceipt) Reset()         { *m = TransactionReceipt{} }
func (m *TransactionReceipt) String() string { return proto.CompactTextString(m) }
func (*TransactionReceipt) ProtoMessage()    {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{6}
}

func (m *TransactionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReceipt.Unmarshal(m, b)
}
func (m *TransactionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReceipt.Marshal(b, m, deterministic)
}
func (m *TransactionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReceipt.Merge(m, src)
}
func (m *TransactionReceipt) XXX_Size() int {
	return xxx_messageInfo_TransactionReceipt.Size(m)
}
func (m *TransactionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReceipt proto.InternalMessageInfo

func (m *TransactionReceipt) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *TransactionReceipt) GetCumulativeGasUsed() uint64 {
	if m != nil {
		return m.CumulativeGasUsed
	}
	return 0
}

func (m *TransactionReceipt) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *TransactionReceipt) GetLogs() []*EventLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

type EventLog struct {
	// consensus
	Address []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics  [][]byte `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data    []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// supplement
	Index                uint32   `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventLog) Reset()         { *m = EventLog{} }
func (m *EventLog) String() string { return proto.CompactTextString(m) }
func (*EventLog) ProtoMessage()    {}
func (*EventLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{7}
}

func (m *EventLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLog.Unmarshal(m, b)
}
func (m *EventLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLog.Marshal(b, m, deterministic)
}
func (m *EventLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLog.Merge(m, src)
}
func (m *EventLog) XXX_Size() int {
	return xxx_messageInfo_EventLog.Size(m)
}
func (m *EventLog) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLog.DiscardUnknown(m)
}

var xxx_messageInfo_EventLog proto.InternalMessageInfo

func (m *EventLog) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *EventLog) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *EventLog) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EventLog) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type EVMCall struct {
	Index                uint32            `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ParentIndex          uint32            `protobuf:"varint,2,opt,name=parent_index,json=parentIndex,proto3" json:"parent_index,omitempty"`
	Depth                uint32            `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	CallType             EVMCallType       `protobuf:"varint,4,opt,name=call_type,json=callType,proto3,enum=dfuse.codecs.deth.EVMCallType" json:"call_type,omitempty"`
	Caller               []byte            `protobuf:"bytes,5,opt,name=caller,proto3" json:"caller,omitempty"`
	Address              []byte            `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Value                *BigInt           `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	GasLimit             uint64            `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasConsumed          uint64            `protobuf:"varint,9,opt,name=gas_consumed,json=gasConsumed,proto3" json:"gas_consumed,omitempty"`
	Failed               bool              `protobuf:"varint,10,opt,name=failed,proto3" json:"failed,omitempty"`
	FailureReason        string            `protobuf:"bytes,11,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	Reverted             bool              `protobuf:"varint,12,opt,name=reverted,proto3" json:"reverted,omitempty"`
	ReturnData           []byte            `protobuf:"bytes,13,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	Input                []byte            `protobuf:"bytes,14,opt,name=input,proto3" json:"input,omitempty"`
	ExecutedCode         bool              `protobuf:"varint,15,opt,name=executed_code,json=executedCode,proto3" json:"executed_code,omitempty"`
	KeccakPreimages      map[string]string `protobuf:"bytes,20,rep,name=keccak_preimages,json=keccakPreimages,proto3" json:"keccak_preimages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StorageChanges       []*StorageChange  `protobuf:"bytes,21,rep,name=storage_changes,json=storageChanges,proto3" json:"storage_changes,omitempty"`
	BalanceChanges       []*BalanceChange  `protobuf:"bytes,22,rep,name=balance_changes,json=balanceChanges,proto3" json:"balance_changes,omitempty"`
	NonceChanges         []*NonceChange    `protobuf:"bytes,24,rep,name=nonce_changes,json=nonceChanges,proto3" json:"nonce_changes,omitempty"`
	Logs                 []*EventLog       `protobuf:"bytes,25,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EVMCall) Reset()         { *m = EVMCall{} }
func (m *EVMCall) String() string { return proto.CompactTextString(m) }
func (*EVMCall) ProtoMessage()    {}
func (*EVMCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{8}
}

func (m *EVMCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVMCall.Unmarshal(m, b)
}
func (m *EVMCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVMCall.Marshal(b, m, deterministic)
}
func (m *EVMCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVMCall.Merge(m, src)
}
func (m *EVMCall) XXX_Size() int {
	return xxx_messageInfo_EVMCall.Size(m)
}
func (m *EVMCall) XXX_DiscardUnknown() {
	xxx_messageInfo_EVMCall.DiscardUnknown(m)
}

var xxx_messageInfo_EVMCall proto.InternalMessageInfo

func (m *EVMCall) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *EVMCall) GetParentIndex() uint32 {
	if m != nil {
		return m.ParentIndex
	}
	return 0
}

func (m *EVMCall) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *EVMCall) GetCallType() EVMCallType {
	if m != nil {
		return m.CallType
	}
	return EVMCallType_UNSPECIFIED
}

func (m *EVMCall) GetCaller() []byte {
	if m != nil {
		return m.Caller
	}
	return nil
}

func (m *EVMCall) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *EVMCall) GetValue() *BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *EVMCall) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *EVMCall) GetGasConsumed() uint64 {
	if m != nil {
		return m.GasConsumed
	}
	return 0
}

func (m *EVMCall) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *EVMCall) GetFailureReason() string {
	if m != nil {
		return m.FailureReason
	}
	return ""
}

func (m *EVMCall) GetReverted() bool {
	if m != nil {
		return m.Reverted
	}
	return false
}

func (m *EVMCall) GetReturnData() []byte {
	if m != nil {
		return m.ReturnData
	}
	return nil
}

func (m *EVMCall) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *EVMCall) GetExecutedCode() bool {
	if m != nil {
		return m.ExecutedCode
	}
	return false
}

func (m *EVMCall) GetKeccakPreimages() map[string]string {
	if m != nil {
		return m.KeccakPreimages
	}
	return nil
}

func (m *EVMCall) GetStorageChanges() []*StorageChange {
	if m != nil {
		return m.StorageChanges
	}
	return nil
}

func (m *EVMCall) GetBalanceChanges() []*BalanceChange {
	if m != nil {
		return m.BalanceChanges
	}
	return nil
}

func (m *EVMCall) GetNonceChanges() []*NonceChange {
	if m != nil {
		return m.NonceChanges
	}
	return nil
}

func (m *EVMCall) GetLogs() []*EventLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

type StorageChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	OldValue             []byte   `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             []byte   `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageChange) Reset()         { *m = StorageChange{} }
func (m *StorageChange) String() string { return proto.CompactTextString(m) }
func (*StorageChange) ProtoMessage()    {}
func (*StorageChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{9}
}

func (m *StorageChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageChange.Unmarshal(m, b)
}
func (m *StorageChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageChange.Marshal(b, m, deterministic)
}
func (m *StorageChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageChange.Merge(m, src)
}
func (m *StorageChange) XXX_Size() int {
	return xxx_messageInfo_StorageChange.Size(m)
}
func (m *StorageChange) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageChange.DiscardUnknown(m)
}

var xxx_messageInfo_StorageChange proto.InternalMessageInfo

func (m *StorageChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *StorageChange) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *StorageChange) GetOldValue() []byte {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *StorageChange) GetNewValue() []byte {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type BalanceChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldValue             *BigInt  `protobuf:"bytes,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             *BigInt  `protobuf:"bytes,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceChange) Reset()         { *m = BalanceChange{} }
func (m *BalanceChange) String() string { return proto.CompactTextString(m) }
func (*BalanceChange) ProtoMessage()    {}
func (*BalanceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{10}
}

func (m *BalanceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceChange.Unmarshal(m, b)
}
func (m *BalanceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceChange.Marshal(b, m, deterministic)
}
func (m *BalanceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceChange.Merge(m, src)
}
func (m *BalanceChange) XXX_Size() int {
	return xxx_messageInfo_BalanceChange.Size(m)
}
func (m *BalanceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceChange.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceChange proto.InternalMessageInfo

func (m *BalanceChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BalanceChange) GetOldValue() *BigInt {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *BalanceChange) GetNewValue() *BigInt {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type NonceChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldValue             uint64   `protobuf:"varint,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             uint64   `protobuf:"varint,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonceChange) Reset()         { *m = NonceChange{} }
func (m *NonceChange) String() string { return proto.CompactTextString(m) }
func (*NonceChange) ProtoMessage()    {}
func (*NonceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{11}
}

func (m *NonceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonceChange.Unmarshal(m, b)
}
func (m *NonceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonceChange.Marshal(b, m, deterministic)
}
func (m *NonceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceChange.Merge(m, src)
}
func (m *NonceChange) XXX_Size() int {
	return xxx_messageInfo_NonceChange.Size(m)
}
func (m *NonceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceChange.DiscardUnknown(m)
}

var xxx_messageInfo_NonceChange proto.InternalMessageInfo

func (m *NonceChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *NonceChange) GetOldValue() uint64 {
	if m != nil {
		return m.OldValue
	}
	return 0
}

func (m *NonceChange) GetNewValue() uint64 {
	if m != nil {
		return m.NewValue
	}
	return 0
}

func init() {
	proto.RegisterEnum("dfuse.codecs.deth.TransactionTraceStatus", TransactionTraceStatus_name, TransactionTraceStatus_value)
	proto.RegisterEnum("dfuse.codecs.deth.EVMCallType", EVMCallType_name, EVMCallType_value)
	proto.RegisterType((*Block)(nil), "dfuse.codecs.deth.Block")
	proto.RegisterType((*TransactionRefs)(nil), "dfuse.codecs.deth.TransactionRefs")
	proto.RegisterType((*BlockRef)(nil), "dfuse.codecs.deth.BlockRef")
	proto.RegisterType((*BlockHeader)(nil), "dfuse.codecs.deth.BlockHeader")
	proto.RegisterType((*BigInt)(nil), "dfuse.codecs.deth.BigInt")
	proto.RegisterType((*TransactionTrace)(nil), "dfuse.codecs.deth.TransactionTrace")
	proto.RegisterType((*TransactionReceipt)(nil), "dfuse.codecs.deth.TransactionReceipt")
	proto.RegisterType((*EventLog)(nil), "dfuse.codecs.deth.EventLog")
	proto.RegisterType((*EVMCall)(nil), "dfuse.codecs.deth.EVMCall")
	proto.RegisterMapType((map[string]string)(nil), "dfuse.codecs.deth.EVMCall.KeccakPreimagesEntry")
	proto.RegisterType((*StorageChange)(nil), "dfuse.codecs.deth.StorageChange")
	proto.RegisterType((*BalanceChange)(nil), "dfuse.codecs.deth.BalanceChange")
	proto.RegisterType((*NonceChange)(nil), "dfuse.codecs.deth.NonceChange")
}

func init() { proto.RegisterFile("dfuse/codecs/deth/deth.proto", fileDescriptor_3f10a8911eca0e2c) }

var fileDescriptor_3f10a8911eca0e2c = []byte{
	// 1446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x7b, 0x6f, 0xdb, 0xb6,
	0x16, 0xaf, 0x1c, 0x3f, 0x8f, 0xed, 0xc4, 0xe5, 0x4d, 0x73, 0xd5, 0xe4, 0xb6, 0x75, 0xdd, 0xdb,
	0x7b, 0xdd, 0x0e, 0xb0, 0x81, 0x0e, 0xc8, 0xba, 0xed, 0x8f, 0x21, 0x71, 0xd4, 0x36, 0x68, 0x96,
	0x76, 0x8c, 0xd3, 0x01, 0xc5, 0x00, 0x81, 0x96, 0x68, 0x47, 0x88, 0x24, 0x1a, 0x22, 0xe5, 0xc6,
	0xfb, 0x26, 0x7b, 0xfc, 0xb1, 0xef, 0xb0, 0x2f, 0x38, 0x90, 0x94, 0x65, 0xd9, 0x71, 0xdc, 0x0c,
	0xd8, 0x3f, 0xc6, 0x79, 0xfc, 0xce, 0xe1, 0xe1, 0x79, 0x51, 0x86, 0xff, 0xb8, 0xc3, 0x98, 0xd3,
	0xae, 0xc3, 0x5c, 0xea, 0xf0, 0xae, 0x4b, 0xc5, 0x85, 0xfa, 0xe9, 0x8c, 0x23, 0x26, 0x18, 0xba,
	0xab, 0xb4, 0x1d, 0xad, 0xed, 0x48, 0xc5, 0xee, 0xa3, 0x11, 0x63, 0x23, 0x9f, 0x76, 0x15, 0x60,
	0x10, 0x0f, 0xbb, 0xc2, 0x0b, 0x28, 0x17, 0x24, 0x18, 0x6b, 0x9b, 0xd6, 0xef, 0x39, 0x28, 0x1c,
	0xfa, 0xcc, 0xb9, 0x44, 0x0d, 0xd8, 0x98, 0xd0, 0xc8, 0x34, 0x9a, 0x46, 0xbb, 0x80, 0x25, 0x89,
	0x10, 0xe4, 0x2f, 0x08, 0xbf, 0x30, 0x73, 0x4d, 0xa3, 0x5d, 0xc3, 0x8a, 0x46, 0x3b, 0x50, 0x0c,
	0xe3, 0x60, 0x40, 0x23, 0x73, 0xa3, 0x69, 0xb4, 0xf3, 0x38, 0xe1, 0x24, 0x96, 0x7b, 0x3f, 0x53,
	0x33, 0xaf, 0xa4, 0x8a, 0x46, 0xfb, 0x50, 0xbc, 0xa0, 0xc4, 0xa5, 0x91, 0x59, 0x68, 0x1a, 0xed,
	0xea, 0x8b, 0x87, 0x9d, 0x6b, 0x01, 0x76, 0xd4, 0xd9, 0x6f, 0x14, 0x0a, 0x27, 0x68, 0x69, 0x17,
	0x87, 0x8e, 0x4f, 0xb9, 0x59, 0x6c, 0x6e, 0xdc, 0xc6, 0x4e, 0xa3, 0xd1, 0x0f, 0x70, 0x57, 0x44,
	0x24, 0xe4, 0xc4, 0x11, 0x1e, 0x0b, 0xfb, 0x11, 0x71, 0x28, 0x37, 0x41, 0xb9, 0x78, 0xb2, 0xc2,
	0x45, 0x7f, 0x09, 0x8b, 0xaf, 0x5b, 0xb7, 0x9e, 0xc1, 0x56, 0x06, 0x86, 0xe9, 0x90, 0xcb, 0x0c,
	0xc8, 0x4c, 0x50, 0x6e, 0x1a, 0xcd, 0x8d, 0x76, 0x0d, 0x27, 0x5c, 0x6b, 0x1f, 0xca, 0x2a, 0x28,
	0x4c, 0x87, 0x69, 0xe6, 0x8c, 0x95, 0x99, 0xcb, 0x65, 0x33, 0xd7, 0xfa, 0x23, 0x0f, 0xd5, 0xcc,
	0x6d, 0xd0, 0x23, 0xa8, 0x8e, 0x49, 0x44, 0x43, 0x61, 0x67, 0x5c, 0x80, 0x16, 0xbd, 0x91, 0x8e,
	0x1e, 0x00, 0xa8, 0x0b, 0xdb, 0x99, 0xe2, 0x54, 0x94, 0x44, 0xa9, 0x77, 0xa1, 0xec, 0x30, 0x2f,
	0x1c, 0x10, 0x4e, 0x55, 0x8d, 0x6a, 0x38, 0xe5, 0xa5, 0x29, 0x17, 0x44, 0x50, 0x3b, 0x62, 0x4c,
	0xa8, 0x5a, 0xd5, 0x70, 0x45, 0x49, 0x30, 0x63, 0x02, 0x7d, 0xb1, 0x90, 0x40, 0xae, 0x51, 0x05,
	0x85, 0x6a, 0x64, 0x15, 0x0a, 0xfc, 0x18, 0x6a, 0x11, 0x75, 0xa8, 0x37, 0x16, 0x1a, 0x57, 0x54,
	0xb8, 0x6a, 0x22, 0x53, 0x90, 0x07, 0x00, 0x3e, 0x1b, 0x71, 0x7b, 0xe0, 0x33, 0x16, 0x98, 0x25,
	0x7d, 0x9c, 0x94, 0x1c, 0x4a, 0x01, 0xfa, 0x1a, 0xc0, 0xf5, 0x86, 0x43, 0xcf, 0x89, 0x7d, 0x31,
	0x35, 0xcb, 0xaa, 0x47, 0xee, 0xaf, 0xaa, 0xb5, 0x37, 0x3a, 0x0e, 0x05, 0xce, 0x80, 0x33, 0xc9,
	0xac, 0x2c, 0xb4, 0xe1, 0x1e, 0x54, 0x46, 0x84, 0xdb, 0xbe, 0x17, 0x78, 0xc2, 0x04, 0xa5, 0x2a,
	0x8f, 0x08, 0x3f, 0x91, 0x3c, 0xba, 0x0f, 0x92, 0xb6, 0x63, 0x4e, 0x5d, 0xb3, 0xaa, 0x74, 0xa5,
	0x11, 0xe1, 0xe7, 0x9c, 0xba, 0xe8, 0x25, 0x54, 0xd2, 0xc9, 0x30, 0x6b, 0x2a, 0x92, 0xdd, 0x8e,
	0x9e, 0x9d, 0xce, 0x6c, 0x76, 0x3a, 0xfd, 0x19, 0x02, 0xcf, 0xc1, 0xf2, 0x8e, 0xf4, 0x4a, 0x44,
	0xc4, 0x76, 0x89, 0x20, 0x66, 0x5d, 0xdf, 0x51, 0x49, 0x8e, 0x88, 0x20, 0xf2, 0xcc, 0xc0, 0xbb,
	0xd2, 0xa5, 0xda, 0x54, 0xca, 0x52, 0xe0, 0x5d, 0xa9, 0x42, 0x6d, 0x43, 0x21, 0x64, 0xa1, 0x43,
	0xcd, 0x2d, 0x15, 0x8b, 0x66, 0xd2, 0xd6, 0x69, 0xcc, 0x5b, 0xa7, 0xf5, 0x10, 0x8a, 0x3a, 0x07,
	0xd2, 0x66, 0x30, 0x15, 0xaa, 0xf7, 0xa4, 0x5a, 0x33, 0xad, 0x5f, 0x8b, 0xd0, 0x58, 0xee, 0x66,
	0xb4, 0x09, 0x39, 0xc1, 0x12, 0x5c, 0x4e, 0xb0, 0xf9, 0x71, 0xb9, 0xec, 0x71, 0xfb, 0x3a, 0x61,
	0xe3, 0xc8, 0x73, 0x74, 0xbb, 0xac, 0x2d, 0x81, 0xcc, 0xdf, 0x7b, 0x09, 0x5d, 0x4c, 0x74, 0x7e,
	0x29, 0xd1, 0x5d, 0x28, 0x4c, 0x88, 0x1f, 0xd3, 0x64, 0xee, 0xd7, 0x38, 0xd4, 0x38, 0x19, 0x9b,
	0x17, 0x8e, 0xe3, 0x59, 0x13, 0x69, 0x06, 0xfd, 0x1f, 0x8c, 0x89, 0xea, 0x9a, 0xb5, 0x2e, 0x8c,
	0x89, 0x04, 0x46, 0x9f, 0xef, 0x1f, 0x23, 0x92, 0x40, 0xae, 0x3a, 0x66, 0x3d, 0x90, 0xeb, 0x80,
	0x5c, 0x7a, 0x65, 0x6e, 0x37, 0x8d, 0x76, 0x1d, 0x6b, 0x26, 0xad, 0xcd, 0xbd, 0xcc, 0x58, 0x23,
	0xc8, 0x0f, 0x23, 0x16, 0x98, 0x3b, 0x5a, 0x26, 0x69, 0x39, 0xc2, 0x11, 0x15, 0x71, 0x14, 0xea,
	0xa6, 0xf8, 0xb7, 0x1e, 0x61, 0x2d, 0x52, 0x5d, 0xf1, 0x00, 0x60, 0x1c, 0x0f, 0x7c, 0xcf, 0xb1,
	0x2f, 0xe9, 0xd4, 0x34, 0x75, 0xd3, 0x68, 0xc9, 0x5b, 0x3a, 0x45, 0x07, 0x50, 0x94, 0x43, 0x19,
	0x73, 0xf3, 0x61, 0xd3, 0x68, 0x6f, 0xbe, 0x78, 0x76, 0x8b, 0xed, 0x75, 0xa6, 0x0c, 0x70, 0x62,
	0x88, 0xbe, 0x83, 0x52, 0x32, 0x89, 0xe6, 0x23, 0x75, 0xdf, 0xa7, 0xeb, 0x7d, 0xe0, 0x64, 0x6c,
	0x67, 0x56, 0xe8, 0x2b, 0xa8, 0xd0, 0x49, 0x60, 0x3b, 0xc4, 0xf7, 0xb9, 0xd9, 0x54, 0x4b, 0x74,
	0x77, 0x85, 0x0b, 0xeb, 0xc3, 0xf7, 0x3d, 0xe2, 0xfb, 0xb8, 0x4c, 0x27, 0x81, 0x24, 0x38, 0x3a,
	0x86, 0xad, 0x01, 0xf1, 0x49, 0xe8, 0x50, 0xdb, 0xb9, 0x20, 0xe1, 0x88, 0x72, 0xb3, 0xad, 0xcc,
	0x9b, 0xab, 0x32, 0xae, 0x91, 0x3d, 0x05, 0xc4, 0x9b, 0x83, 0x2c, 0xcb, 0x51, 0x0f, 0xea, 0xaa,
	0x4b, 0x53, 0x47, 0xcf, 0x6e, 0x7c, 0x0f, 0x4e, 0xd9, 0xdc, 0x4d, 0x2d, 0x9c, 0x33, 0xbc, 0xf5,
	0xa7, 0x01, 0xe8, 0xfa, 0x45, 0x97, 0x56, 0xa1, 0xb1, 0xbc, 0x0a, 0x3b, 0xf0, 0x2f, 0x27, 0x0e,
	0x62, 0x9f, 0x08, 0x6f, 0x42, 0xed, 0x74, 0x6d, 0xe8, 0xd9, 0xb9, 0x3b, 0x57, 0xbd, 0x4e, 0x16,
	0xc8, 0xe2, 0xaa, 0xdb, 0x58, 0x5e, 0x75, 0x5d, 0xc8, 0x4b, 0xc6, 0xcc, 0xab, 0x0b, 0xec, 0xad,
	0x4a, 0xe4, 0x84, 0x86, 0xe2, 0x84, 0x8d, 0xb0, 0x02, 0xb6, 0x86, 0x50, 0x9e, 0x49, 0x90, 0x09,
	0x25, 0xe2, 0xba, 0x11, 0xe5, 0xb3, 0xb1, 0x9f, 0xb1, 0x72, 0x0d, 0x0a, 0x36, 0xf6, 0x1c, 0x6e,
	0xe6, 0xf4, 0x5b, 0xa4, 0x39, 0xd9, 0x94, 0xaa, 0xf3, 0x74, 0x1c, 0x8a, 0x9e, 0xb7, 0x74, 0x3e,
	0xd3, 0xd2, 0xad, 0xdf, 0x4a, 0x50, 0x4a, 0x6a, 0x38, 0x47, 0x18, 0xd9, 0xa6, 0x7f, 0x0c, 0xb5,
	0xe4, 0x3d, 0xd2, 0xca, 0x9c, 0x52, 0x26, 0x6f, 0xd4, 0xb1, 0x82, 0x6c, 0x43, 0xc1, 0xa5, 0x63,
	0x71, 0xa1, 0xce, 0xab, 0x63, 0xcd, 0xa0, 0x6f, 0xa1, 0x22, 0xbb, 0xc7, 0x16, 0xd3, 0xb1, 0xfe,
	0x2e, 0xd8, 0x5c, 0x59, 0xb9, 0xe4, 0xf4, 0xfe, 0x74, 0x4c, 0x71, 0xd9, 0x49, 0x28, 0x79, 0x33,
	0x49, 0x27, 0xdf, 0x0e, 0x35, 0x9c, 0x70, 0xd9, 0x5c, 0x14, 0x17, 0x73, 0x91, 0x2e, 0x9d, 0xd2,
	0x2d, 0x97, 0xce, 0xc2, 0x0a, 0x2b, 0x2f, 0xad, 0xb0, 0xc7, 0x50, 0x93, 0x4a, 0x87, 0x85, 0x3c,
	0x0e, 0xa8, 0x9b, 0x3c, 0x33, 0xd5, 0x11, 0xe1, 0xbd, 0x44, 0x24, 0x43, 0x1c, 0x12, 0xcf, 0xa7,
	0xae, 0x7a, 0x68, 0xca, 0x38, 0xe1, 0xd0, 0x53, 0xd8, 0x94, 0x54, 0x1c, 0x51, 0x3b, 0xa2, 0x84,
	0xb3, 0x50, 0x3d, 0x36, 0x15, 0x5c, 0x4f, 0xa4, 0x58, 0x09, 0xe5, 0x3b, 0x1d, 0xd1, 0x09, 0x8d,
	0x04, 0x75, 0xd5, 0x8b, 0x53, 0xc6, 0x29, 0xbf, 0xbc, 0x40, 0xea, 0xd7, 0x16, 0x48, 0xba, 0x30,
	0x37, 0xb3, 0x0b, 0xf3, 0x09, 0xd4, 0xe9, 0x15, 0x75, 0x62, 0x41, 0x5d, 0x5b, 0xde, 0x5b, 0xbd,
	0x2c, 0x65, 0x5c, 0x9b, 0x09, 0x7b, 0xcc, 0xa5, 0xe8, 0x23, 0x34, 0x2e, 0xa9, 0xe3, 0x90, 0x4b,
	0x7b, 0x1c, 0x51, 0x2f, 0x20, 0x72, 0xae, 0xb6, 0x55, 0x5b, 0x76, 0x6f, 0xae, 0x4e, 0xe7, 0xad,
	0x32, 0x79, 0x3f, 0xb3, 0xb0, 0x42, 0x11, 0x4d, 0xf1, 0xd6, 0xe5, 0xa2, 0x54, 0xce, 0x3e, 0x17,
	0x2c, 0x22, 0xa3, 0xf9, 0xc8, 0xde, 0xbb, 0x71, 0xf6, 0xcf, 0x34, 0x72, 0x36, 0xfb, 0x3c, 0xcb,
	0xae, 0x5c, 0x23, 0x3b, 0xff, 0xd4, 0x1a, 0x31, 0xff, 0xfe, 0x1a, 0x49, 0x27, 0xf8, 0xfe, 0x2d,
	0x27, 0x78, 0xf7, 0x10, 0xb6, 0x57, 0x25, 0x4d, 0x7e, 0x67, 0xcb, 0xa5, 0x6f, 0xa8, 0x9e, 0x90,
	0xa4, 0x2c, 0xa6, 0xee, 0xdc, 0x9c, 0x92, 0x69, 0xe6, 0x9b, 0xdc, 0x4b, 0xa3, 0x15, 0x43, 0x7d,
	0x21, 0x4b, 0x6b, 0x56, 0x41, 0xe2, 0x56, 0x7f, 0x0e, 0x2a, 0xb7, 0x7b, 0x50, 0x61, 0xbe, 0x6b,
	0x6b, 0xd7, 0xc9, 0x97, 0x20, 0xf3, 0xdd, 0x0f, 0xb3, 0xe6, 0x0f, 0xe9, 0xa7, 0x44, 0xa9, 0x3f,
	0x04, 0xcb, 0x21, 0xfd, 0xa4, 0x94, 0xad, 0x5f, 0x0c, 0xa8, 0x2f, 0xa4, 0x74, 0xcd, 0xb9, 0xfb,
	0xd9, 0x53, 0x72, 0x9f, 0xfd, 0x80, 0x48, 0x03, 0xd8, 0xcf, 0x06, 0xf0, 0xf9, 0x0f, 0x8f, 0x34,
	0x36, 0x02, 0xd5, 0x4c, 0x91, 0xd6, 0x04, 0xb6, 0xb7, 0x1c, 0x58, 0xfe, 0xa6, 0xeb, 0xeb, 0x7f,
	0x32, 0xe9, 0x11, 0xcf, 0x4f, 0x60, 0x67, 0xf5, 0xeb, 0x8a, 0xaa, 0x50, 0x3a, 0x3f, 0x7d, 0x7b,
	0xfa, 0xee, 0xc7, 0xd3, 0xc6, 0x1d, 0xc9, 0x9c, 0x9d, 0xf7, 0x7a, 0x96, 0x75, 0xd4, 0x30, 0x10,
	0x40, 0xf1, 0xd5, 0xc1, 0xf1, 0x89, 0x75, 0xd4, 0xc8, 0xa1, 0x1a, 0x94, 0xb1, 0xf5, 0xc1, 0xc2,
	0x7d, 0xeb, 0xa8, 0xb1, 0xf1, 0xfc, 0x27, 0xa8, 0x66, 0x56, 0x1c, 0xda, 0x82, 0xea, 0xf9, 0xe9,
	0xd9, 0x7b, 0xab, 0x77, 0xfc, 0xea, 0xd8, 0x3a, 0x6a, 0xdc, 0x41, 0x65, 0xc8, 0xf7, 0x0e, 0x4e,
	0x4e, 0x1a, 0x86, 0xb4, 0x93, 0x54, 0xef, 0xdd, 0x91, 0xa5, 0xbd, 0x1c, 0x59, 0x27, 0xd6, 0xeb,
	0x83, 0xbe, 0xd5, 0xd8, 0x90, 0xfe, 0xcf, 0xfa, 0x07, 0xfd, 0xe3, 0x5e, 0x23, 0x2f, 0xe9, 0x1e,
	0xb6, 0xa4, 0xbc, 0x70, 0xf8, 0xbf, 0x8f, 0xff, 0x1d, 0x79, 0xe2, 0x22, 0x1e, 0x74, 0x1c, 0x16,
	0x74, 0x29, 0xe3, 0x0e, 0x09, 0x89, 0x4b, 0xba, 0x03, 0x2e, 0x22, 0x4a, 0x82, 0xee, 0x78, 0xa0,
	0xfe, 0x21, 0x0e, 0x8a, 0xea, 0x2b, 0xf6, 0xcb, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x30, 0x26,
	0x68, 0x9e, 0x42, 0x0e, 0x00, 0x00,
}
